### ISSUE TITLE
Seems like there's a problem when dragging point?

### ISSUE THREAD

**Issue by AG3** [SVG-Edit/svgedit#100]
I downloaded a svg file of world's coastline, but when I'm trying to drag a point(already convert polyline to path) on a path, the point only move a really small step and the line was shaking each time I drag. Is the svg file too big that cause the problem?

**Comment by codedread** [comment]
Can you attach the file?  Are you using the latest version?  (the shaking path point sounds like an older bug)

**Comment by AG3** [comment]
The bug appear in both online demo and latest release, I'm using chrome on Windows 7. 

File is here:http://7ktw09.com1.z0.glb.clouddn.com/coastline.svg

**Comment by vko-online** [comment]
any news about this?

**Comment by codedread** [comment]
The latest code works properly for me - can you clone the git repository and run a local web server to confirm this?  We might just need to do another release

**Comment by vko-online** [comment]
1. Draw rectangle
2. Select tool
3. Click convert to path
4. Double click on rectangle
5 .Try to move 1 corner point of rectangle, you will see the glitch and cannot move it

**Comment by codedread** [comment]
Please try the latest code checked out of github - not the online demo

**Comment by vko-online** [comment]
@codedread Works ok, thanks, shall we close this?
