### ISSUE TITLE
Text vertically misaligned due to `dominant-baseline="hanging"` attribute

### ISSUE THREAD

**Issue by optimax** [SVG-Edit/svgedit#1000]
**Description:**
A text block appears at the wrong vertical position when there is a `dominant-baseline="hanging"` attribute on the `text` element.

**To Reproduce**
Load the following SVG image into the editor:

```
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xml="http://www.w3.org/XML/1998/namespace" viewBox="0 0 1400 1000">
    <rect width="1399" height="998" rx="0" ry="0" id="background" stroke-width="0.5" style="fill:#FFFFFF;stroke:#000000;"/>  
    <g transform="scale(39.63119) translate(17.66286, 1.892448)" id="content">
      <text text-anchor="middle" dominant-baseline="hanging" font-family="Helvetica" font-size="12.5px" font-style="normal" font-weight="normal" style="fill:#231F20;"><tspan x="0px" y="0px">TEXT</tspan><tspan x="0px" y="12.5px">TEXT</tspan></text>
    </g>  
</svg>
```
The image appears as follows in the editor:

![in-svgedit](https://github.com/user-attachments/assets/9c1c9f3d-3898-451c-9405-d4544188d401)

**Expected behavior**
The image should appear as follows, where the text block is centered both horizontally and vertically within the bounding rectangle:

![Screenshot 2024-10-22 112523](https://github.com/user-attachments/assets/9aa0bc57-ca51-4fe2-81e2-786ab340aab6)

Both Chrome and Edge display it correctly.

**SVG-Edit environment:**
- Version: latest from the `master` branch 
- The file is loaded either via the `Open` menu item, or via ` svgEditor.loadFromURL("/url-of-svg-image");`, it does not matter as th result is the same.

**Environment:**
 - OS: Windows 11 64 bit Desktop
 - Browser: Edge 130.0.2849.46, Chrome 130.0.6723.59

**Comment by jfhenon** [comment]
dominant-baseline was not included in the whitelist of attributes for text. This should be easy to fix. update to follow.

**Comment by optimax** [comment]
Excellent. Thank you!
