### ISSUE TITLE
Build application using only prod dependencies

### ISSUE THREAD

**Issue by VenissaCarolQuadros** [SVG-Edit/svgedit#1009]
**Describe the bug**
I have been trying to build the application using only prod dependencies but haven't been able to find a way to do so. Am I doing this wrong (I haven't been able to find documentation on this)?

**To Reproduce**
Steps to reproduce the behaviour:
1. I have been trying to build the application with docker using the following Dockerfile
```
# Stage 1: Build the application
FROM node:20-alpine as build

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json to install dependencies
# COPY /services/tat/IMAGE-TactileAuthoring/package*.json ./

# Copy complete application code
COPY /services/tat/IMAGE-TactileAuthoring/ .

# Install only production dependencies
ENV NODE_ENV=production
RUN npm install

# Set npm to ignore scripts
ENV npm_config_ignore_scripts=true

# Run build manually ignoring scripts
WORKDIR /app/packages/svgcanvas
RUN npx rollup -c
WORKDIR /app
RUN npx rollup -c
```
This fails since dev dependencies are used in the rollup. 

**Expected behavior**
I would like to be able to build the application with the above docker file instead of `RUN npm install` . 

**SVG-Edit environment (IMPORTANT)**
- File for SVG-Edit: NA
- Version: latest
- Protocol: NA

**Log**
 > [tat build 6/8] RUN npx rollup -c:
0.759 npm warn exec The following package was not found and will be installed: rollup@4.28.0
1.851 [!] Error: Cannot find package 'rimraf' imported from /app/packages/svgcanvas/rollup.config.mjs

**Comment by jfhenon** [comment]
The project is not supporting this build mode. I suggest to build using the proposed script and to remove useless folders in your docker after the build is complete.
