### ISSUE TITLE
page scroll affects the mousedown and mousemove mouse position

### ISSUE THREAD

**Issue by mindfire-io** [SVG-Edit/svgedit#101]
the page scroll value affects the mouse click/drag position.

This can be fixed by changing ( In ['svgcanvas.js'](https://github.com/SVG-Edit/svgedit/blob/master/editor/svgcanvas.js)):

```
            mouse_x = pt.x * current_zoom,
            mouse_y = pt.y * current_zoom;
```

in mousedown (lines 1316,1317) and mousemove (lines 1683, 1684) functions to:

```
            mouse_x = pt.x * current_zoom - window.pageXOffset;
            mouse_y = pt.y * current_zoom - window.pageYOffset;
```

**Comment by mindfire-io** [comment]
also, there are a bunch of other things affected by the scrollheight. the right click menu and scrollwheel zooming are two that i've found so far.

**Comment by brettz9** [comment]
Thank you for the report and fix. Can you provide a reproducible example where problems can be observed without your fix? Latest stable at https://svg-edit.github.io/svgedit/releases/svg-edit-2.8.1/svg-editor.html and latest prerelease at https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/editor/svg-editor.html

**Comment by brettz9** [comment]
Please also describe reproducible steps for the right-click and scrollwheel zooming problem. Are you placing SVG-edit inline?

**Comment by brettz9** [comment]
Closing due to lack of response. Feel free to reopen/comment further if you can provide an example/some steps to reproduce against the latest pre-release: https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/editor/svg-editor.html
