### ISSUE TITLE
Directly changing elements in DOM may lead to the failure of selector in Chrome

### ISSUE THREAD

**Issue by lamlam123tld3** [SVG-Edit/svgedit#102]
I have been using the develop tool to delete and create the same svg elements directly in the DOM.
The newly created elements can no longer move along correctly with the selector.
Seems that the ListMap in svgtransformlist.js introduce this problem.
The same issue dose not exist in Firefox or IE

**Comment by brettz9** [comment]
We need more information. Which development tool are you talking about? What are your exact steps to reproduce a problem? Closing as invalid, but feel free to reopen or file a new issue with more information.
