### ISSUE TITLE
calling canvas.createLayer() programatically doesn't update layers panel

### ISSUE THREAD

**Issue by flintobrien** [SVG-Edit/svgedit#104]
I'm happy to fix this, just looking to narrow down possible options....

### Problem
For our application; on startup of svgedit, we rename "Layer 1" and create a second layer. The layers panel is not repopulated and still shows one layer, "Layer 1" even though the document has been updated correctly.

### Analysis
createLayer does issue `call('changed', [new_layer])`, but the layers panel is looking for change to `svg#svgcontent`, not the `<g>` element of the new layer.

Here's the relevant code in svg-editor.js
```
var elementChanged = function(win, elems) {
  ...
  if (elem && elem.tagName === 'svg') {
    populateLayers();
    updateCanvas();
  }
  ...
}
```

### Possible fixes
1) Add a `class="layer"` to the layer group element to identify layers. Then elementChanged can easily identify a layer change. This is clean but not backwards compatible for old documents (unless we add code to update them on load).
2) In elementChanged, add an additional test for elem.parentNode being `svg` with `id === 'svgcontent'` to identify layer changes.
3) `svgedit.draw.Drawing.prototype.identifyLayers` could issue a more direct broadcast message to notify the layers panel that the layers have changed. I don't know the repercussions of this.
4) Other ideas?

From what I currently know, I'd recommend option 2. If I was designing from scratch, I'd pick 1.

**Comment by codedread** [comment]
Ok, I will have to try look at the code and think more about this (maybe tonight or tomorrow).  I have a gut preference for suggestion #1 with the caveat that documents re-loaded back in would get the class="layer" added like you suggest
