### ISSUE TITLE
Grouping a rotated shape and ungrouping it makes the selection rotate

### ISSUE THREAD

**Issue by slreynolds** [SVG-Edit/svgedit#112]
When using the grouping (G) on a rotated shape (for example rect) and ungrouping it makes the selection on the shape rotate as well.

Tested in _Google Chrome 50.0.2661.94_ and _Firefox 47.0a2 (2016-04-25)_ with _svg-edit-2.8.1_

**Steps to Reproduce:**
1. Create a new design
2. Create two shapes (A and B)
3. group A and B into group C
4. resize group C
5. rotate group C
6. ungroup

It then looks like this:
![svg-edit-bug](https://cloud.githubusercontent.com/assets/6493157/15139490/af244958-1696-11e6-8d13-cd3c597f6391.png)
But isn't this the correct behavior?
![svg-edit-bug2](https://cloud.githubusercontent.com/assets/6493157/15139555/0791e4d8-1697-11e6-90e7-bd049558d72a.png)

Thanks!

**Comment by brettz9** [comment]
I think between step 2 and step 3, you need to add "Rotate one of the shapes", correct?

**Comment by brettz9** [comment]
I think this is now fixed in `master`. Could you check at https://svg-edit.github.io/svgedit/editor/svg-editor-es.html ?

**Comment by slreynolds** [comment]
Thanks @brettz9 , I just tested it and can confirm that its fixed!
