### ISSUE TITLE
Allow setting element width or height via user input

### ISSUE THREAD

**Issue by caccialdo** [SVG-Edit/svgedit#113]
Currently, after selecting an element, the user can only adjust the X and Y position of the element and resize it using the corner handles. It would be quite useful to be able to adjust width and height via an input in a similar fashion as X and Y.

**Comment by drc-gcoakley** [comment]
Which version of SVG-edit and what types of elements are you testing this with? Version 2.8.1 has text input boxes for setting the width and height. They are just to the right of the boxes to set the x & y coordinates as seen marked with the red box in this image.
![image](https://user-images.githubusercontent.com/26071543/38057716-e7eb1fbe-32a5-11e8-865a-e4cf054a827a.png)

**Comment by caccialdo** [comment]
I hadn't checked since. I guess it was added since I opened this issue. Consider it resolved 👍
