### ISSUE TITLE
less buttons on the left when running SVG-edit from PC than from your website

### ISSUE THREAD

**Issue by yipingshen** [SVG-Edit/svgedit#119]
Hello,  I am new to SVG-edit and I'd like to use it for my design work.   I have downladed version2.8.1 and unzip it to a folder in my PC, then I run svg-editor.html from the folder. I found I only have 9 buttons available when I run it.  However it has 14 buttons on the left when I run it from the demo link (https://svg-edit.github.io/svgedit/releases/svg-edit-2.8.1/svg-editor.html).  I dont have shape library, polygon tool, star tool, eye dropper and panning.  I have windows 9 and IE11.  Could anyone provide me an instruction how to correctly run SVG -editor please?  Thank you very much!  You can answer with technical languages and I have friends doing IT can help me out. Thank you!

**Comment by codedread** [comment]
You need to run a local web server to get the full online experience.  Here is how I do it:

python -m SimpleHTTPServer 8888

**Comment by yipingshen** [comment]
Dear Jeff,

Thank you very much! I installed Python 2.7 and it works!

Sorry I am not sure if it is appropriate for me to ask more questions here or I should ask on the website. May I have two more please?
1. This one is not a question.Maybe just a bug can be fixed quickly. When I click the shape library,I can see all the shapes under "basic". I randomly select one shape. I can draw the shape. And when I go back to the shape library I can all the shapes under Basic. However if I select other shape folders other than Basic, then I go back to select Basic folder, the shapes are not displayed. However I still can draw the shape,just the icons gone blank.

2. How can I create my own shape library folder to contain my own shapes? .json files seems to be shape folder files. I tried to use a SVG file to creat one but it didn't work. It must be some rules that I need to follow?

Regards,
Yiping

???? iPhone

? 2016?6?12????2:31?Jeff Schiller <notifications@github.com<mailto:notifications@github.com>> ???


You need to run a local web server to get the full online experience. Here is how I do it:

python -m SimpleHTTPServer 8888

-
