### ISSUE TITLE
svgcanvas

### ISSUE THREAD

**Issue by maneraz** [SVG-Edit/svgedit#123]
hi all,
i am getting an error of 
Unhandled exception at line 559, column 3 in <url>
0x800a139e - JavaScript runtime error: NoModificationAllowedError, 
the code at the line is 
rubberBBox.x += parseInt(svgcontent.getAttribute('x'), 10);
rubberBBox.y += parseInt(svgcontent.getAttribute('y'), 10);

**Comment by brettz9** [comment]
Which browser? Which version of SVG-Edit? What were you trying to do at the time?

**Comment by brettz9** [comment]
Closing due to lack of response. Feel free to provide more information to reproduce. It may have been fixed by a more recent version if you were not using our pre-release versions.
