### ISSUE TITLE
Resizing grouped elements do not resize together

### ISSUE THREAD

**Issue by jaycbrf4** [SVG-Edit/svgedit#126]
I made a pentagram with a circle and a star then grouped them to be one object. When resizing the grouped object, the circle did not resize at the same proportion and the shape was no longer a pentagram as the star was resized and the circle just got smaller.

**Comment by artshevtsov** [comment]
I think that it's better to use svgjs, or raphael js with its groups and sets + transformations for such operations. Google svg is not bad, but here is no support and lots of bugs.

**Comment by c-gonzalez** [comment]
The circle is... a circle. So it can't be deformed... Draw an ellipse or convert your circle to path.

**Comment by brettz9** [comment]
Are you still seeing the issue at https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/editor/svg-editor.html ? If so, can you please provide some more precise steps (as minimal and exact as possible)

**Comment by brettz9** [comment]
Closing due to lack of response. Feel free to provide more precise steps in a new issue or commenting further here if it is still occurring in the latest pre-release or `master`.
