### ISSUE TITLE
Tests fail in Firefox

### ISSUE THREAD

**Issue by iuyiuy** [SVG-Edit/svgedit#128]
On Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0, I get this error, among others:

```
svgedit.utilities: Test getBBoxOfElementAsPath (1, 2, 3)
    failed
    Expected:   
    {
      "x": 0,
      "y": 1,
      "width": 0,
      "height": 0
    }

    Result:     
    {
      "x": 0,
      "y": 0,
      "width": 0,
      "height": 0
    }

    Diff:   
     {
       "x":  0,
       "y": 1,
      0,
       "width":  0,
       "height":  0
     } 
```

The tests all work on Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/51.0.2704.79 Chrome/51.0.2704.79 Safari/537.36.

The mentioned error above in svgutils.js happened in commit 01ad9d7. The other errors seemed to be from before that.

**Comment by brettz9** [comment]
Tests all working now. Close, though feel free to reopen if you come across any other issues...
