### ISSUE TITLE
Cursor style in the menu

### ISSUE THREAD

**Issue by iuyiuy** [SVG-Edit/svgedit#129]
The mouse cursor in the menu is 'default', as in the regular 'arrow' type cursor. Whereas in the toolbar it's the 'pointer', as in the hand that links use.

Even though this is mimicking the style of a regular application, it's still in a browser. So I think it should be the pointer. Github's buttons are also using the pointer cursor, even though the regular browser buttons are using the default style cursor.

I've created [a commit](https://github.com/iuyiuy/svgedit/commit/811e378a22aa7bdf621d79917c88fd0b18eea74a) in my fork with the fix. Do you want me to branch and make a pull request? It is just one line after all.

**Comment by brettz9** [comment]
I personally like the hand tooltip, and I think this is minor enough not to really warrant config, especially given that one can use one's own stylesheet override, but thanks for the offer.

(FWIW, the file `custom.css` which had been the recommended way for config has been renamed...For those copying the default `svgedit-config-sample-es.js` file, the file `svgedit-config.css` will be looked for in the project root. One can also add to the `stylesheets` config array for adding other stylesheets. See the README for the latest install instructions.)

Feel free to comment further if anything is unclear.
