### ISSUE TITLE
Microsoft Japanese ime can not show in firefox when import something to text

### ISSUE THREAD

**Issue by crazyboy12** [SVG-Edit/svgedit#136]
Hi,I find a bug about svgedit,when i use svgedit in firefox,i try to write something in text.i find the  list of candidates of the ime don't show,but in chrome i can see it

**Comment by brettz9** [comment]
Can you provide a screenshot of what is happening in each case? Is the problem still happening in https://svg-edit.github.io/svgedit/releases/svg-edit-2.8.1/svg-editor.html ? Please also try in our latest pre-release: https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/editor/svg-editor.html

**Comment by brettz9** [comment]
Closing due to lack of response. Feel free to reopen/comment further if you can provide a screenshot or some steps to reproduce against the latest pre-release: https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/editor/svg-editor.html
