### ISSUE TITLE
Fire an event at path completion.

### ISSUE THREAD

**Issue by factorde7** [SVG-Edit/svgedit#141]
Hi, I need to fire a custom event on path completion. Means when a user picks up a path tool and starts making a polygon, now as soon as he clicks the first point to complete the polygon, i need to show a prompt where he should enter the name of that polygon, and then I need to create a text element on my canvas with the text entered by the user. Any help? Thanks

**Comment by brettz9** [comment]
In `master`, there is now a `pointsAdded` event. You can check that its `closedSubpath` property is `true`. The grips are also reported.

You can use something like the following (e.g., in your `svgedit-config-es.js`).

```js
svgEditor.ready(function () {
  svgEditor.canvas.bind('pointsAdded', function (win, {closedSubpath, grips}) {
    if (closedSubpath) {
      // Do something
    }
  });
});
```
