### ISSUE TITLE
Check if mouse was clicked (left click) within a path area

### ISSUE THREAD

**Issue by factorde7** [SVG-Edit/svgedit#146]
Hi, I have a custom requirement, i want to catch the x and y coordinates whenever the user clicks on the canvas. Then I need to check if the click was made inside a path or not and get that path element as a jQuery object, then perform custom operation on that path tool.

For example, I have a path with following coordinates:
**`M534.531,1042.81 L985.336,1042.48 L987.188,1271.25 L532.969,1271.25 L534.531,1042.81 z`**

How can I detect if a click was made within this path element and get that path in jQuery.

**Comment by brettz9** [comment]
You can get the x and y coordinates with the click event's `clientX` and `clientY` coordinates: https://stackoverflow.com/a/23744762/271577 .

Then you can use [this method](https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/elementFromPoint) to find the element at that position.

Finally, you can have jQuery wrap that DOM element like `$(domElement)`.

Closing, as that should answer the question. For other usage questions, in the future, please use StackOverflow with the `svg-edit` tag: https://stackoverflow.com/tags/svg-edit
