### ISSUE TITLE
Unable to fill color in uploaded SVG

### ISSUE THREAD

**Issue by gargamul** [SVG-Edit/svgedit#149]
Somehow while using the 2.8.1 version, i was not able to fill color inside the uploaded vectors. Works perfectly well with 2.8.
Since I am using this editor for free, I thought it would be good to contribute by highlighting this issue with the latest version. Let me know if you need more details.

**Comment by brettz9** [comment]
Yes, we would need some sample file to test with, ideally as small as possible to reproduce the problem.

Besides [2.8.1](https://svg-edit.github.io/svgedit/releases/svg-edit-2.8.1/svg-editor.html), we'd welcome you to test against our currently latest pre-release https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/editor/svg-editor.html .

**Comment by brettz9** [comment]
Closing due to lack of response. Feel free to provide more details or a sample (if still occurring with the latest pre-release or `master`) so we can reproduce.
