### ISSUE TITLE
IE Error version 2.8.1

### ISSUE THREAD

**Issue by bsssp** [SVG-Edit/svgedit#153]
Hi this Error was hapened by opening a existing svg in the editor.
 maybe you know why this hapens.
here a screenshot:
![image](https://cloud.githubusercontent.com/assets/13966807/20757443/945a1262-b716-11e6-8693-707ea458141f.png)

KR

**Comment by codedread** [comment]
This seems to be because the SVGRect returned from getBBox() is readonly in IE.  In the latest code, we have an if-check for IE browsers: https://github.com/iuyiuy/svgedit/blob/95fbdf47751f0be7a2ea1ac1c2ef176a09cfd089/editor/svgcanvas.js#L564

Can you see if this helps by trying the trunk?

**Comment by bsssp** [comment]
Many thanks for your answer.
It works after i have added this if-check for IE-Browsers.
