### ISSUE TITLE
Zooming exactly on the same location where clicked or mouse wheele.

### ISSUE THREAD

**Issue by factorde7** [SVG-Edit/svgedit#154]
When I use zoom functionality within SVG-Edit tool, I want it to be zoomed exactly on the same location where my mouse pointer was. Currently it zooms into different proportions so that I lose my target area. Can you look into it and tell me some quick fix? Thanks.

**Comment by brettz9** [comment]
This should now be fixed by the latest changes added via PR #169 . See https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/editor/svg-editor.html to confirm, and feel free to comment further or reopen as needed, but closing as it should be fixed.
