### ISSUE TITLE
Page is refreshed after selecting a dropdown while using Master page

### ISSUE THREAD

**Issue by BIMDevelopement** [SVG-Edit/svgedit#157]
Hi ,

I am using web form with master page. In this scenario , I am facing problem of page refreshed after selecting a drop down .

But while I am using plain aspx page [without master page ], Its working fine . Page is not refreshing .

Can you help me to resolve this issue while using master page. 
[SvgEditorApp.zip](https://github.com/SVG-Edit/svgedit/files/680732/SvgEditorApp.zip)

**Comment by brettz9** [comment]
What do you mean "master page"? What does this have to do with svg-edit? Please provide some more concrete details and ideally some sample code to replicate...

**Comment by brettz9** [comment]
Closing due to lack of response. Feel free to reopen/comment further if you can provide an example/some steps to reproduce against the latest pre-release: https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/editor/svg-editor.html
