### ISSUE TITLE
how download svg image

### ISSUE THREAD

**Issue by Dilipkumaryadav** [SVG-Edit/svgedit#161]
how download image as different farmate like png jpeg

**Comment by adrianbj** [comment]
SVG-Edit > Export

**Comment by Dilipkumaryadav** [comment]
thanks but i mean we want source code where we put svg code it import different formate.

**Comment by brettz9** [comment]
If you want to programmatically get an export, you can call `svgEditor.canvas.rasterExport()` with the arguments: `imgType`, `quality`, and `exportWindowName`.

In prior releases, you will need to first set up an `exported` event listener:

```js
svgEditor.canvas.bind('exported', function (win, obj) {
    // inspect `obj` for the export URL
});
```

The object will be passed with these properties: 

`datauri`, `bloburl`, `svg` (string), `issues`, `issueCodes`, `type` (the image type), `mimeType`, `quality`, `exportWindowName`.

In `master`, I've also allowed a final callback function argument and the method also returns a promise which will be resolved with the object as well. How you want to export it is up to you...

The `exportHandler` function in `svg-editor.js` shows how it can be used.

For example, you might open a new window:

```
const exportWindow = window.open('', exportWindowName); // A hack to get the window via JSON-able name without opening a new one

if (!exportWindow || exportWindow.closed) {
      alert('popup window blocked; please enable popup windows');
      return;
}

exportWindow.location.href = data.bloburl || data.datauri;
```

The PDF export (which still needs fixing per #249) requires that `svgEditor.canvas.exportPDF()` be called instead (with `exportWindowName` and `outputType` (not currently in use, so just omit)... It will return an object with these properties:

`dataurlstring`, `svg` (string), `issues`, `issueCodes`, `exportWindowName`

So for that case (when it is working again) you'd call `svgEditor.canvas.exportPDF` and set the window location to `dataurlstring` instead (and if working in an older non-`master` version, listen for that object using `svgEditor.canvas.bind('exportedPDF', callback)`).

I will close now as that should address the question, but feel free to reopen/comment further if something is not clear.
