### ISSUE TITLE
Faster Freehand onMouseMove?

### ISSUE THREAD

**Issue by jtnw** [SVG-Edit/svgedit#175]
I'm integrating SVGEdit into an application and with all the other javascript the freehand draw is quite slow. The slowdown is more noticeable in my application, but it does happen in the official editor. To reproduce, use the freehand tool and keep drawing a single path until you notice the frame drop. Mainly, I've made this faster by lowering the STEP_COUNT constant, but am also looking at other ways to speed it up. 

On line 1835 of svgcanvas.js I replaced `shape.setAttributeNS(null, 'points', d_attr);` with:

    var point = svgcontent.createSVGPoint();                                       
    point.x = bSpline.x;                                                           
    point.y = bSpline.y;                                                           
    shape.points.appendItem(point);            

Although I'm not positive it makes a difference. Can someone smarter than me run a test or such to determine if this should be used instead of rewriting the whole points attribute? The theory is that the browser doesn't have to re-parse the whole points string.

**Comment by jtnw** [comment]
I just tested on chrome and it does seem like it's a huge improvement. Not sure if it's an improvement on Firefox. Still I'd like to see an official test by someone if possible!

**Comment by codedread** [comment]
Feel free to send a pull request :)

**Comment by jtnw** [comment]
pull request sent to master branch.

**Comment by jtnw** [comment]
Posting here that Robertcck found the pull request to improve speed on IE and Edge.

**Comment by brettz9** [comment]
Confirmed in Firefox and Chrome to be improving performance by about two orders of magnitude (Since mousemove can't be so readily simulated, I wrapped the relevant portion within a loop and logged results when drawing manually). Thanks for the issue and PR!
