### ISSUE TITLE
Poor performance on ie and edge 

### ISSUE THREAD

**Issue by robertcck** [SVG-Edit/svgedit#179]
Hi there,

I noticed poor performance on IE and Edge when drawing. Wondering if there's a fix for it?

Thanks 
Robert

**Comment by robertcck** [comment]
The solution from https://github.com/SVG-Edit/svgedit/issues/175
seems to work well

**Comment by jtnw** [comment]
Hey robertcck, 

I'm glad that worked out for you. Just curious, did you do the STEP_COUNT fix or the shape.points.appendItem(point); fix? 

If the latter I think my pull request should be merged.

**Comment by robertcck** [comment]
@jtnw I only did the shape.points.appendItem(point); fix and its already a hugh improvement. 
I will check the STEP_COUNT fix now and see if it improves the drawing performance again. 

Will let you know the result

**Comment by jtnw** [comment]
I'm not sure I tested it on IE or Edge yet, so that's great news. I'll comment in the original issue so the maintainers know it is a worthwhile improvement.

By the way, I changed STEP_COUNT from 10 to 2 and the freehand paths still look smooth enough to me and it is an even bigger improvement over the appendItem fix. However, I'm not sure the maintainers will modify that in the master branch as it was probably a deliberate design choice, but for my purposes it is fine.

**Comment by robertcck** [comment]
@jtnw I think the STEP_COUNT did improve it a bit but not as noticeable. I was unable to test on IE as my IE isnt working on my machine for some reason

**Comment by jtnw** [comment]
Got it, the appendItems change may have negated the need for changing the STEP_COUNT in your case. If you notice a slowdown in other browsers you may want to try that again.

FYI, what STEP_COUNT is doing is if you move your mouse really quick (say it moves 100px is one frame) the freehand will draw the value of STEP_COUNT points in between. So even if the user only moves a few pixels by default svgEdit draws several points in between. The downside to a lower STEP_COUNT is a slightly less accurate line. 

Anyway, your confirmation helps a lot to know that this improves IE and Edge as I'm still in development of my application and haven't started testing on anything other that Chromium and FF on linux.

**Comment by robertcck** [comment]
@jtnw No worries mate. Thanks again to show your knowledge. 
BTW, are you integrating SvgEditto an application or are you extending SvgEdit?

I am integrating it to an Angular 4 application, removed the gray background with my own bootstrap buttons for the tools. Removed a lot of unnecessary features for my app

**Comment by jtnw** [comment]
@robertcck I'm integrating. I threw out svg-editor.js completely and am just using svgcanvas.js and its dependencies. Note I did copy some code from svg-editor.js into a new file but it's seriously slimmed down using a new ui (using google material components/mdl)

What I'm integrating it into is a custom PDF.js app I wrote a year ago (and am rewriting now)

Originally I wanted to use ionic2 and ng2 or 3, but I'm new to that and don't have the time to learn that yet. I plan to release my app eventually with ionic (or maybe just Cordova), electron and plain old HTML+js

**Comment by robertcck** [comment]
@jtnw Is yours a web app or a mobile app?

I also want to throw away the svg-editor.js due to its size.  However, I only have limited hours for this project and Client just wanted something done ASAP so I decided to modify the file instead. I made my Angular app to dynamically load the svg-editor.js at run time instead. 

The down-side I noticed, when doing a production build for my Angular4 app, the web pack bundling process takes ages and I think I can cut out a lot of time. 

I am hoping to replace this file with my own in the future but its totally up to the client's budget. 

Good to know what you are doing and hopefully we can share our knowledge sometime in the future :)

**Comment by jtnw** [comment]
@robertcck right now it's just a web app, but I do plan on eventually turning it into a mobile app. I assume you're doing an app? 

Personally I have unlimited hours on my project as it's for my company. Throwing away that file wasn't too hard, depending on what tools you need. If you just need select, line, ellipse and rectangle it's easy. Text is a little harder, and shapes a little more harder. Then you have to think if you need layer management, line thickness, opacity, blur, etc. 

Shoot me an email at thejinjt (at) gmail.com and I may be able to share some code with you.

**Comment by robertcck** [comment]
@jtnw The one I am working on is also a web app using Angular 4 as the client wants the app to be accessible from any devices. If you are doing to do this as a mobile app, is ionic2 the pick for you? 
I have done one mobile app using React Native and I like it personally. 

That's good you are able work without time constraints. I wish I can do that too :(

![image](https://cloud.githubusercontent.com/assets/2003517/26089907/7191d11e-3a44-11e7-9fe5-76b37a4d9489.png)

This is what I am working on, all we need is every simple, This is the list I had and currently working already.... 

Select, Line, Freehand, Highlighter, Rectangle, Ellipse, Text, Insert Image, Stroke Width, Colors (Stroke & Fill), Opacity, Download as PNG / SVG / JPEG, Refresh, undo, redo, cut, paste, layer up / down and delete

No layer management, no gray background with full width drawing and I removed the context menu
I customized it so that when dragging by holding the right mouse button will erase the drawing. 

That's very nice of you. I will send you an email in a moment 👍

**Comment by jtnw** [comment]
@robertcck sent an email back. In case anyone else if curious, I pushed some code here: https://github.com/jtnw/drawsvg-minimal

Note the above repo may need a lot of work depending on your needs, but it's a good starting point for throwing away the main svgEdit interface and rolling your own.

**Comment by robertcck** [comment]
@jtnw Thanks Justin. I have replied you back an email :)
