### ISSUE TITLE
how to do smooth pinch to zoom

### ISSUE THREAD

**Issue by kstych** [SVG-Edit/svgedit#18]

**Comment by ian-workcircle** [comment]
Its not very clear what you are meaning here. Maybe further info would help and how to test what you are experiencing.

**Comment by kstych** [comment]
hi, thanks for replying. 
SVGEdit has zoom-in/out based on mouse wheel ..I can also simulate this on mobile devices by capturing touch events and triggering mousewheel (eg hammerjs)

however mousewheel zoom happens in step and it is difficult to control without a smooth feedback (like google maps for example)

**Comment by ibrierley** [comment]
Do you mean its also not very central making it difficult (doesn't seem to move in a linear arc when using mouse, so feels a bit odd.

Oddly I can't even get past the 'store preferences' menu when trying on a touch device, so wondering if there are larger problems there :).

**Comment by kstych** [comment]
yes overall zoom is broken both in performance and aesthetics, there is an option to zoom from center but it is also not very useful, ideally zoom should be relative to mouse pointer location 

and yes, touch is erratic if you simply use stock code, I had to add ontouchstart='doJSMagicClick()' on every element that didnt responded to touch by default

**Comment by SQT2015** [comment]
We are still experiencing this issue. Has anyone located a fix or is there any update on a status for the fix?

**Comment by brettz9** [comment]
You might want to take a look at https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/editor/svg-editor.html and try zooming (with mouse-wheel and shift). This [PR](https://github.com/SVG-Edit/svgedit/pull/169) may have done the trick for you...

**Comment by brettz9** [comment]
Closing due to lack of response. Feel free to reopen if you are still experiencing the problem against the latest [pre-release](https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/editor/svg-editor.html) or `master`.
