### ISSUE TITLE
Chrome 58 version issue in jGraduate

### ISSUE THREAD

**Issue by ajinkyas** [SVG-Edit/svgedit#181]
Double clicking on droplet in jGraduate tab of color picker do not open jPicker view to select a gradient stop color. Issue exists only in chrome version 58
![image](https://cloud.githubusercontent.com/assets/8790387/26111684/6211fac8-3a73-11e7-8866-8eafc28543d4.png)

**Comment by ajinkyas** [comment]
I found the solution myself.

appendChild() was removing binded dblclick event of child. Hence commented below line of code.

`F.parentNode.appendChild(F)`

The function to which this line belongs, is a function to make the border of the selected droplet 'blue', on gradient's panel

**Comment by codedread** [comment]
Can you please send a pull request?

**Comment by ajinkyas** [comment]
I will not be able to send pull request for this. But that line of code is present in **jquery.jgraduate.min.js** file.
Corresponding code in **jquery.jgraduate.js** is
`cur_stop.parentNode.appendChild(cur_stop);`

**Comment by exelzero** [comment]
Hello,

I am currently experiencing this issue right now. I can't have jpicker load when I double click the droplet. I am somewhat confused by the comments above. This is a is still happening to me in chrome 59 (my latest chrome update was 6/21/2017. That is when I updated mine. )

However, this feature works perfectly fine in IExplorer and Firefox. 

Let me know what should I look into?

Thank you in advance!

**Comment by ajinkyas** [comment]
Hi, you need to remove `F.parentNode.appendChild(F)` this line of code from **jquery.jgraduate.min.js**

Not sure if the issue is different in you case, but it fixed my problem.

**Comment by exelzero** [comment]
Hi, thank you so much! I can not believe that is all it was! I've been circling this for a while now. It works like a charm now!

**Comment by codedread** [comment]
Can someone please send a pull request so that the rest of the world can
benefit from your experimentation? :)

**Comment by brettz9** [comment]
Since Chrome 58 share is listed at https://caniuse.com/usage-table as 0.18% , and since I presume that code within `selectStop` had some utility, and since it is working for me now in Chrome (66), I will close. Feel free to reopen or comment further if you have additional information to share.

**Comment by mdvz** [comment]
@brettz9 Just tried in Chrome 66 and then in Chrome 67.0.3396.87 (64-bit) Windows based, does not appear to be working in either version.  Color picker does not appear/display when double-clicking either Gradient color.  Sharing this experience in case others are as well.
