### ISSUE TITLE
Hi Sir When we png image export into svg image by illustrator then not color any part of image.

### ISSUE THREAD

**Issue by Dilipkumaryadav** [SVG-Edit/svgedit#182]
Hi Sir When we png image export into svg image by illustrator then not color any part of image.
example a abc.png image export by illutrator into abc.svg image now open in svg editor then not color any part of image.

**Comment by GoTeamScotch** [comment]
Can you upload the PNG that you experienced the issue with? Press F12 in your browser and look at the "console" tab. Do you see any errors reported when the problem happens?

**Comment by brettz9** [comment]
Closing for lack of reply. Feel free to reopen with an example. Thanks...
