### ISSUE TITLE
Set stroke alignment

### ISSUE THREAD

**Issue by GoTeamScotch** [SVG-Edit/svgedit#183]
As of April 2016, SVG allows the alignment of strokes applied to elements to be changed to one of three values: inside, outside, and center. SVG Edit is not compatible with this new spec.

Specs: [https://svgwg.org/specs/strokes/#SpecifyingStrokeAlignment](https://svgwg.org/specs/strokes/#SpecifyingStrokeAlignment)

To reproduce: Try viewing this SVG in a web browser:
[https://svgwg.org/specs/strokes/images/stroke-alignment-openpath.svg](https://svgwg.org/specs/strokes/images/stroke-alignment-openpath.svg) 
Then, try saving that same SVG file locally and opening it in SVG-Edit. You'll find that it is distorted. Example screenshot:
[Screenshot - click here to view](http://i.imgur.com/fHBvmRr.jpg)

I'm really stumped on this one. In svgcanvas.js where **changeSelectedAttributeNoUndo()** is defined, it uses basically boils down to using the function
`elem.setAttribute(attr, newValue);`
This is a pretty basic JS function and it works well enough for adding the stroke-alignment attribute.

During testing, I was using this to add the stroke-alignment attribute to a text field:
`svgCanvas.getSelectedElems()[0].setAttribute('stroke-alignment', 'center');`
If you run that in the browser's console, targeting the selected element (a text box, for example), it will change the element's stroke-alignment attribute but it will not actually do anything on screen. You can open the source SVG in the browser and see the new attribute. Running svgEditor.updateCanvas() doesn't help. Even though my browser handles it perfectly fine, SVG Edit disregards the attribute. What am I missing here?

FF 54.0 and Chrome 59.0.3071.104

**Comment by codedread** [comment]
Cool - it's a new attribute.  Seems like you need to update editor/sanitize.js

**Comment by GoTeamScotch** [comment]
So add to "svgWhiteList_"? I've done that and so far it's a no go. Any other suggestions?

Example - updated text array item:
`"text": ["class", "clip-path", "clip-rule", "fill", "fill-opacity", "fill-rule", "filter", "font-family", "font-size", "font-style", "font-weight", "id", "mask", "opacity", "requiredFeatures", "stroke", "stroke-dasharray", "stroke-dashoffset", "stroke-linecap", "stroke-linejoin", "stroke-miterlimit", "stroke-opacity", "stroke-width", "stroke-alignment", "style", "systemLanguage", "text-anchor", "transform", "x", "xml:space", "y"]`

**Comment by codedread** [comment]
Ok, I did some investigation here.

There are some open issues with that new attribute in the spec, not sure of it's status - but what I do know is that stroke-alignment is not supported in Chrome or Firefox or Safari yet.  See this file: http://codedread.com/stroke-alignment.svg

That means that no matter what we do in terms of preserving this attribute in SVG-edit, it has no effect on the rendering - browser need to actually support this cool new feature.  See also http://caniuse.com/#search=stroke-align

Maybe one day :-/

To fake this feature in SVG-edit would probably require a lot of work.  The outer/inner stroke would probably need to be a stroke around a non-filled shape that mirrors the size/rotation of the master shape and then use some JavaScript to keep the two shapes in sync as the user changes the size/orientation of the master shape.

**Comment by GoTeamScotch** [comment]
Crap that's too bad. I was excited about this. I guess I misunderstood the examples when I saw them in FF when I checked. Well thanks for looking into it. Much appreciated.

**Comment by brettz9** [comment]
Closing as http://caniuse.com/#search=stroke-align is still showing:

> This CSS property is not supported in any modern browser, nor are there any known plans to support it.

Feel free to reopen if it makes a comeback...
