### ISSUE TITLE
Select tool issue

### ISSUE THREAD

**Issue by sachinbhopi92** [SVG-Edit/svgedit#184]
Hi,
When I draw any shape i.e. rectangle or ellipse it is not deselecting it. Select tool is not activated when I select previous drawn shapes. Is there any issue with library files? Thanks in advance.

**Comment by brettz9** [comment]
Can you clarify what you mean?

When you draw a shape, you are expecting it to be deselected or do you mean when you draw a shape and then try to deselect, it won't deselect?

What do you mean the select tool is not activated when you select previous drawn shapes? Do you mean the icon doesn't show as selected? How are you selecting previous shapes if the tool is not activated?

**Comment by brettz9** [comment]
Closing due to lack of response. Feel free to open with more precise steps to reproduce. Also please test against the latest pre-releases to ensure the issue has not already been fixed.
