### ISSUE TITLE
Chrome "Save as..." does not result in a png

### ISSUE THREAD

**Issue by kritixilithos** [SVG-Edit/svgedit#192]
I want to export the svg as a png. Clicking on "Export > png" tells me to use my browser's "Save as..." button. From what I can see, the browser's "Save as..." button can only save the *entire* website as a html document (with other scripts). It does not appear to be able to save it as a png, so I cannot export the graphics at all.

Browser: Chrome 60 on macOS.

Edit: this works perfectly in Firefox

**Comment by nitroamos** [comment]
I'm seeing this issue using Chrome, too. When I try, I see this exception in the new page it creates:

`about:blank:1 Not allowed to navigate top frame to data URL: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABuUAAAHdCAYAAAAKInQhAAAgAElEQVR4XuzdC5xkdXnn/6cu3XOFmeEyCAJzQQQGEWOigo5B3cgQVyEJiTGJ5mVcg0oIN/GSXVGMuwYJiJtk46pkd40xgiICUSMCmRvo5qYMJhrvsK8/BlGUGZjpW3XV//V9fuc59etD9XTPpXq6pz+Vnf90V53zO7/zPqeK+dfX5/nVjAcCCCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggggAACCPRVoNbX0RkcAQQQQAABBBBAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQSMUI6bAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQAABBBBAAIE+CxDK9RmY4RFAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQAABBBAglOMeQAABBBBAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQKDPAoRyfQZmeAQQQAABB...IIIIDAVAKEclMxsRMCCCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggggAACswsQys1ux5EIIIAAAggggAACCCCAAAIIIIAAAggggAACCCCAAAIITCVAKDcVEzshgAACCCCAAAIIIIAAAggggAACCCCAAAIIIIAAAgggMLsAodzsdhyJAAIIIIAAAggggAACCCCAAAIIIIAAAggggAACCCCAwFQChHJTMbETAggggAACCCCAAAIIIIAAAggggAACCCCAAAIIIIAAArMLEMrNbseRCCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggggAACCEwlQCg3FRM7IYAAAggggAACCCCAAAIIIIAAAggggAACCCCAAAIIIDC7AKHc7HYciQACCCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggggMBUAoRyUzGxEwIIIIAAAggggAACCCCAAAIIIIAAAggggAACCCCAAAKzC/z/douRRqlhj20AAAAASUVORK5CYII=`

**Comment by TomasHurtz** [comment]
I have this problem too - latest browser chrome or FF same result - no way to export "save as in your browser" not possible.

**Comment by brettz9** [comment]
While I am seeing an issue in Firefox with "Save image" (reported as #248) and with PDF export (#249), I am having no problems exporting other image types in Chrome (66) or Firefox (61.0b9), except with the fact that Chrome's File menu "save as" does not work and one must use the context menu (right-click) to get a working save image option. I've updated the alert message to reflect this.

While this doesn't include the alert message fix, you should see that the functionality is working now at https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/editor/svg-editor.html .

Note that a new tab should be opened with the image--it is that image that you are supposed to save.

I will close now as the issue should be resolved, but feel free to reopen/comment further if you can't get it working.

**Comment by TomasHurtz** [comment]
Great - yest, save as now works in a new window ! Excellents.

However, you may also take note when zooming in new version it also zooms entire tools etc... not just the vector   https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/editor/svg-editor.html 

Zooming in this version works correct:
https://svg-edit.github.io/svgedit/releases/svg-edit-2.8.1/svg-editor.html
