### ISSUE TITLE
Can't get the color from a selected element

### ISSUE THREAD

**Issue by DavidGoerig** [SVG-Edit/svgedit#194]
Hi everybody,
im actually trying to do an extension for svgedit, but i encounter a problem. I can't get the color of the current selected object.
I tried with selectedElement.getColor; but it dont work.

If somebody got an idea!
Thank you!
David

**Comment by brettz9** [comment]
You can use `svgEditor.canvas.getSelectedElems()` and then, depending on the element, grab its attributes:

```js
  const els = svgEditor.canvas.getSelectedElems();
  console.log('els', els[0].getAttribute('fill'), els[0].getAttribute('stroke'));
```

Closing as that should address it, but feel free to comment further...
