### ISSUE TITLE
Small (and large/extra-large) icons misplacing rulers position

### ISSUE THREAD

**Issue by soulmare** [SVG-Edit/svgedit#197]
![svgedit-bug](https://user-images.githubusercontent.com/32684597/31404298-4d0b085e-ae04-11e7-9b96-13d381339e46.png)
When setting icons to "small" size, rulers are misplaced.
Chromium Version 61.0.3163.100 (Official Build) Built on Ubuntu , running on Ubuntu 14.04 (64-bit)

**Comment by brettz9** [comment]
This is a dupe of #79 so closing, but feel free to subscribe there for any issue updates.
