### ISSUE TITLE
Animation rotation SVG-editor slow and lag on IE11 in Win 10

### ISSUE THREAD

**Issue by huynvn010193** [SVG-Edit/svgedit#205]
The svg-editor runs on IE 11 of win 10 it looks like the rotation attribute is lag and slow. Can you tell me if I can improve them better?

**Comment by brettz9** [comment]
Do you have some sample code for us to try with?

**Comment by brettz9** [comment]
Closing due to lack of response. Feel free to reopen if you can provide more steps to reproduce.
