### ISSUE TITLE
Filter Effect not working

### ISSUE THREAD

**Issue by Waxxxon** [SVG-Edit/svgedit#211]
Hi everyone,

following Filter Effekt is not working. Am I doing something wrong here or am I using certain functions not yet implemented ?
 
## <defs>
    <filter id="f2" x="0" y="0" width="200%" height="200%">
      <feOffset result="offOut" in="SourceGraphic" dx="20" dy="20" />
      <feGaussianBlur result="blurOut" in="offOut" stdDeviation="10" />
      <feBlend in="SourceGraphic" in2="blurOut" mode="normal" />
    </filter>
  </defs>#

**Comment by brettz9** [comment]
This is working for me:

```svg
<svg width="140" height="140" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
 <defs>
  <filter id="f2" x="0" y="0" width="200%" height="200%">
   <feGaussianBlur stdDeviation="10"/>
  </filter>
 </defs>
 <g class="layer">
  <title>Layer 1</title>
  <rect width="90" height="90" stroke="green" stroke-width="3" fill="yellow" filter="url(#f2)" id="svg_1"/>
 </g>
</svg>
```

It requires SVG having a namespace declaration, however (at least when added through the source editor): see #250 .

Closing as this should work as a workaround (and the namespace issue was filed). Feel free to comment further as needed.
