### ISSUE TITLE
Cannot import image in mobile device

### ISSUE THREAD

**Issue by shah-dhaval** [SVG-Edit/svgedit#214]
I have tried in android and ios device, But when click on File > Import Image no action fires.

**Comment by brettz9** [comment]
Which version of SVG-Edit are you using? Please try against the latest stable or pre-release versions:

You can try the latest stable release at https://svg-edit.github.io/svgedit/releases/svg-edit-2.8.1/svg-editor.html or the latest pre-release at https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/editor/svg-editor-es.html

**Comment by shah-dhaval** [comment]
Thanks for the reply, 
Still not working. I have tested in iPhone 5s, ios 11

**Comment by brettz9** [comment]
Thanks for the reply. Are you getting any error messages in Web Inspector console? https://www.lifewire.com/activate-the-debug-console-in-safari-445798 / https://developer.apple.com/safari/tools/

**Comment by jfhenon** [comment]
no reply for nearly 3 years. please reopen if needed.
