### ISSUE TITLE
Mouse Event Handlers

### ISSUE THREAD

**Issue by sandeep048** [SVG-Edit/svgedit#218]
Is there any API documentation on mouse up/down hover events that I can intercept easily? This project will be immensely when coupled with WebSockets for real time collaboration.

Regards,
Sandeep

**Comment by codedread** [comment]
You should be able to write an extension that fires when mouse events happen.  See the many examples in extensions/

**Comment by sandeep048** [comment]
Managed to create an extension with mouse events and pass coordinates over websocket. I am still unable to replay the mouse events on remote participants end (omitted mousemove events in the example below). Can you kindly explain why the following code is unable to render rectangle. Please suggest a solution to achieve collaborative SVG editor.

```
svgCanvas.setMode('rect');
element = document.getElementById('svgcanvas');

event = document.createEvent("MouseEvent");
event.initMouseEvent("mousedown", true, true, window, 1,
                     100, 100, 100, 250,
                     false, false, false, false,
                     0, null);
element.dispatchEvent(event);


event = document.createEvent("MouseEvent");
event.initMouseEvent("mouseup", true, true, window, 1,
                     250, 200, 250, 450,
                     false, false, false, false,
                     0, null);
element.dispatchEvent(event);`
