### ISSUE TITLE
When trying to draw - everything is out of the canvas

### ISSUE THREAD

**Issue by AmitEshbal** [SVG-Edit/svgedit#220]
Hi there!
I just started using svg-edit, and right away I stumbled upon this problem - The items aren't drawn where the mouse is pointing, but way down and to the right.
https://ibb.co/kpKq7n - check the images, the red circle marks where the mouse is.

Any solution? THANKS!

**Comment by brettz9** [comment]
Please use a current version of SVG-Edit. You can try the latest stable release at https://svg-edit.github.io/svgedit/releases/svg-edit-2.8.1/svg-editor.html or the latest pre-release at https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/editor/svg-editor-es.html

If you are still facing issues, feel free to open a new issue, indicating the SVG-Edit version, your browser version, and the steps to replicate.

Thanks!
