### ISSUE TITLE
Saving image just goes to about:blank

### ISSUE THREAD

**Issue by JonathanYiv** [SVG-Edit/svgedit#225]
https://github.com/SVG-Edit/svgedit/issues/193
Same issue as above.
Chrome 65 and Firefox 59

**Comment by brettz9** [comment]
Please see my comment at #192 : https://github.com/SVG-Edit/svgedit/issues/192#issuecomment-393071359  . Export should be working (except for PDF #249) and "Save Image" is not working in Firefox at the moment (#248 ).

Will close now though feel free to reopen/comment further if still facing any issues that do not include the two mentioned above.
