### ISSUE TITLE
ES6 Modules, Rollup, and Babel

### ISSUE THREAD

**Issue by brettz9** [SVG-Edit/svgedit#235]
This is an issue for tracking the conversion of source to ES6 Modules along with a Rollup routine and Babel plug-in. In doing so, there are some methods mentioned in code that were to be moved between modules (e.g., some `path` modules in `svgcanvas`); these should be moved as well.

Additional ES6 refactoring could then be applied to source as well, such as ES6 classes.

**Comment by codedread** [comment]
Yay for this :-)

Let's also include simple things like:  const, let, arrow functions.

**Comment by brettz9** [comment]
This is now available in `master`, including quite a bit of basic ES6 refactoring, moving the modules per the instructions (though I think in one case I moved to `path.js` instead of a new file of `pathActions.js`) `const`, `let`, arrow functions, destructuring and more...

Though I tried to be careful, I'd expect some glitches to be found, given the sheer amount of code affected...

**Comment by codedread** [comment]
I synced this morning and found out that SVG-edit is not working anymore after your changes.  Can you please put these changes into a branch instead while you're working things out?

(I typically run a local server and then browse to /svgedit/editor/svg-editor.html.  This no longer works)

**Comment by brettz9** [comment]
Needs a config file added... After running `npm install`:

1. Copy `svgedit-config-sample-es.js` (*in project root*) to `svgedit-config-es.js`.
2. Run `npm run build-config`

I obviously need to add this to docs, but wanted to see about any feedback on the process...

**Comment by brettz9** [comment]
When I said there are in all likelihood some glitches, I don't mean it is broken--it is working and passing all tests...

**Comment by brettz9** [comment]
I've added the installation steps (with a little more info) on the [README](https://github.com/SVG-Edit/svgedit/blob/master/README.md#installation).

**Comment by PatrickMennen** [comment]
Currently it does not seem to be possible to import just the SVGCanvas from the library. It seems there is no export in svg-editor.js which is the main library in your package.json

I know that the component  is most probably used as is, but currently I am working on a custom implementation and it would be nice if such an export was available

**Comment by brettz9** [comment]
@PatrickMennen : It is possible. @NeilFraser has kindly agreed for our using his demo, and it is now available on `master` (under `demos/canvas.html`). I added it as an ES6 module (as it is works nicely with our modular source), but those modules can also be bundled (as with Rollup or Webpack) to allow demos which work with older browsers. You might also see his demo at https://neil.fraser.name/news/2018/SvgCanvas.html before integrated with our ES6 changes.

One thing to bear in mind if you're getting into importing individual modules beyond the editor or canvas code (`svgcanvas.js` is inited by instantiation)... Rather than requiring circular dependencies between the modules to allow one dependency to be informed of changes in the other, some modules have `init` functions which are required to set properties/methods that may be queried or called. This allows a parent module to set them without the child module needing to add the parent as a dependency. It also allows the expected properties to be stubbed, as in some of our unit tests, but it comes at the cost that some methods expect `init` to have been called. When importing `svg-editor.js` (or `svgcanvas.js` as in this demo) one doesn't need to worry about any of that, but I thought I'd mention it in this issue and in case anyone was experimenting with other lower-level modules.

And please also bear in mind we've just migrated to ES6 modules with a whole lot of ES6 refactoring having been done, so there are probably some uncaught regressions (one I'm aware of and working on now is with stylesheets which I hope to have a fix for soon).

**Comment by brettz9** [comment]
As far as `main` in `package.json` (or `browser`/`module`), `svg-editor.js` is the closest to this at the moment, but SVG-edit still effectively requires our particular entrance HTML file (`svg-editor.html`, or the new `svg-editor-es.html` source which directly uses modules).

I'd like to see whether loading all of the HTML dynamically will cost us much in performance, as I think it'd be more elegant to let users load the script into their own HTML (as well as open chances for configuring which HTML even gets added), but I'd guess SVG-edit may not be very flexible to alternative styling/placement, with the embedded editor (which adds `svg-editor.html` as an iframe) being the current way to get SVG-edit placed flexibly within a page.

**Comment by PatrickMennen** [comment]
@brettz9 thanks, that solution works, however it would be nice if there was a named export to SVGCanvas in svgeditor.js (you are already importing it anyways ;-)) so that we can at least use the package directly from the node modules without hardlinking to it (or copying it)

Something like: import { Canvas } from 'svg-edit'

**Comment by brettz9** [comment]
@PatrickMennen : First as an FYI, in `master` and in a new npm release 3.0.0.-alpha.4, for `package.json`, I've recently updated `main` to point, as we should, to our non-ES6 (UMD) module entrance file and added `module`, the recommended way to point to our ES6 Module entry file so that tools like Rollup or Webpack can use the information.

I sympathize with the desire to avoid hard-linking paths. However, to encourage people to take advantage of modularity (and the benefits of not needing to build or load the entire file (in this case, `svg-editor.js`), I think there is a better solution than having `svg-editor.js` regurgitate its imports.

As with Node allowing, `require('someModule/someSubmodule/anotherSubmodule')`, this same non-hard-linked-path approach for modules (e.g., `import {xyz} from 'someModule/someSubmodule/anotherSubmodule'`) should apparently be honored by `rollup-plugin-node-resolve` per https://stackoverflow.com/a/42349748/271577 (and per the plugin's reference to the Node resolution algorithm).

I don't know if you'll need to have `rollup-plugin-node-resolve` set `main: false` to avoid resolving relative to our `package.json` `module`-pointed ES6 `dist` file, but I think you should be able to configure the Rollup plugin to get the non-hard-coded submodule path working (i.e., being able to use the likes of: `import SVGCanvas from 'svgedit/editor/svgcanvas';`).

I will close this issue now, but please comment further here if it is successful for you and feel free to open a new issue if you need something on our end to make that possible (without breaking other uses).
