### ISSUE TITLE
Saving svg images results in an empty new tab with the error (see description)

### ISSUE THREAD

**Issue by Pjaerr** [SVG-Edit/svgedit#239]
https://svg-edit.github.io/svgedit/releases/svg-edit-2.8.1/svgedit.compiled.js:461 Not allowed to navigate top frame to data URL: data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIj8+Cjxzdmcgd2lkdGg9IjI0LjAwMDAwMDAwMDAwMDAwNCIgaGVpZ2h0PSIyNC4wMDAwMDAwMDAwMDAwMDQiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6c3ZnPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiA8Zz4KICA8dGl0bGU+TGF5ZXIgMTwvdGl0bGU+CiAgPHBhdGggZD0ibTcuNDEsOC41OGw0LjU5LDQuNTlsNC41OSwtNC41OWwxLjQxLDEuNDJsLTYsNmwtNiwtNmwxLjQxLC0xLjQyeiIgaWQ9InN2Z18xIiBmaWxsPSIjMmYzNTQyIi8+CiA8L2c+Cjwvc3ZnPg== (anonymous) @ https://svg-edit.github.io/svgedit/releases/svg-edit-2.8.1/svgedit.compiled.js:461

**Comment by brettz9** [comment]
In Chrome, when I visit the latest at https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/editor/svg-editor.html and add your data URL via the "Image Tool" icon on the left toolbar, I get an image ok.

In Firefox, nothing appears to happen except for an alert.

If this is what you are seeing, please change the issue title to reflect the current status.

**Comment by brettz9** [comment]
Or were you going to "Export" instead of "save image"? This looks like the same error reported at #192 in which case this should be closed and marked as a dupe.

**Comment by Pjaerr** [comment]
It was when I was saving, it works now though :/  Ill close the issue.
