### ISSUE TITLE
Migrate to JSDoc (along with package.json script)

### ISSUE THREAD

**Issue by brettz9** [SVG-Edit/svgedit#240]
[JSDoc](http://usejsdoc.org/) supports [es2015-classes](http://usejsdoc.org/howto-es2015-classes.html), etc.

**Comment by tetedacier** [comment]
Hello, I provided basic documentation generation update in a [PR](https://github.com/SVG-Edit/svgedit/pull/244).

**Comment by brettz9** [comment]
Sweet! Thanks for your help on this!

**Comment by brettz9** [comment]
See #244 on issue with exports...

**Comment by brettz9** [comment]
FYI, I've put the jsdoc output within `/docs/jsdoc/` (though hidden in `.gitignore`), published it on `gh-pages` (without the `.gitignore`) (and linked to this from our `master`'s README): https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/docs/jsdoc/index.html . Thanks again!
