### ISSUE TITLE
Parsing errors

### ISSUE THREAD

**Issue by TomasHurtz** [SVG-Edit/svgedit#247]
Can't save - so trying to copy/paste into new browser window to try there....... when copy paste SVG code to new browser, I get :

"There were parsing errors in your SVG source.
Revert back to original SVG source?"

and it reverts to default.

**Comment by brettz9** [comment]
Which version were you trying with? Can you paste your SVG source here?

**Comment by brettz9** [comment]
Ok, the issue, whatever it was, appears to have now been fixed. You can try against our latest prerelease at: https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/editor/svg-editor.html

Closing as I confirmed the problem in 2.8.1 but found it gone in the pre-release. Feel free to comment further if needed.
