### ISSUE TITLE
Shape selection not working as expected with the rectangle / circle tool active

### ISSUE THREAD

**Issue by glutanimate** [SVG-Edit/svgedit#262]
Before diving into the actual bug report, let me just say that I really appreciate all of the recent activity on svgedit. Thanks a lot in particular to @brettz9 for reinvigorating this project!

----

## Overview

With the rectangle or circle tool active, clicking on a recently drawn shape used to automatically switch the tool to selection mode and select the shape, allowing the user to quickly move the shape around without having to manually switch to the selection tool. This no longer works in recent builds of SVG-Edit.

## Steps to reproduce

1. Draw circle/rectangle
2. Click on circle/rectangle

## Expected behavior (present under SVG Edit 2.6 – 2.8.1 on Firefox)

- tool switches to selection tool
- circle/rectangle becomes selected

### SVG-Edit 2.5.1 – 2.8.1, and master before 3.0.0 work

**Google Chrome and Chromium QtWebEngine**

- rectangle: no action
- circle: 1x1 circle is drawn on top of existing circle at mouse click position

Associated error message when no action is performed:

    Uncaught TypeError: Cannot read property 'parentNode' of null
        at HTMLDivElement.mouseUp (svgcanvas.js:2212)
        at HTMLDivElement.dispatch (jquery.js:3)
        at HTMLDivElement.i (jquery.js:3)

**Firefox**

Working as expected

### SVG-Edit 3.0.0 Alpha pre-release 4 standard / ES6

**Google Chrome and Chromium QtWebEngine**

- rectangle: 1x1 rectangle is drawn on top of existing rectangle at mouse click position
- circle: 1x1 circle is drawn on top of existing circle at mouse click position

**Firefox**

In both cases:

- tool switches to selection tool
- *canvas* becomes selected

No associated error message.

### Version information

- Firefox: 60.0.2
- Google Chrome: 67.0.3396.87
- Tested on:
   + Ubuntu 18.04
   + macOS Sierra
   + Windows 10

----------

This is an [issue](https://github.com/glutanimate/image-occlusion-enhanced/issues/54) that has been somewhat of a blocker on my [downstream project](https://github.com/glutanimate/image-occlusion-enhanced/projects/1), so it would really be a major help if we could somehow track this down and fix it.

If there is anything else I can do to help on my end please let me know!

**Comment by brettz9** [comment]
Thanks for the encouragement, and a very helpful report, thank you!

I was able to confirm (and also see it was happening as early as 3.0.0 alpha 2) and it is now fixed in `master`.

I am not sure why `rx` and `ry` are getting set to 0 now instead of null, but this seemed like a safe fix.

Closing as should be fixed, but feel free to comment further.

**Comment by brettz9** [comment]
And in case you already checked `master`, I realized I was missing rectangle/square fixes as well, now applied....  (And just in case it comes up, using the fixed circle subtool did not show the problem but the ellipsis (which can create circles) did...)

**Comment by glutanimate** [comment]
Thank you for the lightning fast-response (and sorry on my part for taking a bit longer to respond)! I've just given the latest master branch a try and I can confirm that it's fixed on Firefox and performing as before v3.0.0 on Chrome. Really hoping that we can somehow fix this on Chrome as well. Is there anything I can do to help? I'm not that experienced with JavaScript, unfortunately (more of a Python guy).

**Comment by brettz9** [comment]
Sorry, I see I neglected to reply. The JSDocs (at http://svg-edit.github.io/svgedit/releases/latest/docs/jsdoc/index.html ) should help one be able to dig more into the code. Since JS borrows a lot from Python, it hopefully wouldn't be too much of a leap. Besides, it's worth learning, with JS being ever more ubiquitous!

**Comment by AgriyaDev5** [comment]
https://user-images.githubusercontent.com/44435283/125436678-73fb541c-1c67-48ab-b826-35d50687859f.mp4

`clicking on a recently drawn shape used to automatically switch the tool to selection mode`
