### ISSUE TITLE
Add to JSDoc

### ISSUE THREAD

**Issue by brettz9** [SVG-Edit/svgedit#263]
I'm preparing a major PR for adding to JSDoc (which includes jQuery plugins as long as non-minified source was included), but there are some items that are not part of this PR.

While there are a good number of private functions not documented, the following strike me as being desirable for higher priority:

- [x] Context menus (svg-editor.js)
- [x] Toolbar buttons  (svg-editor.js)
- [x] `getPrivateMethods` - (svgcanvas.js); listed as deprecated but exposed to extensions
- [ ] canvg is only partially doc'd, as I think we should first submit any improvements of ours to the latest canvg at https://github.com/canvg/canvg and then document and update (adding links to any standard APIs and denoting which methods are custom).

The old wiki pages could also be adopted, and there are some useful items in there, but I wouldn't personally consider it high priority.

**Comment by jfhenon** [comment]
This comment does not apply anymore.
