### ISSUE TITLE
Add markdown rendering in jsdoc

### ISSUE THREAD

**Issue by tetedacier** [SVG-Edit/svgedit#265]
As shown in [this generated doc](https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/docs/jsdoc/HistoryRecordingService.html) markdown is not rendered.

To enable that, we simply need to activate the builtin markdown plugin of jsdoc.

**Comment by brettz9** [comment]
This has been addressed in #264, among with many other documentation changes. We can keep this issue open until that may be pulled.

**Comment by brettz9** [comment]
And again, thanks for getting the ball rolling on JSDoc--something like it is absolutely needed for a project of this size. Even with JSDoc seeming to be of fairly low activity these days, beyond its usefulness, its incorporation into TypeScript seems to bode well for its future...
