### ISSUE TITLE
Path element cannot be exported to PDF

### ISSUE THREAD

**Issue by cuixiping** [SVG-Edit/svgedit#269]
Currently, only `line, rect, ellipse, circle, text` elements can be exported to pdf. 
see [`jspdf.plugin.svgToPdf.js`](https://github.com/SVG-Edit/svgedit/blob/master/editor/jspdf/jspdf.plugin.svgToPdf.js).

Any `<path>` element in the svg document cannot be exported to pdf.

The following svg document will be exported as an empty pdf. 
2 path elements are ignored.

```
<svg width="640" height="480" xmlns="http://www.w3.org/2000/svg">
  <path d="m100,229c191,97 173,-94 379,45" fill="#FF0000" stroke="#000000" stroke-width="5"/>
  <path d="m223,101a114,62 0 1 0 219,2" fill="#FF0000" stroke="#000000" stroke-width="5"/>
</svg>
```

![image](https://user-images.githubusercontent.com/1104492/44246772-9522d880-a212-11e8-9319-421fd047df66.png)

**Comment by brettz9** [comment]
As per #51 , we really should see about updating jsPDF (possibly requiring an update to the [fork I was using](https://github.com/ahwolf/jsPDF/pull/4) for the SVG plugin or resuming use of upstream)... PRs welcome!

**Comment by brettz9** [comment]
Btw, which browser were you testing in? In my case, when I test in Firefox (as Chrome is not working for me), I see nothing at all in the PDF... FWIW, exporting to PNG works fine...

**Comment by cuixiping** [comment]
I tested in Chrome and Firefox.

**Comment by cuixiping** [comment]
I fixed it partially. But have not send PR.

It can export normal curves to PDF.
It supports `MmLlQqCcZz` commands but not `HhVvAaTtSs` yet.
It doen't support holes in path. All holes will be treated as normal shape.
I have no ideas to handle with holes.

**Comment by cuixiping** [comment]
Update: Path with holes has been ok.
Here is a pdf screenshot:

![image](https://user-images.githubusercontent.com/1104492/72402452-4e7c3980-378a-11ea-91c6-b5750f4677e0.png)

**Comment by cuixiping** [comment]
I am solving the `HhVv` commands and find another bug:  `convertPath` function in `path.js` handle `hv` commands incorrectly.

**Comment by cuixiping** [comment]
I tried to write a cypress case for `convertPath` . It is a waste of life. :joy:  :sob: 
It's very difficult to make it work correctly for me.

**Comment by brettz9** [comment]
Awww.. Hopefully learned at least what not to do. :-) You tried a PDF parser or what?

**Comment by cuixiping** [comment]
> Awww.. Hopefully learned at least what not to do. :-) You tried a PDF parser or what?

Not PDF. I just tried to test the `convertPath` function.

**Comment by cuixiping** [comment]
My fix now supports all path commands except arc commands(A,a) to be exported to pdf.

**Comment by klesun-misc** [comment]
@cuixiping you rock!
