### ISSUE TITLE
Invalid X for text after resize

### ISSUE THREAD

**Issue by Stereotip42** [SVG-Edit/svgedit#270]
Good day! Wanted to find out why for text when make it **resize**, not correctly calculated X when moving it relative to the container?
http://prntscr.com/kg1seh - x=200..,  although by analogy with the rectangle (http://prntscr.com/kg1t4u) equel ~640. 
Thanks!

**Comment by brettz9** [comment]
Hello... The core developers are not really active at this time, but feel free to dig into the code and file a PR if you can isolate the issue along with your test case.

In any case, please indicate the version of SVG-Edit you are working off of...

**Comment by Stereotip42** [comment]
@brettz9 
This is the version from the link on the main page of the demo
https://svg-edit.github.io/svgedit/releases/latest/editor/svg-editor.html
