### ISSUE TITLE
Some imported symbols cutoff

### ISSUE THREAD

**Issue by adrianbj** [SVG-Edit/svgedit#281]
**Describe the bug**
When importing some symbols, the symbol is positioned partially off the canvas and is much larger than expected.

**To Reproduce**
1. IAN symbols - Fauna > Birds > Ammodramus nelsoni (Nelson's Sparrow)

**Expected behavior**
Should import the entire symbol at the size of other symbols

**SVG-Edit environment (IMPORTANT)**
- File for SVG-Edit: [e.g., `svg-editor.html`, `svg-editor-es.html`, `embedapi.html`]
- Version: 3.x (testing on github demo
- Protocol: https

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra
 - Browser: Chrome
 - Version: 69.0.3497.81

![image](https://user-images.githubusercontent.com/871211/45465013-1bbebe80-b6c8-11e8-9bcc-33b5f1d5b2dc.png)

![image](https://user-images.githubusercontent.com/871211/45465024-2aa57100-b6c8-11e8-98d2-c434155a6566.png)

If you break link to symbol, then it's fine:

![image](https://user-images.githubusercontent.com/871211/45465030-34c76f80-b6c8-11e8-8345-55749608eb24.png)

**Comment by AgriyaDev5** [comment]
> When importing some symbols, the symbol is positioned partially off the canvas and is much larger than expected.

IAN as they changed the API, so we removed IAN option in SVGEdit.

**Comment by adrianbj** [comment]
@AgriyaDev5 and @jfhenon - isn't it likely that this issue will affect other symbols from other sources and so should still be fixed?

Regarding the IAN library - I'd be happy to get that interface up and running again if you'd like. The website was rebuilt and this got lost in the shuffle, but should be pretty easy to get it back up again.
