### ISSUE TITLE
Bounding box moves when moving a symbol in Firefox and Safari

### ISSUE THREAD

**Issue by adrianbj** [SVG-Edit/svgedit#284]
**Describe the bug**
Bounding box moves when moving a symbol in Firefox and Safari. Note that it's fine in Chrome these days, but in 2.5 is was a bug in Chrome as well.

**To Reproduce**
1. Insert an IAN symbol
2. Click and drag to move it

**Expected behavior**
Bounding box should stay with the symbol

**Screenshots**
![image](https://user-images.githubusercontent.com/871211/45491546-ceba0700-b71e-11e8-94f8-af7c37ee55d3.png)

**Comment by sbrown345** [comment]
This worked on my old branch from Method Draw. The default case:

https://github.com/methodofaction/Method-Draw/blob/de8eb4c6954e3dd1b71e06cdcece41f13d80d891/editor/src/svgutils.js#L494

```
    if(elname === 'use') {
      ret = groupBBFix(selected, true);
    }
    
    if(elname === 'use') {
      if(!ret) ret = selected.getBBox();
      //if(!svgedit.browser.isWebkit()) {
      //  var bb = {};
      //  bb.width = ret.width;
      //  bb.height = ret.height;
      //  bb.x = ret.x + parseFloat(selected.getAttribute('x')||0);
      //  bb.y = ret.y + parseFloat(selected.getAttribute('y')||0);
      //  ret = bb;
      //}
    } else if(~visElems_arr.indexOf(elname)) {
      try { ret = selected.getBBox();} 
      catch(e) { 
        // Check if element is child of a foreignObject
        var fo = $(selected).closest("foreignObject");
        if(fo.length) {
          try {
            ret = fo[0].getBBox();
          } catch(e) {
            ret = null;
          }
        } else {
          ret = null;
        }
      }
```

**Comment by AgriyaDev5** [comment]
## Before
![Screenshot at 2021-06-08 18:52:58](https://user-images.githubusercontent.com/44435283/121193587-958d3200-c88b-11eb-9ac8-9f2a73d287a4.png)


## After 
![Screenshot at 2021-06-08 18:49:13](https://user-images.githubusercontent.com/44435283/121193612-9cb44000-c88b-11eb-98a0-b809a6143cbf.png)
