### ISSUE TITLE
Context menu doubling up of shortcuts

### ISSUE THREAD

**Issue by adrianbj** [SVG-Edit/svgedit#285]
Not sure when this was introduced, but it was fine when the feature was added back in 2 point something :)

![image](https://user-images.githubusercontent.com/871211/45492024-0c6b5f80-b720-11e8-9969-eb4860e33cf7.png)

**Comment by brettz9** [comment]
Thanks for this.... I've added https://github.com/brettz9/svgedit/commit/b51db3a3c17f528377f8b1dac01840d431d24cd9 which fixes the double shortcuts and also adds a few missing shortcuts (cut, copy, delete).

**Comment by brettz9** [comment]
Sorry, hadn't noticed this comment until now--hope the fix earlier did the trick!

**Comment by adrianbj** [comment]
No problem :)

Yes, the additions from yesterday are excellent - thanks!
