### ISSUE TITLE
Backspace key for deleting elements is unreliable

### ISSUE THREAD

**Issue by adrianbj** [SVG-Edit/svgedit#290]
**Describe the bug**
Sometimes the backspace (delete on mac) key doesn't trigger deleting of an element.

**To Reproduce**
1. Go to IAN libraries and insert a couple of symbols
2. Click on one of the symbols to select it
3. Hit backspace key
4. It doesn't delete
5. Click the delete button on the SVGEdit toolbar
6. Click on the other symbol and now the backspace key will work on it

**Expected behavior**
Backspace key should always delete element

**SVG-Edit environment (IMPORTANT)**
- File for SVG-Edit: `svg-editor.html`
- Version: 
https://rawgit.com/SVG-Edit/svgedit/master/editor/svg-editor.html and
https://svg-edit.github.io/svgedit/releases/svg-edit-2.8.1/svg-editor.html
- Protocol: https

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 70.0.3538.22

**Comment by brettz9** [comment]
On Firefox I don't see any issues (is that the same for you?), and I can't confirm Chrome with my  issues logging into your site from Chrome...

**Comment by jfhenon** [comment]
see #556
