### ISSUE TITLE
Keyboard navigation improvements?

### ISSUE THREAD

**Issue by inspector71** [SVG-Edit/svgedit#291]
This program is a huge achievement. Congratulations to all involved.

I wonder, though, if a few improvements could be made to keyboard navigation. For example:

1. [x] In source edit mode, map `Esc` to Cancel
1. [ ] In source edit mode, map `Tab` to first move the focus to OK, Cancel, then the rest of the browser chrome elements - assuming that is, that supporting smart tabs (press Tab, enter X spaces) cannot be supported, or may come with a syntax highlighter (that would also be brilliantly helpful :) )

**Comment by brettz9** [comment]
Incidentally, the fix for using escape for cancel also got it working again within the Document Properties and Settings dialogs as well...

**Comment by adrianbj** [comment]
On this note, I'd love to see CTRL/CMD + A work for select all. I know we have "a" on its own for this, but muscle memory means I always end up doing the former which ends up being ugly.

Regarding a code editor, I have always gone with ACE because it had functionality that Codemirror didn't, but perhaps that has changed in the last year or two. I don't imagine it matters too much which code editor is utilized as this would be a pretty simple use case and any option would handle things just fine.

**Comment by inspector71** [comment]
Hi Brett

I'd like to contribute. I write some JS for a (extremely meagre!) living so
maybe it would not be too hard.

No disrespect to those who have worked so hard to get things to their
current point but I feel the interface could use some touching up. Perhaps
that would be somewhere I could start.

Agree `tabindex` might be less than ideal in that AFAIK it tends to follow
source order but I've not done a lot of work with forms for a while so
probably need a redux.

**Comment by inspector71** [comment]
Sweet! Always great to get a bonus or two.

**Comment by inspector71** [comment]
On Mon, 1 Oct 2018, 8:12 PM Adrian Jones <notifications@github.com> wrote:

> On this note, I'd love to see CTRL/CMD + A work for select all.
>
Extremely odd that you mention this ... it was next on my list!

One of the annoyances I find with so-called web apps relative to self
contained apps is they're often messy when users accidently drag over a
section of the GUI with the mouse button down. It takes awareness of the
ability to click in a certain zone to remove the selection over the GUI
buttons and toolbars.

I found that Ctrl + A selected all the GUI elements instead of the
`textarea` 😀

Whoops, haha.

> I know we have "a" on its own for this, but muscle memory means I always
> end up doing the former which ends up being ugly.
>
I still can't stop Alt Tabbing when occasionally using a web app then
intending to flip to a program (or site) ... that's in another tab in the
same browser window! Muscle memory is hard to retrain 😀

Regarding a code editor, I have always gone with ACE because it had
> functionality that Codemirror didn't, but perhaps that has changed in the
> last year or two. I don't imagine it matters too much which code editor is
> utilized as this would be a pretty simple use case and any option would
> handle things just fine.
>
Yeah as long as it's not terrible and breaks too much existing
functionality ... or is too bloated so the code view mode loads too slowly
... anything that highlights syntax would be an improvement. Worth some
experimenting I'm sure.

**Comment by brettz9** [comment]
Regarding Cmd/ctrl + a for select all (i.e., Command on Mac and Ctrl on Windows), I've just pushed this ability to `master`.

I've also added support for a global "Escape" key listener to clear the canvas selection (unless one is within a dialog, in which case it should only cancel the dialog).

And I also just added a fix to `master` in that my prior commit referenced above had only undone the limitation that one could not use the escape key to cancel dialogs when the focus was within a textarea; now the limitation has been removed which prevented it from working within input textboxes as well.

**Comment by brettz9** [comment]
As far as a code editor, Ace Editor does look pretty good now--I seem to recall CodeMirror being unique in being able to handle a large amount of text well, but I see Ace does the job well. But CM seemed to have a lot of plugins, etc. I'm not as familiar with what Ace offers over CM. Anyways, can cross that bridge if we get to it...

@inspector71 : Most welcome to take a stab at improvements and send your PRs in...

Re: inadvertently selecting all of the controls, yes, that can be a concern, but I'm also not a fan of when apps take away control of the context menu entirely, and one cannot use the built-in browser features to introspect, use add-ons, etc. And it's not only for developers of the app--it also relates to things like being able to copy a link's location or text, etc.

It would be helpful for starters, @inspector71, if you familiarized yourself a little with our development environment. Our source is in ES6, so for initial work, it is probably easiest to modify `svg-editor-es.html` as it doesn't require a build step (which creates the regular `svg-editor.html` and its JavaScript files).

As far as testing, I've just added a UI testing framework (testcafe) which seems quite cool. I'm also using a plugin for it to handle accessibility UI tests (which are currently failing), but these tests may also be helpful in identifying any issues with using tabindex or whatever other alternative (I would guess that tabindex may be helpful to use if it doesn't hurt anything as it is a standard recognized property that presumably assistive devices might utilize, but I really am not too familiar with that).

Let me know if you need help around the code or what not... Hopefully the new jsdocs should assist: https://svg-edit.github.io/svgedit/releases/latest/docs/jsdoc/index.html ... I'm really hopeful that whoever makes improvements can also touch up the docs along the way, as there is still a lot more that could be done, and I think it is important for such a large code base...

**Comment by inspector71** [comment]
Nice work Brett!

**Comment by inspector71** [comment]
> @inspector71 : Most welcome to take a stab at improvements and send your PRs in...

Thanks for the welcome.

I've had a very brief go at updating or modernising the toolbars a little and hit a snag or two already. I suspect you may be able to help though. Generally speaking I don't develop on my local machine. Do you guys run a web server on your local machine and develop that way? I'm getting permission limits when just quickly tinkering from my local hard drive after cloning and loading via the file:/// protocol.
 
> Re: inadvertently selecting all of the controls, yes, that can be a concern, but I'm also not a fan of when apps take away control of the context menu entirely, and one cannot use the built-in browser features to introspect, use add-ons, etc. And it's not only for developers of the app--it also relates to things like being able to copy a link's location or text, etc.

I've not looked into this before. If we can't disable selecting without disabling native right-click and so forth, I can see your point. The web has grown so much due to the open nature of it and that should be supported wherever possible. Long run, perhaps a toggle in an options dialog might be the best compromise but there's a visual refresh that I think could be a big boost before this sort of thing.

> It would be helpful for starters, @inspector71, if you familiarized yourself a little with our development environment. Our source is in ES6, so for initial work, it is probably easiest to modify `svg-editor-es.html` as it doesn't require a build step (which creates the regular `svg-editor.html` and its JavaScript files).
 
Just looked at the HTML primarily so far. Seems there's a few inconsistencies which is a little tricky. For example, the `#editor_panel` contains two buttons that are initially HTML divs but the show grid button is presumably created in JS on the fly. Not a showstopper but I guess it would be cleaner and easier to develop if things were in one spot. Perhaps there's a strong reason why this is all JS though?

I should confess ..., 

Firstly, I'm brand new to compiled JS. I've read news about Mozilla's asm.js and WebAssembly seems to have shot ahead at a rate of knots relative to previous standards development schedules (years not decades!). But whilst I am again familiar with terms like LLVM and such, that's all from casual reading. So I'd need a hand to compile. 

Secondly, I've used git a lot in a terminal environment with relatively pre-defined dev and central origin, then deploy workflows. I've hung around and edited Github wiki content via the browser and I'm definitely no stranger to GitHub issues and so forth. But I'm yet to issue my first PR! It's been something of a wish list for ages but I think I could use a helping hand to get started. If the SVG-Edit project can help me there, that'd be brilliant.

Thirdly ... hmm, I think I've forgotten. Swear there was a thirdly and more. LOL Oh well, one step at a time!

> As far as testing, I've just added a UI testing framework (testcafe) which seems quite cool. I'm also using a plugin for it to handle accessibility UI tests (which are currently failing), but these tests may also be helpful in identifying any issues with using tabindex or whatever other alternative (I would guess that tabindex may be helpful to use if it doesn't hurt anything as it is a standard recognized property that presumably assistive devices might utilize, but I really am not too familiar with that).

Oh yeah, thirdly ... my workplace doesn't generally have the resources to instrument scripted testing! That sucks for stress levels as when we deploy we could be breaking something inadvertantly. Somehow though, we scrape by. I am nonetheless very interested in test scripting but am also a newb at it :(

> Let me know if you need help around the code or what not... 

Absolutely! I find it always takes a bit of time and some questions to get a feel for a project. Thanks for offering! Generally speaking I work best in a tag team or power trio :)

Hopefully the new jsdocs should assist: https://svg-edit.github.io/svgedit/releases/latest/docs/jsdoc/index.html ... 

Phew, intimidating length and complexity! Great that such doco already exists though. Nothing like having references to speed up development instead of having to hunt down what needs to be passed where and which data types, etc.

> I'm really hopeful that whoever makes improvements can also touch up the docs along the way, as there is still a lot more that could be done, and I think it is important for such a large code base...

Agreed. Documentation is all important. I tend to be as concise and yet descriptive as I can be through comments. I tend to get an instinct for when I might have hooked something together to work, but possibly it might appear to weird to others. Of course, writing better structured code in the first place tends to reduce the need for documentating such oddities. All depends on the problem and circumstances we're trying to resolve though!

**Comment by inspector71** [comment]
Hi
Lost a lot of the little confidence I had in my skills. Best I close this and stop wasting everyone's time.
All the best.

**Comment by brettz9** [comment]
Everything of any scope can start out intimidating... May just take some time, and we're here if you have questions... Best wishes...

**Comment by inspector71** [comment]
Thanks Brett, I really appreciate those kind words. I'm having a really
hard time lately and it made me very sad to realise I'm struggling to
contribute to a project like this.

Thank you most humbly.

**Comment by brettz9** [comment]
I've filed #296 to track the syntax highlighting enhancement request, so feel free to subscribe there if you wish...
