### ISSUE TITLE
Sidebar doesn't unfold when zoomed in

### ISSUE THREAD

**Issue by sanderd17** [SVG-Edit/svgedit#298]
When zoomed in, clicking on the "Layers" button doesn't open the sidebar.

**To Reproduce**
* Open the editor
* Zoom in using CTRL++ to 110% or more
* Click on the "LAYERS" button
* The sidebar doesn't unfold

**Expected behavior**
The sidebar should open and show the layer settings.

**SVG-Edit environment**
- File for SVG-Edit: `svg-editor-es.html`
- Versions tested: 3.0.0 and master
- Protocols: http and file

**Desktop:**
 - OS: Linux
 - Browser Firefox
 - Version 62

**Additional context**

Reason is that the pixes are zoomed in,  `$('#sidepanels').width()` returns 2.25, while the check is done on 2.

See svg-editor.js line 4977
```js
const toggleSidePanel = function (close) {
   const w = $('#sidepanels').width();
   const deltaX = (w > 2 || close ? 2 : SIDEPANEL_OPENWIDTH) - w;
   changeSidePanelWidth(deltaX);
};
```

I don't know enough about the code structure on where to keep the state (whether the bar is considered open or not). Apparently deducing it from the HTML style doesn't always work.

**Comment by brettz9** [comment]
Thank you for the report. There is a reason we have the bug report templae, however, as it helps us to confirm, debug, etc., knowing what version you are using, etc. If you need help finding the information, let us know.

**Comment by brettz9** [comment]
Thanks!

I get decent-seeming behavior (including for zoom less than 100%) when changing to this to take into account the zoom through `window.devicePixelRatio`:

```js
const toggleSidePanel = function (close) {
    const dpr = window.devicePixelRatio || 1;
    const w = $('#sidepanels').width();
    const isOpened = (dpr < 1 ? w : w / dpr) > 2;
    const zoomAdjustedSidepanelWidth = (dpr < 1 ? 1 : dpr) * SIDEPANEL_OPENWIDTH;
    const deltaX = (isOpened || close ? 0 : zoomAdjustedSidepanelWidth) - w;
    changeSidePanelWidth(deltaX);
  };
```

I changed the 2nd "2" to "0" as I don't see why we should be changing the value at all if we determined it is already open/closed, and it seems fine.

Let me know if these changes work for you...
