### ISSUE TITLE
 Some facility to look inside a svg image that is displayed. And be able to highlight or focus on where you find matching?

### ISSUE THREAD

**Issue by martinmurciego** [SVG-Edit/svgedit#299]
I am interested in displaying a svg image on a page that displays a database diagram exported from the dBeaver tool in svg format. If I want to locate elements looking similar to when looking at a web page there is some way to achieve a search functionality that helps me and focus on that area of ​​the image (title of table, field, etc.).

Maybe how to search and select an element of the svg image? It would be a more technically specific question.

**Comment by martinmurciego** [comment]
Thanks for answering. I was just looking for how to present a database diagram in svg format on a page of my application for a formal presentation. And locating a table or field by a searched string would be very useful in a diagram of about 50 tables.

**Comment by brettz9** [comment]
Ok, sure, but if my answer wasn't clear, you can already effectively do this using the browser features I described--just not within SVG-Edit...
