### ISSUE TITLE
Include filters ?

### ISSUE THREAD

**Issue by ibrierley** [SVG-Edit/svgedit#3]
Is there a way to include filters (other than shadow and editing the svg), if not, should we add one ?

**Comment by codedread** [comment]
If I remember correct, gaussian blur is there... (Is that what you meant by shadow?)

**Comment by ibrierley** [comment]
Tbh it was a while ago and can't quite remember now! :).  I think at the time I was thinking svg-edit could be interesting if more of the filters were available, especially if you could combine some and then be able to play with the various settings, or even paste the filter markup somewhere for you to reuse. Eg some of the filters like at https://docs.webplatform.org/wiki/svg/tutorials/smarter_svg_filters

I haven't seen much out there which lets you combine and create your own filters, like dragging outputs of one filter into another, but thats likely beyond the scope of svg-edit I guess.

**Comment by codedread** [comment]
Browsers support many more filters now, so it would be cool, no doubt!  :)

**Comment by brettz9** [comment]
FWIW, `feMorphology` has now been whitelisted per #318 , so one can at least have this filtering tag preserved if in source (though no graphical way to edit).
