### ISSUE TITLE
Free-hand shape mousedown method started in last mouseUp position

### ISSUE THREAD

**Issue by initialdmg** [SVG-Edit/svgedit#300]
**Describe the bug**
Free-hand shape mousedown method started in last mouseUp position

**To Reproduce**
2. Click on 'Free-hand rectangle'

**Expected behavior**
The New shape begin with the mousedown position

**SVG-Edit environment (IMPORTANT)**
- File for SVG-Edit: [`svg-editor-es.html`]
- Version: [3.2.0]
- Protocol: [https]

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome]
 - Version [70]

**Screenshots**

![ezgif-2-958f4018ef5b](https://user-images.githubusercontent.com/22365060/48403849-d0796880-e769-11e8-9fed-8a5275d0d7b8.gif)

**Comment by cuixiping** [comment]
Has been fixed. https://github.com/SVG-Edit/svgedit/commit/471035c0da2471ce52e3debed694bbb9962a4d90
