### ISSUE TITLE
Minimal SVG Canvas

### ISSUE THREAD

**Issue by sanderd17** [SVG-Edit/svgedit#301]
I'd like to use this project to develop custom saving, loading, bindings, handlers, ...

But for that, I'd best start from a minimal SVG Canvas. Starting from the svg-editor makes no sense, as it will be outdated soon (including all JS parts).

In #235 I found a reference to https://neil.fraser.name/news/2018/SvgCanvas.html , where a minimal instance is made from different libraries.

However, in the current state, different files don't exist anymore, and others are converted to ES modules, so won't load in old-fashioned script tags.

Are there plans to support a minimal canvas with a more or less stable interface to build on?

**Comment by brettz9** [comment]
I've added some prebuilt svgcanvas.js distributions...

You could modify `/demos/canvas.html` to remove `type="module"` and the import in favor of adding this before that script:

```html
    <script src="../node_modules/@babel/polyfill/dist/polyfill.js"></script>
    <script src="../dist/svgcanvas-iife.js"></script>
```
