### ISSUE TITLE
moving imported .svg after rotation is broken

### ISSUE THREAD

**Issue by 3akdaniel** [SVG-Edit/svgedit#302]
**Describe the bug**
I'm importing a .svg image from the libraries and rotate it. Then I try to move it with keyboard arrows.
After moving some steps the icon starts jumping all over the canvas...

**To Reproduce**
1. Go to Demo: 'https://svg-edit.github.io/svgedit/releases/latest/editor/svg-editor.html'
2. Click on 'svg-edit' -> 'Image Library' - > 'Demo library (local)' -> 'smiley.svg '
3. Click on the imported icon and rotate it 90 deg.
4. Click on the Select tool (v) and click the icon again,
5. press the 'right arrow' on the keyboard.
6. after some steps you will see the icon jumping on the canvas...

**Expected behavior**
The icon should move properly without "jumps"

**SVG-Edit environment (IMPORTANT)**
- Version: use the one in the demo

**Desktop (please complete the following information):**
 - Browser: Chrome, Windows.

**Comment by AgriyaDev5** [comment]
@3akdaniel  unable to reproduce now.


https://user-images.githubusercontent.com/44435283/125456283-8686f7df-1af9-4b2a-b22f-98a487501a9e.mp4
