### ISSUE TITLE
zh-CN,zh-HK,zh-TW bug

### ISSUE THREAD

**Issue by enlove** [SVG-Edit/svgedit#304]
**Describe the bug**

**To Reproduce**
local open 'svg-editor.html' , refresh with link "&lang=zh-CN" or open it in chinese language environment.

**Expected behavior**
display chinese language menu.

**SVG-Edit environment (IMPORTANT)**
- File for SVG-Edit: [e.g., `svg-editor.html`, `svg-editor-es.html`, `embedapi.html`]
- Version: 4.0.1

**Desktop (please complete the following information):**
 - OS: windows7 x64
 - Browser: chrome,firefox

**Additional context**
cannot work

**Comment by brettz9** [comment]
I'm not seeing this issue when adding `?lang=zh-CN` (I see one issue with the image libs extension though). Do you see errors in console?

**Comment by brettz9** [comment]
I've just now published 4.1.0 which fixes an issue I did discover with extensions not properly loading for locales with hyphens (like `zh-CN`). You might see if that fixes your issue: https://svg-edit.github.io/svgedit/releases/svg-edit-4.1.0/editor/svg-editor.html?lang=zh-CN

**Comment by enlove** [comment]
thank you very much for your bug fixing ！ I have translate english to chinese，bug i don't know how to merge to your code. i have upload lang file to https://github.com/enlove/svgedit/tree/master/dist/extensions/ext-locale

**Comment by enlove** [comment]
sorry ,i updated  wrong zh-CN lang files ,i will update them tomorrow.

**Comment by enlove** [comment]
path:   ...dist\extensions\ext-locale
zh-CN files:
https://pan.baidu.com/s/1I0KIr2FdEVxJblQRzFnTUw

**Comment by brettz9** [comment]
Do you have a WeChat id or email? I think that'd be easier, as I don't read Chinese well enough to follow the instructions on downloading there...

**Comment by brettz9** [comment]
Thanks--this is now added in `master`... FYI, I pushed out that last release quickly because of a fatal bug (for such locale users), but for lesser fixes or locale changes, the priority for a release is not as urgent... I'm closing this issue now as the bug and locale changes should now be addressed, though feel free to comment further...
