### ISSUE TITLE
Grid improperly works

### ISSUE THREAD

**Issue by NeiroNx** [SVG-Edit/svgedit#308]
**Describe the bug**
A Grid pattern do not working propertly when used markes on polyline. Pattern created on `svgroot` element, but needs only in `canvasGrid` element.

**To Reproduce**
1. Enable Grid
2. Create line
3. Set line markers
4. Update page
5. Grid is newer sows with that svg
6. See `pattern` in svg code of your image.

**Expected behavior**
Expected propertly working of grid.

**SVG-Edit environment (IMPORTANT)**
- File for SVG-Edit: `svg-editor-es.html`
- Version: last
- Protocol: any

**Desktop (please complete the following information):**
 - OS: any
 - Browser any
 - Version any

**Solution**
https://github.com/SVG-Edit/svgedit/pull/307

**Comment by brettz9** [comment]
Fixed by #307 . Thanks!
