### ISSUE TITLE
Bounding box for foreignObject in Safari

### ISSUE THREAD

**Issue by distler** [SVG-Edit/svgedit#310]
The bounding box for a `<foreignObject>` (created either using the `foreignobject` extension or using my `itex` extension) is displaced relative to the object itself. This happens only in Safari, and the fix is a [simple one-liner](https://github.com/parasew/instiki/commit/969d33ac7cc411bab9f15614bb0ed8a44dffd2ff):

~~~~~~
--- a/svgedit-config-iife.js
+++ b/svgedit-config-iife.js
@@ -8526,7 +8526,7 @@
           // ——————————


-          if (!isWebkit()) {
+          if ('width' in ret) {
             var bb = {};
             bb.width = ret.width;
             bb.height = ret.height;
~~~~~~~

I would create a pull request but (because of all of the refactoring that has taken place since I last immersed myself in  the code) I'm not sure this is the correct place to apply the patch.

I encountered this in updating my `itex` extension for the latest version of SVG-Edit, but the bug is a long-standing one (ever since Webkit fixed their behaviour).

**Comment by brettz9** [comment]
As far as refactoring, `svgedit-config-iife.js` is just the bundled and Babelified version of `svgedit-config-es.js`, where the latter file, before setting config, starts the chain of SVG-Edit imports by importing `editor/svg-editor.js`--a file which does its own ES imports which can be traced.

PRs can modify the source files, and then (after running `npm install` with Node/npm installed) run `npm run browser-test` to complete the build steps and also ensure the browser tests are working. It'd be great if you could submit a PR for this against the latest in `master` (just updated)...

Please let me know if you need any assistance with this... Thanks!

**Comment by jfhenon** [comment]
This is not relevant anymore with V7.
Thanks
JF
