### ISSUE TITLE
isIE is a function but used as boolean in svgcanvas.js leads a performance problem

### ISSUE THREAD

**Issue by ianli-sc** [SVG-Edit/svgedit#312]
**Describe the bug**
in this line https://github.com/SVG-Edit/svgedit/blob/master/editor/svgcanvas.js#L1229 
use `!isIE` to test if browser support function `getIntersectionList`, call isIE as a boolean without a function leads always true in browser

**To Reproduce**

every browser

**Expected behavior**

call `!isIE()` not `!isIE`

**SVG-Edit environment (IMPORTANT)**

- File for SVG-Edit: all
- Version:  4.2.0
- Protocol: all

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser Chrome
 - Version 71.0.3578.98

**Screenshots**
![image](https://user-images.githubusercontent.com/1450556/50442546-54fb0180-093a-11e9-90ec-5cf3efa6243c.png)

**Comment by brettz9** [comment]
I went ahead and applied the fix, thanks!

For future reference, please see https://github.com/SVG-Edit/svgedit/issues/310#issuecomment-450054248 on the steps you can follow to modify the source, build the files, and test, before submitting a PR...
