### ISSUE TITLE
Transparent rectangles due to short hex color code rendering from bug in URL param parsing

### ISSUE THREAD

**Issue by adelq** [SVG-Edit/svgedit#314]
**Describe the bug**

The svg-edit library parses URL querystring data improperly, leading to corruption of color data. svg-edit parses the URL parameters using jQuery BBQ and attempts to [coerce](http://benalman.com/code/projects/jquery-bbq/examples/deparam/) everything to native JS types, so a hex color like `"009900"` gets converted to `9900` though colors with letters in the hex representation (ex: `"FFEBA2"`) would stay as strings. This coerced integer `9900` gets saved into `svgEditor.curConfig.initFill.color` and passed all the way down to the fill color of the shape when drawn as `fill="#9900"`.

**To Reproduce**
1. Go to https://svg-edit.github.io/svgedit/releases/latest/editor/svg-editor.html?storagePrompt=false&initFill[color]=009900
2. Click on the rectangle tool
3. Draw a rectangle on the screen
4. Note that rectangle is unfilled, rather than the green specified in the URL param (`#009900`)

**Expected behavior**
Rectangle should be filled with the green specified in the URL param (`#009900`)

**SVG-Edit environment (IMPORTANT)**
- File for SVG-Edit: `svg-editor.html`
- Version: 2.6+
- Protocol: all

**Desktop (please complete the following information):**
 - OS: any
 - Browser/Version: Chrome 71, Firefox 64

**Sandbox**

You can test this through the web demo:

https://svg-edit.github.io/svgedit/releases/latest/editor/svg-editor.html?storagePrompt=false&initFill[color]=009900

The URL parameter `initFill[color]` should set the fill color of rectangles to green (`#009900`) but instead draws clear rectangles. The fill colorpicker draws an unfilled box.

**Additional context**

This bug was originally discovered in the Anki addon Image Occlusion Enhanced, which uses a fork of svg-edit 2.6. However, this bug is still present in the latest versions of svg-edit.

https://github.com/glutanimate/image-occlusion-enhanced/issues/90

Modern browsers such as Chrome/Firefox happily take values such as `#1`, but fail on other inputs such as `009900`, which would render green (`#009900`), but gets converted to `9900` which does not properly fill.

I have written a patch, but merely works around the problem by converting the fill color back to a string and pads it with `0`s. There are lots of other color parameters that can be set through URL parameters though, so this is not a comprehensive fix.

**Comment by brettz9** [comment]
In the process of hopefully getting this handled, it'd be nice to switch to `URLSearchParams`, e.g., `new URL(document.location).searchParams` parsing, so we could get rid of `$.deparam` in svgeditor.js, which I think is our last dependency on jquery BBQ, so we could then remove that, helping fix part of #51.
