### ISSUE TITLE
cant drag and drop a dynamically added svg object having a viewbox

### ISSUE THREAD

**Issue by shahalam-geek** [SVG-Edit/svgedit#315]
[https://github.com/shahalam-geek/Floor-Plan](url)
**my project demo is at github "shahalam-geek/Floor-Planl" file name btext.html**
**please check my code and help me**
![imp](https://user-images.githubusercontent.com/46439269/50830359-95f90a00-136d-11e9-89d3-cd6d613702cc.png)

![newbt](https://user-images.githubusercontent.com/46439269/50829356-449b4b80-136a-11e9-93b5-5c2e71967588.png)

**it does not work when i drag and  drop**

**in my real project i am using svg edit tool where id="svgcontent" is present inside the svg canvas. it works fine on button click text got added on the target but when i drag and drop it does not work it alyas stay at its initial position.**
![text](https://user-images.githubusercontent.com/46439269/50828773-52e86800-1368-11e9-988e-12a4f717c0e2.png)

**Comment by brettz9** [comment]
This is not a question for the software SVG-Edit, but is instead just an SVG question (as I can see by demoing your code at https://raw.githack.com/shahalam-geek/Floor-Plan/master/btext.html ). Please add your question to StackOverflow or such a site. Thank you.
