### ISSUE TITLE
"Open SVG" issues

### ISSUE THREAD

**Issue by Nefiji** [SVG-Edit/svgedit#317]
If I click on "Open SVG" in the SVG-Edit drop-down menu, and then select a .svg file from my computer, SVG-Edit doesn't correctly open the file on its own. Only after I click on "Open SVG" again, it proceeds to open the .svg file from my first attempt. (Without having to select a file again) But even then, it pops up the "Loading image, please wait..." message indefinitely. Although when clicking on "Cancel", it clearly shows that the SVG already has been loaded completely and without an issue.

I don't know why this is happening, but it's happening on both of my browsers (Chrome & Firefox) - without any plugins interfering. Tell me if you need any further information.

**Comment by brettz9** [comment]
IIRC, this may be an issue with not allowing pop-ups for the domain you are using... Can you try that and see if that helps?

**Comment by brettz9** [comment]
Closing as no reply. Feel free to reopen if you have more info.
