### ISSUE TITLE
<filter> directive should not be removed from the SVG

### ISSUE THREAD

**Issue by jfhenon** [SVG-Edit/svgedit#318]
**Describe the bug**
The current implementation of SVG-Edit only supports <filters> for the Blur effect. I see this as a bug that other effects are deleted from the SVG. Ideally, it should support all effects but, if not supported, they should not be removed from the SVG. 

**To Reproduce**
1. Start a new image
2. Click on 'svg' button to see the svg elements:
```svg
<svg width="230" height="120" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
 <!-- Created with SVG-edit - https://github.com/SVG-Edit/svgedit-->
 <g class="layer">
  <title>Layer 1</title>
 </g>
</svg>
```
3. Add a filter in this SVG: 
```svg
<svg width="230" height="120" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
 <!-- Created with SVG-edit - https://github.com/SVG-Edit/svgedit-->
<filter id="deep">
    <feMorphology operator="dilate" radius="10"/>
  </filter>
 <g class="layer">
  <title>Layer 1</title>
 </g>
</svg>
```
4. See error:
If you click 'OK' and reopen the SVG content, the filters will be removed: 
```svg
<svg width="230" height="120" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
 <!-- Created with SVG-edit - https://github.com/SVG-Edit/svgedit-->
 <filter id="deep"/>
 <g class="layer">
  <title>Layer 1</title>
 </g>
</svg>
```

**Expected behavior**
The SVG should be kept intact with the filters.

**SVG-Edit environment (IMPORTANT)**
- File for SVG-Edit: `svg-editor.html`
- Version: latest]: online demo
- Protocol: [e.g., http, https, file] https

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOs
 - Browser Chrome
 - Version [e.g. 22]:  

**Smartphone (please complete the following information):**
 - Version [e.g. 22] Version 71.0.3578.98 (Build officiel) (64 bits)

**Screenshots**

**Additional context**

**Comment by brettz9** [comment]
I've whitelisted `feMorphology` (with attributes 'class', 'in', 'operator', 'radius') per c2a9798bfe17db52c58883030a50524e76ca0e94

Thanks for the report!
