### ISSUE TITLE
Dimensions passed on URL don't work

### ISSUE THREAD

**Issue by sjernigan** [SVG-Edit/svgedit#320]
The doc mentions that you can pass image dimensions on the URL like so
`.../svg-editor.html?dimensions=300,240&canvas_expansion=5&initFill[color]=0000FF`

However, when I try to do that with master or several hosted versions, I get a
`TypeError: arr[Symbol.iterator] is not a function`
error in the console.  I could not find a workaround format.  

I believe I understand the current status of this project so many thanks for any responses.

**Comment by sjernigan** [comment]
Adding the below just above the call to config_.dimensions solves the issue for me but I may not understand the issue.  I can submit a PR if desired.
`
    if (config_.dimensions[Symbol.iterator] != 'function') {
      config_.dimensions = [config_.dimensions[0],config_.dimensions[1]]
    }
`

**Comment by brettz9** [comment]
Ok, there was one issue I've fixed just now in d7b9cc630950e50e1f81608fe9e98bd5d4aa45bb that array configs were not being preserved internally as arrays. You'll have to see though what other issues might still be present though as far as dimensions--e.g., updating the Document Properties dialog, etc.

**Comment by sjernigan** [comment]
The changes seem to work.  I have not noticed other issues though I only use dimensions, url, lang, and storagePrompt.  Thank you.

**Comment by brettz9** [comment]
Are the dimensions to be reflected in the Document Properties dialog?

**Comment by sjernigan** [comment]
Yes, they are correct in the Document Properties
