### ISSUE TITLE
URL for image passed via URL params doesn't work

### ISSUE THREAD

**Issue by sjernigan** [SVG-Edit/svgedit#323]
Add a ?URL="some_svg_file.svg" to the src path for an iframe and the image will not load.

The first error you will see is that the locale string translation hasn't been loaded.  If you try to default, the string, you will get an error that the $.process_cancel function doesn't exist.  Commenting out the beforeSend callback definition works around this issue albeit without a loading prompt.
From svg-editor.js:6398
```js
editor.loadFromURL = function (url, {cache, noAlert} = {}) {
  return editor.ready(function () {
    return new Promise((resolve, reject) => { // eslint-disable-line promise/avoid-new
      $.ajax({
        url,
        dataType: 'text',
        cache: Boolean(cache),
        // beforeSend () {
        //   $.process_cancel(uiStrings.notification.loadingImage);
        // },
...
```

Not sure if pull requests are being reviewed/accepted for this project anymore.

**Comment by brettz9** [comment]
For well-documented PRs which explain why any changes to existing behavior are needed, I am trying to review as I have energy.
