### ISSUE TITLE
How to use ext-server_opensave.js?

### ISSUE THREAD

**Issue by deenfoxx** [SVG-Edit/svgedit#338]
I cannot figure out how to get "ext-server_opensave.js" to actually use the "filesave.php" to push the SVG to the server. Once I get this figured out, I'm sure I'll be able to get the "fileopen.php" to work as well (which currently does not do anything either).

1. Go to 'https://www.bestticketprinting.com/svgedit/editor/svg-editor.html?extensions=ext-server_opensave.js' (I verified the extension does load, no errors.)
2. Click on 'SVG Edit -> Save Image'
3. It simply saves to the client, does not do anything with "filesave.php".
4. Likewise, 'SVG Edit -> Open SVG', does nothing with "fileopen.php". gives choices from client.

I am expecting an SVG image can be selected and loaded from our server, not the client computer, and changes saved back to our server under a folder/filename that we determine based on their login to Best Ticket Printing.

- Version: master, 4.3
- OS: Windows
- Browser: Chrome, Firefox

The only documentation regarding this, that I can find, is here... https://github.com/SVG-Edit/svgedit/blob/v4.3.0/docs/tutorials/FrequentlyAskedQuestions.md ...second question/answer on the FAQ. Any further help would be appreciated. Thank you.

**Comment by brettz9** [comment]
Thank you for the report. I hope to be able to take a look maybe tomorrow.

**Comment by brettz9** [comment]
Can you try commenting out this line?

```js
if (window.FileReader) { return; }
```

It looks like the extension is making the assumption that you won't need server support if you can get it locally. If you can confirm, I can add some config which disables this behavior.

I'll try to take a closer look later.

**Comment by brettz9** [comment]
Oh, and there are also three instances of the following form which should be commented out:

```js
if (clientDownloadSupport(...)) {
  return;
}
```

**Comment by deenfoxx** [comment]
Commented out the lines you suggested without success. Added some alert()'s... no result. Took a closer look at Network load and found out it is not actually touching the "/svgedit/editor/extensions/ext-server_opensave.js", it is pulling in the "/svgedit/dist/extensions/ext-server_opensave.js".

I commented out the lines in the "dist" version and it did attempt to post to the "filesave.php" now, but not reaching out the the "fileopen.php".

Am I on the right track? Or should I not be editing the "/svgedit/dist/extensions/ext-server_opensave.js"?

**Comment by brettz9** [comment]
Sorry, am preoccupied at the moment to dig deeper, but yes, if you want to work on the ES Modules (ESM) source, you can work on the `/editor/extensions` files directly.

This may be easier for debugging as you can work with the distinct source files, but you need to test on a modern browser (or otherwise ES modules won't load) and go to `/editor/svg-editor-es.html` instead of `/editor/svg-editor.html`. But to get the chances from these source files moved into the `dist` files, you need to go to the project root while in console, and run the command `npm start` in one console tab and then open a new tab to run `npm run test-prep` in another.

But you can also just work on the `dist` files directly.

But I am currently preoccupied to look into this further at the moment.

**Comment by deenfoxx** [comment]
Okay, thank you for your time. I've never worked with ES6 before, so this is new to me. I appreciate your response.

**Comment by brettz9** [comment]
I'll first address the issue of the bugs you uncovered (now fixed), and then tell you which file I think you really might want to use instead.

The `ext-server_opensave.js` extension is really just intended as a go-between for helping users without modern browser file reading and saving features. I added some config to help you leverage it as you are seeking, but you really may just want to take a look at `ext-php_savefile.js` which converts the save button to send the contents (and file title) to the server.

Ok, I had time to debug a little, and I've pushed a couple fixes to master, as well as added a feature, all of which were needed here.

1. The means of accessing the `extPath` property was mistaken. Now fixed.
2. The PHP files needed to be present in `dist/extensions` as well. These are now part of the copy routine.
3. To avoid the need to comment out the client side detection and force the file to always interact with the server, you can set `avoidClientSide: true` in your config. For `svg-editor.html`, that is the file `svgedit-config-iife.js` at project root, and for `svg-editor-es.html`, that is the file `svgedit-config-es.js` at project root. If you don't want users to be able to override this option, set it one of the `setConfig` blocks without `allowInitialUserOverride: true` (e.g., the 2nd to last `setConfig` call on either page--an empty one).

It appears to be working in a PHP environment on my machine. By the way, let me know if you need config to disable the `if (window.FileReader) { return; }` line. That bypasses the need for using the server as a go-between for *opening* a *local* file. I could add a `avoidClientSide` check here too (or different config if desired), but I figure the real copy you want sent to the server is when the user is finished editing and decides to save. But correct me if I'm wrong.

But in case you only just need want the extension `ext-php_savefile.js`, that expects a file `savefile_config.php` in the same directory (you need to create the file; the entrance file that requires it is `savefile.php`). If you add a config file but do nothing in it, the PHP script will continue and save whatever was submitted to it to disk (deriving a filename from the user's title). You should do whatever validation you want, or redo `savefile.php` per your own needs to avoid users being able to fill up your hard drive with contents.

Let me know if this addresses your needs or if you need further config added.

**Comment by brettz9** [comment]
Closing as this should now be addressed.

**Comment by deenfoxx** [comment]
Thank you for the reply and fixes. I was on vacation for a couple weeks, sorry I did not get back quickly.

Re:  if you need config to disable the if (window.FileReader) { return; } line. 
I will comment out that line. Thank you. Yes, what I am attempting will require both load and save directly from/to the server. Client will be selecting from multiple pre-made templates and then saving their changes. This is a replacement to an existing Flash editor that is becoming more and more obsolete. (see bestticketprinting.com/search if interested).

This addressed my needs very nicely. Crossing my fingers.

Thanks again.

**Comment by brettz9** [comment]
In order to allow for potentially two different config settings, in `master`, I've deprecated `avoidClientSide` in favor of a more specific setting `avoidClientSideDownload` which can be used in the same way as you were using `avoidClientSide`.

I also added `avoidClientSideOpen` config to disable the exit upon `FileReader` support detection.

Both settings default to `false`.
