### ISSUE TITLE
Multiselect doesn't account for zoom

### ISSUE THREAD

**Issue by sjernigan** [SVG-Edit/svgedit#342]
**Describe the bug**
When zoomed, the selection of multiple items doesn't seem to account for the zoom.  Stretch it wide enough and you'll eventually grab the objects.

**To Reproduce**
1. Draw a few items.
2. Zoom to something other than 100%
3. Try to click-drag select multiple objects.

**Expected behavior**
The items in the box are selected.

**SVG-Edit environment (IMPORTANT)**
-Version: 4.3.0

**Desktop (please complete the following information):**
-OS: OSX
-Browser Chrome
-Version 73

**Additional context**
Very similar problem was previously described as a Firefox only issue #55

**Comment by FCCSeb** [comment]
Hi, I'm a little bit late but I have the same bug. 
Did you find a solution or temporary solution ? 

Have a good day !
Thanks.

**Comment by jfhenon** [comment]
Cannot be reproduced with V7
