### ISSUE TITLE
Resizing grouped text with any shape get stretched

### ISSUE THREAD

**Issue by shahalam-geek** [SVG-Edit/svgedit#344]
![issue](https://user-images.githubusercontent.com/46439269/57688615-852e0d00-765b-11e9-9cc9-d75bcf4324b8.png)

If I group Text with any shape  and resize it Text get stretched. for example if I group a Text with rect and resize it then Text get stretched as we can see in picture above.

I am using your software in my college project as a floor plan designer , and I am using rect as a room and Text as name or id for that room. and group them for avoiding the complexity for different rooms and I have to provide a function to resize the room, but here I am facing problem while resizing the room the Id of that room get stretched please help me to solve this problem by enhancing your software.

**Comment by NeiroNx** [comment]
It worked as planed, because uses svg "transform" parameter. You need use middle "text-marker" on line instead of text block. 
![image](https://user-images.githubusercontent.com/4705299/57694373-94fa2100-765c-11e9-8a1c-817ac2935c2f.png)

**Comment by brettz9** [comment]
Does @NeiroNx 's suggestion resolve your issue, @shahalam-geek ?

**Comment by shahalam-geek** [comment]
I am not able to implement **@NeiroNx** 's suggestion.Can You please elaborate it for me or any other suggestion,  **@brettz9** ?

**Comment by brettz9** [comment]
@NeiroNx , sorry, but can you show how you achieved this? You are getting text to remain constant while still being part of a group? I am not clear on how you achieved this myself. I know you can add a text marker on a line, but the line will be visible and grouping it with the rectangle will still make it resize.

**Comment by NeiroNx** [comment]
https://drive.google.com/file/d/1lPa2g-8om39enWTYQ4sFSuVbp6beC6zs/view

**Comment by brettz9** [comment]
Excellent! Thanks so much! (We could probably use a bunch of such videos if any contributors are ever so inspired...)

I will close, but feel free to comment further as needed @shahalam-geek ...
