### ISSUE TITLE
Toolbars: messy style

### ISSUE THREAD

**Issue by dredev89** [SVG-Edit/svgedit#352]
**Describe the bug**
The buttons in the top/left toolbars have not consistent margins/style.
The bottom toolbar also has some styling problems, resulting in elements overlapping.

**To Reproduce**
Open any version later than "3.0.0. - Alpha pre-release 1", from the releases page (https://github.com/SVG-Edit/svgedit/releases) 

**Expected behavior**
Consistent styiling

**SVG-Edit environment (IMPORTANT)**
- Version: every version later than "3.0.0. - Alpha pre-release 1"

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version 75.0.3770.142

**Screenshots**
![toolbars](https://user-images.githubusercontent.com/16489972/62530418-bd02b600-b840-11e9-806b-414b3e47bc0f.PNG)

**Comment by brettz9** [comment]
Did #348 fix the bottom toolbar issues for you?

**Comment by dredev89** [comment]
Yes, it solves just the toolbar issue. I had a similar result by applying this:

`#tools_bottom input[type=text] {
  width: auto;
}`

I don't know if it is better or not.

**Comment by jfhenon** [comment]
this does not apply with V7. (but I'm sure, we will have other similar issues to fix...)
