### ISSUE TITLE
Any plans to update UI?

### ISSUE THREAD

**Issue by mblataric** [SVG-Edit/svgedit#353]
Hi, 

This seems like a great and one of a kind library, it's hard to believe it does not attract more developers to it.
Which makes me wonder - are there any plans to update UI? It is really dated, like Windwos 95 dated and a modern refresh would be most welcome. 

Regards,
Mario

**Comment by brettz9** [comment]
As per the [README](https://github.com/SVG-Edit/svgedit#help-wanted), the project is not really being actively developed, though we have been refactoring somewhat to encourage new contributors as well as merging bug fixes and enhancements that individual contributors have submitted.

An updated theme--if that's what you're getting at--would be welcome and #294 ought to help in this regard. For other UI changes, feel free to submit separate issues/PRs if the envisioned changes would go beyond stylistic changes. But no plans for doing this on my own.

**Comment by jfhenon** [comment]
we updated the UI with V7
