### ISSUE TITLE
unable to load svg data in Image Occlusion add-on for Anki

### ISSUE THREAD

**Issue by galantra** [SVG-Edit/svgedit#358]
Hello.
I am using svgedit within the [Image Occlusion add-on ](https://github.com/Glutanimate/image-occlusion-enhanced)for Anki. Recently, I am frequently getting these error messages:
![grafik](https://user-images.githubusercontent.com/52420923/64943983-748ddd80-d86d-11e9-8d8a-00abea418beb.png)
I have no clue why.
It's still possible to review cards; but I cannot edit the svg.

**Comment by brettz9** [comment]
Please file this issue with the add-on. If they have a problem, they can file an issue here with more precise information about how they are calling our code. Thanks...
