### ISSUE TITLE
problem with file size 1.6MB

### ISSUE THREAD

**Issue by AhmedHelalAhmed** [SVG-Edit/svgedit#361]
**Describe the bug**
when I load file with 1.6 MB svgi can hardly edit and deal with it and suggestions? 

**To Reproduce**
1.  open a file with size 1.6 MB or larger 
2- try to edit ti it take a lot of time to response

**Expected behavior**
just as normal not to take too long time to response.

**SVG-Edit environment (IMPORTANT)**
- File for SVG-Edit: [e.g., `svg-editor.html`, `svg-editor-es.html`, `embedapi.html`]
- Version: [latest]
- Protocol: [file]

**Desktop (please complete the following information):**
 - OS: [windwos]
 - Browser [chrome]
 - Version [latest]

**Screenshots**
it takes too long time to response.

**Additional context**
Please help as we need it in our web app which organize a building we just need to remove rename objects in svg only simple functionalty.

**Comment by brettz9** [comment]
None of the core developers have been working on the project of late. If you were willing to encourage the development with some funds, you can add an amount at https://issuehunt.io/r/SVG-Edit/svgedit and that may attract some developers to try to improve the performance, though you might have to quantify your expectations, e.g., how much of a delay improvement you needed. This is just an idea though; I don't know if developers would work on it for sure.

**Comment by AhmedHelalAhmed** [comment]
I will try to make this optimization :)

**Comment by cuixiping** [comment]
We can try to lazy load some extensions and components.

**Comment by brettz9** [comment]
Extensions are already lazy-loaded (as are locales). It would be nice if possible to turn more functionality into extensions though...

**Comment by klesun** [comment]
Having a 16 MiB jpg texture for print loaded and editor is barely working ;c

**Comment by jfhenon** [comment]
Can you please retry with the current build and let us know the usability?

**Comment by jfhenon** [comment]
no answer so closing the issue. Can be reopen if required
