### ISSUE TITLE
Cannot save the svg in Internet Explorer 11.0.9600.18920

### ISSUE THREAD

**Issue by schafx** [SVG-Edit/svgedit#363]
Hi I have IE 11.0.9600.18920 and tried to use your online version 5.0.0.
If I try to save my created SVG it gives me an error.
Something with variable is in strict mode...
I used this Version of you tool:

https://unpkg.com/svgedit@5.0.0/editor/svg-editor.html
the problems seems to be in line 30538 
a.style = 'display: none;'; 
in File
 https://unpkg.com/svgedit@5.0.0/svgedit-config-iife.js

Thank you for your support.

**Comment by brettz9** [comment]
I've added this fix to the latest version, 5.1.0, just released. Feel free to report if you come across other issues.

You can test against our Github-hosted demo: https://svg-edit.github.io/svgedit/releases/svg-edit-5.1.0/editor/svg-editor.html
