### ISSUE TITLE
IE: After draw Rectangle there is no select event happen

### ISSUE THREAD

**Issue by fkcailiniyazi** [SVG-Edit/svgedit#364]
**Describe the bug**
After I drawed a Rectangle, I tried to select it by click, but it didn't work, I have to click selection from toolbar or click resize/rotate to select it.

**To Reproduce**
1. Open SVGEditor from Internet Explorer
2. Draw a rectangle
3. Click on it
4. See the error

**Expected behavior**
Like other tool(circle for example) after click on it, a rectangle should be selected.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Internet Explorer 10

**Screenshots**

![Screenshot (3)](https://user-images.githubusercontent.com/54360982/69351885-474e1900-0c7c-11ea-8318-5205bb018f68.png)

**Comment by brettz9** [comment]
Are you able to confirm your fix still works in other browsers besides IE?

**Comment by fkcailiniyazi** [comment]
I have tested with latest versions of Chrome/Opera/Firefox/Microsoft Edge/ Internet Explorer 10, 11, this works.

**Comment by brettz9** [comment]
Ok, great.

Would you mind also adding a UI test case (to the just-now-added to `master`  Cypress UI tests)? Specifically, if you could add to `cypress/integration/ui.js`.

(Cypress is a UI testing tool which has the awesome ability to give us coverage reports (and its coverage can also integrate with regular unit tests, though our old HTML tests have not yet been converted over). It sadly does not support non-Chromium based browsers at the moment, but I thought it was worth switching from Testcafe due to this great ability to get coverage info.)

**Comment by fkcailiniyazi** [comment]
I am sorry that I'm late to reply to you, I was at vacation.

I could try to add UI test case, but I don't know how to do it, I checked the documentation, but I found difficulties to understand it.

**Comment by brettz9** [comment]
I will need more time then, as I have a number of projects on my plate. If you look at the examples though (including the ones in our project), Cypress is pretty intuitive to pick up.

**Comment by brettz9** [comment]
Even though Cypress [doesn't yet support other non-Chrome browsers](https://github.com/cypress-io/cypress/issues/310), I'd still like to add the test to ensure we're ok with other browsers, and once they may get that support.

In trying to prepare the UI case, however, I'm not clear on what happens after you draw the rectangle. Are you saying it is not selected right after drawing the rectangle?

Also, when you say "click resize/rotate", which form controls are you talking about? Don't the resize/rotate controls only show up after the rectangle is selected?

**Comment by fkcailiniyazi** [comment]
Hi Brettz9, happy new year at first.
My problem was, I tried to select rectangle by clicking after drawed it for many porpuse, like moving it or delete it, but it wont happent. I have to select the rectangle either by selecting other object or by clicking the controls for reseize/rotate.
