### ISSUE TITLE
Cannot save svg

### ISSUE THREAD

**Issue by cdalexndr** [SVG-Edit/svgedit#368]
**Describe the bug**
Using https://svg-edit.github.io/svgedit/releases/svg-edit-2.8.1/svg-editor.html
Cannot save as svg on firefox

**To Reproduce**
1. Make any svg
2. SVG-Edit -> Save Image
3. The page opened is blank and cannot save svg
4. Repeat step 2
5. No page is opened (new tab is created and closed immediately)

**Expected behavior**

**SVG-Edit environment (IMPORTANT)**
- File for SVG-Edit: [e.g., `svg-editor.html`, `svg-editor-es.html`, `embedapi.html`]
- Version: 2.8.1
- Protocol: https

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Firefox
 - Version 70.0.1 (64bit)

**Comment by brettz9** [comment]
Please test against the most recent version, i.e., https://svg-edit.github.io/svgedit/releases/latest/editor/svg-editor.html or https://svg-edit.github.io/svgedit/releases/svg-edit-5.1.0/editor/svg-editor.html .

It sounds like you may have an issue with a pop-up blocker though.

**Comment by cdalexndr** [comment]
Works with https://svg-edit.github.io/svgedit/releases/latest/editor/svg-editor.html
