### ISSUE TITLE
Switch files to the one true line ending and indentation

### ISSUE THREAD

**Issue by progers** [SVG-Edit/svgedit#37]
Some files have old-style windows line endings such as ext-imagelib.js. We should clean these up.

**Comment by codedread** [comment]
I'd also like to see us switch from tabs to 2-sp indenting... wdyt?

**Comment by progers** [comment]
2-space indents would be great. There's quite a bit of inconsistent style; it would be nice to reformat everything using idiomatic js or the google js guide.

**Comment by brettz9** [comment]
I think this should now be all covered in `master`...
