### ISSUE TITLE
Suggestions about the main menu style and text

### ISSUE THREAD

**Issue by cuixiping** [SVG-Edit/svgedit#371]
# 1. Style

Currently, there are 3 different styles in the main menu:
- Menu item
- Link
- Button

Link and button can be changed to menu item and will be more unified.

(Currently) 
![image](https://user-images.githubusercontent.com/1104492/71256644-56ec7a80-236c-11ea-8b58-4f9775f8bb65.png) 

(Suggestion) 
![image](https://user-images.githubusercontent.com/1104492/71256657-5fdd4c00-236c-11ea-8fbe-d5b84d15e0e9.png)

# 2. Style

Two menu items show hand cursor with a tip text (by the file input ), other items show arrowhead cursor.

I suggest changing to hand cursor style, and move the file inputs to anotherwhere.

![image](https://user-images.githubusercontent.com/1104492/71258424-193e2080-2371-11ea-9f85-eb589ef73684.png)  ![image](https://user-images.githubusercontent.com/1104492/71258428-1c391100-2371-11ea-8d07-c1f5cf4c20c8.png)

# 3. Text

Button uses `Editor Options` but dialog uses `Editor Preferences` , and `Editor Options` button has no i18n.

Suggestion:  Change `Editor Options` to `Editor Preferences`

![image](https://user-images.githubusercontent.com/1104492/71256828-f3af1800-236c-11ea-8b59-1b9c8328a30f.png)  ![image](https://user-images.githubusercontent.com/1104492/71256837-fc075300-236c-11ea-9513-58bed4174700.png)

# 4.
I can send a PR if the above suggestions are accepted.

**Comment by brettz9** [comment]
These changes sound good to me, though I wasn't clear what you meant by "move the file inputs". Move what? And to where?

**Comment by cuixiping** [comment]
> These changes sound good to me, though I wasn't clear what you meant by "move the file inputs". Move what? And to where?

Move the `<input type=file>` elsewhere in the page HTML code. Then we can control the cursor style as we like.

![image](https://user-images.githubusercontent.com/1104492/71301882-aa4be080-23df-11ea-9181-ce125eb0b6b0.png)

**Comment by brettz9** [comment]
Ok, gotcha, thanks... And SGTM...

**Comment by brettz9** [comment]
Fixed in `master`. Thanks very much!
