### ISSUE TITLE
Save not working

### ISSUE THREAD

**Issue by axet** [SVG-Edit/svgedit#373]
Hello! Save button or hot key not working with recent chrome 79 (at least under osx)! It open new empty tab and do nothing.

1) open svg from file
2) hit 'S' or 'SVG-Edit/Save Image'

**Comment by brettz9** [comment]
Closing as did not provide the requested fields. Not replicating and may be due to version information.

**Comment by axet** [comment]
Yep. Google suggest the following url with bug I reported (try to search svg editor):

https://svg-edit.github.io/svgedit/releases/svg-edit-2.8.1/svg-editor.html

I guess, its a google issue :)

**Comment by brettz9** [comment]
Cool... Yeah, so the latest release you can find at: https://svg-edit.github.io/svgedit/releases/latest/editor/svg-editor.html
