### ISSUE TITLE
Toolbar expanded buttons are off the correct position in Firefox

### ISSUE THREAD

**Issue by cuixiping** [SVG-Edit/svgedit#375]
**Describe the bug**
Toolbar expanded buttons are off the correct position in Firefox.
It's ok in Chrome.

**To Reproduce**
Click the toolbar button's right bottom corner.
See screenshot.

**Expected behavior**

**SVG-Edit environment (IMPORTANT)**
- File for SVG-Edit: `svg-editor-es.html`
- Version: master
- Protocol: http

**Desktop (please complete the following information):**
 - OS: Win7
 - Browser Firefox
 - Version 71

**Screenshots**
Firefox:
![image](https://user-images.githubusercontent.com/1104492/71764702-18d38700-2f26-11ea-91ab-10e457e67a8b.png)

Chrome:
![image](https://user-images.githubusercontent.com/1104492/71764709-2ee14780-2f26-11ea-8aa0-75a5901350c5.png)

**Comment by brettz9** [comment]
Maybe try upgrading to FF 72? I don't see any problem in FF 72 on my Mac. It's not perfectly aligned with small icons (medium icons are ok), but it doesn't have a gap as big as in your picture.

**Comment by cuixiping** [comment]
FF 71 is up to date on my windows. 
This issue may not occur, but it has a high probability if I refreshed a few times.

Does `latest` mean `master`? or the last release?

"**https://svg-edit.github.io/svgedit/releases/latest/editor/svg-editor-es.html**" files is not same as the svgedit's master branch.

**Comment by brettz9** [comment]
Oh, I am seeing something on `master`.

**Comment by cuixiping** [comment]
`SVG-Edit.github.io` repo is 500 MB! 
`SVG-Edit.github.io` repo can only provide master version demo and links to the each releases for example `https://github.com/SVG-Edit/svgedit/releases/tag/v5.1.0`.

**Comment by brettz9** [comment]
I think we will definitely want to keep at least the last previous major version, as some may be slow to upgrade, and it can help us see where regressions occurred more easily as well. But I'm open to dropping the others.

**Comment by ievgennaida** [comment]
In Chrome it's not possible to open this panel at all

**Comment by jfhenon** [comment]
The part of the UI was rewritten and this issue is gone.
