### ISSUE TITLE
License review / Replace images with unclear license provenance (`editor/images`)

### ISSUE THREAD

**Issue by brettz9** [SVG-Edit/svgedit#377]
I have been reviewing the license content of svgedit, and added a couple badges to indicate the licenses of the repo and its bundled dependencies (and one for devDependencies). Any feedback would be welcome.

~Anyways, when searching for license info *within* svgedit, I discovered that there is at least one SVG file with the viral license "CC-BY-SA-2.0". See https://creativecommons.org/licenses/by-sa/2.0/ . My review has found that no other licenses in our package, including bundled dependencies (and we have no `dependencies`) are explicitly virally restrictive besides this one.~

~Since we don't want to be required to make the library require compliance with this license type (assuming it is even compatible with the rest of the licenses), we really need to substitute this image.~

~The image that was labeled with this license was `editor/images/polygon.svg` (and presumably a file generated from it, `editor/images/polygon.png`)--a small polygon (`http://creativecommons.org/licenses/by-sa/2.0/` is referenced in source).~ The other files in that directory do not have clear license information, merely stating a source for some files. 

~While~ I think we should replace all of these icons ~, for starters, I think we really need to avoid this dependency.~

**Update: we have replaced the explicitly protective (CC-BY-SA-2.0) license file, but still are unclear on the license status of the other image files.**

**Comment by mowijo** [comment]
I have a rudimentary SVG+PNG that I can push. It still does not

> ... replace[d] all of these icons...

and confuses the visual expression a bit, but it gets out of the SA-2.0 license.
What license would you prefer and how do I make a merge request?

**Comment by brettz9** [comment]
Sounds wonderful, thank you!

The MIT license would be great if that is ok--much of the project uses it, and it is very permissive.

You can:

1. Clone the repository
2. Add a branch on top of our current `master` branch with your change
3. Push the branch to Github.
4. Visit the main page of svgedit on Github or the Pull Requests page, and click the button that should automatically give you a chance to make a pull request for your new branch (assuming you have gotten your branch successfully pushed). (You can also make pull requests by going to https://github.com/SVG-Edit/svgedit/compare and clicking to "compare across forks" but it should easier if you use the automatic button instead, as you will not need to hunt for your branch.)

Let me know if you have difficulties in any of these steps. If this ends up too difficult, you can paste the SVG source here (e.g., within fenced blocks--3 backticks before and after the SVG code).

**Comment by mowijo** [comment]
So apparently I am not allowed to push to your repo which kind of makes sense. Well. [Here is a patch](https://github.com/SVG-Edit/svgedit/files/4570523/0001-See-377.-Replaces-polygon-icons-with-images-under-MI.txt) resulting from a `git format-patch HEAD~1`

**Comment by brettz9** [comment]
So, to confirm, submitting as MIT is ok with you?

**Comment by brettz9** [comment]
Nevermind, I see that was added within the file, thanks...

**Comment by brettz9** [comment]
@prusnak , having adding the original editor/images/README.txt file to track the image file origins, do you recall the license terms of either the files listed with the http://tango.freedesktop.org/static/cvs/tango-art-libre origin or files without an origin? In this issue, we are replacing here one file whose metadata shows it is under the protective CC-BY-SA-2.0 license, but we're not clear on the licenses of the other image files... Thanks!

**Comment by brettz9** [comment]
Btw, @mowijo , thank you very much for your contribution. It has now been added to `master`! Although I've removed the explicit reference to CC-BY-SA-2.0 in our multi-licensing lists, I've added a note indicating our lack of clarity of provenance of the other image files (and still linking to this issue).

But this should provide at least some assurance to users requiring non-restrictive terms that we are at least not knowingly including content with more protective licenses.

As mentioned on the README, if anyone can provide replacement images, or indicate the actual license types of the other image files in `/editor/images`, it would be most appreciated.

Thanks again!

**Comment by mowijo** [comment]
Our of curiosity, is https://creativecommons.org/licenses/by/4.0/ acceptable for this project?

**Comment by brettz9** [comment]
Yes, that would be fine. Just would want to avoid the viral "Share-Alike" Creative Commons versions (or the ones placing restrictions on how the content is used, such as non-commercial, no-derivatives, etc.).

IANAL, but I think with the MIT license requiring "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software", it ends up ensuring that attribution is preserved too, as long as you add your name to the license copyright portion (in our case, we are just pointing to our AUTHORS file where you could also add your name).

**Comment by brettz9** [comment]
Did you wish to change the license terms?

**Comment by jfhenon** [comment]
We recreated icons as SVG in V7 under the MIT licence
