### ISSUE TITLE
Clipboard uses local storage and persists forever

### ISSUE THREAD

**Issue by NeilFraser** [SVG-Edit/svgedit#379]
**Describe the bug**
SvgCanvas uses `localStorage` to save the contents of the clipboard.  This lasts forever, and has GDPR implications since users do not expect that the contents of their clipboard will survive beyond the current session, let alone a reboot of their computer.

**To Reproduce**
1. Go to https://svg-edit.github.io/svgedit/releases/latest/editor/svg-editor.html
2. Create any shape.
3. Cut the shape using the keyboard shortcut or the context menu.
4. Close the tab, close your browser (optionally reboot your computer).
5. Restart your browser, reopen a tab to https://svg-edit.github.io/svgedit/releases/latest/editor/svg-editor.html
6. Paste using the keyboard shortcut or the context menu.

**Expected behaviour**
The expected behaviour is that nothing would be pasted.  The actual behaviour is that the content is pasted.

**Proposed solutions**
I'm happy to implement the fix, but I want opinions on which direction to pursue before doing so.
* Switching from localStorage to sessionStorage would be trivial.  However, it would not allow for copy/paste operations between tabs.
* Switching from localStorage to a session cookie would be nearly as trivial and does work across tabs.  However, cookies would impose a 4 kb limit on the clipboard, instead of the storage API's 5 MB limit.
* Switch to sessionStorage, but also add event monitoring to synchronize data across tabs.  See [this answer on StackOverflow](https://stackoverflow.com/questions/20325763/browser-sessionstorage-share-between-tabs).

**Comment by brettz9** [comment]
FWIW, with the (default-on) `ext-storage` extension, we do have the approval when first starting svgedit which states:

> By default and where supported, SVG-Edit can store your editor preferences and SVG content locally on your machine so you do not need to add these back each time you load SVG-Edit. If, for privacy reasons, you do not wish to store this information on your machine, you can change away from the default option below.

In any case though, this is a bug as the clipboard is indeed not hooked into that mechanism (and with it being saved, I imagine we could be getting a memory leak which even persists across sessions?).

I think that while your item no. 3 would be a nice-to-have if you wish to implement, I think no. 1 would be sufficient. However, if the potential memory issue could be resolved, `localStorage` may be a nice optional feature. Personally, I am happy if could get back to my undos for a document after a restart.
