### ISSUE TITLE
`Uncaught TypeError: Cannot read property 'getAttribute' of undefined` when I press delete when editing shape path

### ISSUE THREAD

**Issue by klesun-misc** [SVG-Edit/svgedit#382]
**Describe the bug**
When I hit "Delete" button, while in shape editing mode, nothing happens in the editor, and `Uncaught TypeError: Cannot read property 'getAttribute' of undefined` error appears in console.

**To Reproduce**
1. Open the editor (for example in your [demo](https://unpkg.com/svgedit@5.1.0/editor/svg-editor.html))
2. Draw some shape with _Path Tool_
3. While bezier curves mode is still on, try pressing "Delete" or "Backspace"
4. See error in the console

**Expected behavior**
I would guess that pressing delete is supposed to remove the selected verticle from the path.

**SVG-Edit environment (IMPORTANT)**
- File for SVG-Edit: `svg-editor.html`
- Version: 5.1.0 (the one in the demo, though same error happens in the f9f359b98f9bb292313f24e21db168595c5f8d9c)
- Protocol: https

**Desktop (please complete the following information):**
 - OS: Linux Mint 18.3
 - Browser Chromium
 - Version v79

**Screenshots**
![image](https://user-images.githubusercontent.com/30558426/73544380-b648aa80-4441-11ea-8de3-f14a68a47218.png)

**Additional context**
```
ext-connector.js:605 Uncaught TypeError: Cannot read property 'getAttribute' of undefined
    at Object.elementChanged (ext-connector.js:605)
    at Object.<anonymous> (svgedit-config-iife.js:14519)
    at Function.each (jquery.min.js:2)
    at SvgCanvas.runExtensions.runExtensions (svgedit-config-iife.js:14506)
    at Object.elementChanged [as changed] (svgedit-config-iife.js:31591)
    at call (svgedit-config-iife.js:14091)
    at SvgCanvas.deleteSelectedElements (svgedit-config-iife.js:20581)
    at deleteSelected (svgedit-config-iife.js:33363)
    at HTMLDocument.<anonymous> (svgedit-config-iife.js:35500)
    at HTMLDocument.d.handler (svgedit-config-iife.js:21864)
```

**Comment by brettz9** [comment]
Confirmed. In Firefox, I instead get the error, "TypeError: elem is undefined ext-connector.js:625:13"

**Comment by brettz9** [comment]
Confirmed. In Firefox, I instead get the error, "TypeError: elem is undefined ext-connector.js:625:13"

**Comment by brettz9** [comment]
@cuixiping : While this predates your recent work on paths, as you have worked with them, do you have an interest to look at this?
