### ISSUE TITLE
SVG with tiger hangs the app.  App right click is extremely unresponsive.

### ISSUE THREAD

**Issue by ievgennaida** [SVG-Edit/svgedit#385]
**Describe the bug**
The application is not responding for the 5+  seconds and hangs the browser on the right click.

**To Reproduce**
1. Open the default tiger SVG (the same as on the main picture of the app).
2. Right-click.

Tested on the website 
https://svg-edit.github.io/svgedit/releases/latest/editor/svg-editor.html

**Expected behavior**
The context menu is displayed at least within few seconds.

Latest chrome, windows.

Ghostscript Tiger, one of the standards for SVG vector rendering testing: 

Source SVG: https://upload.wikimedia.org/wikipedia/commons/f/fd/Ghostscript_Tiger.svg

**Comment by brettz9** [comment]
As with #391, while I know the screenshot is at `docs/screenshot.png`, I need to know where are you obtaining the "default tiger SVG" from. Thanks!

**Comment by dredev89** [comment]
I was having performance issues with large files too.
Removing the extension "ext-overview_window" from the svgedit-config-es.js file helped a lot in improving the performance.
Maybe you want to check if it is working for you too.

- comment the ext-overview_window extension
- run the npm script build-by-config

**Comment by ievgennaida** [comment]
> As with #391, while I know the screenshot is at `docs/screenshot.png`, I need to know where are you obtaining the "default tiger SVG" from. Thanks!

SVG file link was attached.

**Comment by jfhenon** [comment]
We moved several parts of svgedit to more native functions. 
could you test again?
https://svgedit.netlify.app/editor/index.html

**Comment by jfhenon** [comment]
We also removed the overview window of the right panel causing a lot of delays. 
I assume that you've seen performance increase.
