### ISSUE TITLE
Polyline/path canceled by a right-click crashes the app state.

### ISSUE THREAD

**Issue by ievgennaida** [SVG-Edit/svgedit#386]
**Describe the bug**
Adorners are broken, when creation of the line is started and then right-click is performed.

**To Reproduce**
1. Start creating polyline. 
2. Right-click 
3. App is broken (broken adorners, broken selection, cannot create new polyline.)

**Comment by brettz9** [comment]
By creating a polyline, I assume you mean using the path tool? (I'm not really an SVG person--just keeping the project here alive and maintained.)

Yes, I can confirm this. FWIW, in the middle of using the path tool and using right-click, in Firefox I see everything disappear, not visibly broken as in Chrome.

**Comment by ievgennaida** [comment]
The problem is more than just disappeared helpers. Futher using of the app leads sometimes to unpredictable helpers visualization bugs.

**Comment by AgriyaDev5** [comment]
https://user-images.githubusercontent.com/44435283/126441611-ce3379e9-399e-4f0e-a249-6128ac16591c.mp4
