### ISSUE TITLE
`npm ci` fails

### ISSUE THREAD

**Issue by cpcallen** [SVG-Edit/svgedit#388]
**Describe the bug**

Running `npm ci` in a freshly-cloned repo fails.

**To Reproduce**

1. Clone repo:

```
~/src$ git clone https://github.com/SVG-Edit/svgedit.git
Cloning into 'svgedit'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 27491 (delta 7), reused 11 (delta 4), pack-reused 27474
Receiving objects: 100% (27491/27491), 59.60 MiB | 3.52 MiB/s, done.
Resolving deltas: 100% (18610/18610), done.
```

2. Run `npm ci`:

```
~/src$ cd svgedit/
~/src/svgedit$ npm ci
npm ERR! code 128
npm ERR! Command failed: git checkout 326bbed67abe38bebbb35098cd38f0101f7eb80e
npm ERR! fatal: reference is not a tree: 326bbed67abe38bebbb35098cd38f0101f7eb80e
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cpcallen/.npm/_logs/2020-02-20T19_49_39_961Z-debug.log
```

See [contents of error log here](https://gist.github.com/cpcallen/88ac4664a61e991199fc730e95fd1020).

**Expected behavior**

All required modules for (e.g.) running tests are installed.

**SVG-Edit environment**

- File for SVG-Edit: n/a
- Version: current master (f594813)
- Protocol: n/a

**Additional context**

This came up while attempting to help @NeilFraser reproduce bug #387.  I started by trying to run tests [per instructions](https://github.com/SVG-Edit/svgedit/blob/master/docs/Testing.md), beginning with `npm run build-docs` which failed due to  being unable to find `run-s`.  Trying to run `npm ci`, which is my usual first approach to ensuring all dependencies are correctly installed, failed.  Later I tried `npm install`, which seems to work better (though interestingly I noticed it only downloaded and installed Cypress the second time I ran `npm install`, having in the mean time done `rm -rf node_modules` manually; unfortunately I am unable to reproduce this(1).

I can subsequently confirm that `git clone …` + `npm install` + `npm run build-docs` (or `npm test`) seems to work fine.

(1) Presumably this was due to having gotten my repo into a weird state by (for example) having done `npm ci`, noting that `npm run build-docs` was still failing because it couldn't find `run-p`, discovering that although `node_modules/npm-run-all/bin/run-p` existed it hadn't been symlinked to `node_modules/.bin` and doing a manual `npm install npm-run-all` to attempt to correct this.

**Comment by brettz9** [comment]
Hi, thanks for the report and info.

I cloned and ran `npm ci` without problems (and `npm run build docs`). I then ran `npm ci` again (in case the repeating was the cause), and wasn't able to replicate here either.

I'm on a Mac. You?

I'm wondering if this is just some bug with npm or maybe your install completed but the post-install scripts did not complete for some unrelated reason.

I have myself occasionally had to use `npm rebuild`, e.g., when a poor connection gets the regular npm installed files, but the build steps do not complete. With the Mac, there can also be a step to verify the Cypress build so though it should download, the test script might time out upon a first run (or until the verification completes). (Testcafe also required System Preference whitelisting, e.g., for screen recording, but I don't see that Cypress does so, maybe because Cypress uses the browser's own abilities.)

Are you consistently seeing a problem with `npm ci` or can we chalk this up to being some temporary network or system fluke?

**Comment by cpcallen** [comment]
I am also on macOS: v10.14.6, with git v2.24.0.525.  I updated `npm` just to make sure that wasn't an issue.  Here's the whole sequence:
```
~/src$ git clone https://github.com/SVG-Edit/svgedit.git
Cloning into 'svgedit'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 27514 (delta 18), reused 23 (delta 9), pack-reused 27474
Receiving objects: 100% (27514/27514), 59.60 MiB | 5.19 MiB/s, done.
Resolving deltas: 100% (18621/18621), done.

~/src$ npm i -g npm
/usr/local/brew/bin/npx -> /usr/local/brew/lib/node_modules/npm/bin/npx-cli.js
/usr/local/brew/bin/npm -> /usr/local/brew/lib/node_modules/npm/bin/npm-cli.js
+ npm@6.13.7
updated 1 package in 5.03s

~/src$ npm --version
6.13.7

~/src$ cd svgedit/

~/src/svgedit$ npm ci
npm ERR! code 128
npm ERR! Command failed: git checkout 326bbed67abe38bebbb35098cd38f0101f7eb80e
npm ERR! fatal: reference is not a tree: 326bbed67abe38bebbb35098cd38f0101f7eb80e
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cpcallen/.npm/_logs/2020-02-21T18_21_05_485Z-debug.log
```
There is no sign whatsoever of any post-install scripts being run.  I note that `npm ci` displays a series of quickly-overwritten progress messages until the `ERR! code 128` appears; after that, there is a delay with no further visible updates until the final "complete log" message appears just before it terminates.

**Comment by brettz9** [comment]
Thanks for the helpful report! I found `package-lock.json` had a SHA pointing to a custom fork which I had later overwritten and forgot to update. Should now be fixed, thanks!
