### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by frist008** [SVG-Edit/svgedit#392]
**Describe the bug**
404 not found

**To Reproduce**
1. Go to https://svg-edit.github.io/svgedit/releases/latest/editor/svg-editor.html

**SVG-Edit environment (IMPORTANT)**
- File for SVG-Edit:`svg-editor.html`, `svg-editor-es.html`, `embedapi.html`
- Version: latest  5.1.0 6.0.0
- Protocol: http, https

**Desktop (please complete the following information):**
 - Browser chrome, safari
 - Version latest 5.1.0 6.0.0

**Screenshots**
http://dl4.joxi.net/drive/2020/02/24/0016/2100/1095732/32/5f4e06df27.png

**Comment by brettz9** [comment]
Thanks for the report. If anyone could help with https://stackoverflow.com/questions/60353589/adding-a-submodule-with-a-branch-that-is-present-at-the-given-url-but-is-not-pre , it'd be most appreciated, as that could allow me to add the submodules which were hosting the demos back in a proper manner.

**Comment by jeremydouglass** [comment]
The broken link is also the prominant "**Try SVG-edit here**" linked twice in README.md:

> ### [Try SVG-edit here](https://svg-edit.github.io/svgedit/releases/latest/editor/svg-editor.html)
> See the [latest release](https://svg-edit.github.io/svgedit/releases/latest/editor/svg-editor.html)

If resolving this held up by something, you might want to change those two links in the readme to point to the latest master, which link is working:

https://svg-edit.github.io/svgedit/editor/svg-editor.html

**Comment by brettz9** [comment]
Thanks for the report and to @jeremydouglass for the extra info. Fixed in 65fcb1da9aeee56ee71035dc058ad2c04bee4535
