### ISSUE TITLE
Ungroup Elements is not working properly

### ISSUE THREAD

**Issue by Jeyssiva** [SVG-Edit/svgedit#393]
**Describe the bug**
 Ungrouping is not working properly if have not any siblings to the selected group element.

**To Reproduce**
1. Open as a new Page.
2. Create two or more elements (For Ex: rectangle, circle)
3. Group the elements using a grouping tool
4. Select the grouped elements and click "ungroup icon"

**Comment by brettz9** [comment]
I've added a fix on `master`. Let me know if that works for you. (You can try on the demo at https://svg-edit.github.io/svgedit/editor/svg-editor-es.html until we may get the `latest` and previous releases working again.)

**Comment by Jeyssiva** [comment]
Working as expected. Thanks
