### ISSUE TITLE
Offer Method-Draw-like theme

### ISSUE THREAD

**Issue by memtech3** [SVG-Edit/svgedit#398]
merge the method draw project into the svgedit project
https://github.com/methodofaction/Method-Draw

**Comment by brettz9** [comment]
We don't have any core developers working on the project these days anyways, but please be precise in what you want integrated from it. As it mentions it was a fork of svg-edit, what are the features from it that you want incorporated?

**Comment by memtech3** [comment]
Mostly its UI. Its a lot more modern

**Comment by brettz9** [comment]
You want the theme or certain features?

**Comment by memtech3** [comment]
The theme

**Comment by jfhenon** [comment]
V7 has a new style
