### ISSUE TITLE
Shape Library’s behaviour on IE11

### ISSUE THREAD

**Issue by arundhatip** [SVG-Edit/svgedit#400]
**Describe the bug**
When Shape library’s Categories are traversed from top to bottom., it shows all symbols. However when traversed again from bottom to top, icons for some categories are not visible.  

**To Reproduce**
1. Go to https://unpkg.com/svgedit@5.1.0/editor/svg-editor.html from IE11
2. Click on Shape Library icon and then traverse through categories from “Basic" to "Raphaeljs.com Set 2" and then again traverse in the reverse order from “Raphaeljs.com Set 2” to “Basic”. 
3. See error as icons are now not visible

**Expected behavior**
Irrespective of any order of traversing through categories, icons should be visible.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Internet Explorer 11
 - Version: 11.719.18362.0

**Screenshots**
When it works for the first time:
![image](https://user-images.githubusercontent.com/8402508/77082565-87d85c00-69fc-11ea-932b-0f249db1ebee.png)

After visiting this again
![image](https://user-images.githubusercontent.com/8402508/77082680-b5bda080-69fc-11ea-93bc-46eddf55ef71.png)

**Comment by brettz9** [comment]
If you are getting an error in the console, could you paste that message for us?

**Comment by arundhatip** [comment]
There is no error on console regarding this.

**Comment by jfhenon** [comment]
This button was rewritten in V7.
