### ISSUE TITLE
Bug when trying to show SVG content

### ISSUE THREAD

**Issue by jfhenon** [SVG-Edit/svgedit#408]
**Describe the bug**
Bug when trying to show SVG content when the context is changed.

**To Reproduce**
1. Load the following sampe SVG:
```
<svg width="640" height="480" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
 <!-- Created with SVG-edit - https://github.com/SVG-Edit/svgedit-->
 <g class="layer">
  <title>Layer 1</title>
  <g id="svg_6">
   <rect fill="#FF0000" height="71" id="svg_1" stroke="#000000" stroke-width="5" width="94" x="69.5" y="51.5"/>
   <circle cx="117.5" cy="87.5" fill="#ffff00" id="svg_5" r="19.84943" stroke="#000000" stroke-dasharray="null" stroke-linecap="null" stroke-linejoin="null" stroke-width="5"/>
  </g>
 </g>
</svg>
````
2. move the context to the group by double-click on the rectangle
![image](https://user-images.githubusercontent.com/20402845/79689039-93fd4680-8252-11ea-9218-a7372ce80d79.png)
3. click on the following button ![image](https://user-images.githubusercontent.com/20402845/79689115-08d08080-8253-11ea-8455-fa9c3a0dab72.png) 
4. the action will fail and an error is displayed in the console: 
![image](https://user-images.githubusercontent.com/20402845/79689102-ed657580-8252-11ea-8430-c7593e352856.png)
**Expected behavior**
A window with the SVG content should be displayed.

**SVG-Edit environment (IMPORTANT)**
https://unpkg.com/svgedit@5.1.0/editor/svg-editor.html

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 81.0.4044.113

**Screenshots**
see above

**Log**
see above 

**Additional context**
https://github.com/SVG-Edit/svgedit/blob/4b92acc79047ad3fede9945c3bc0a55f8c23f6ef/editor/svgcanvas.js#L695

This seems to related to the conditional statement above. If showGrip is false or undefined AND selectedElements.length == 0, it fails on the statement selectorManager.requestSelector. 

should it be the following? 
```
if (selectedElements.length === 1) {
  selectorManager.requestSelector(selectedElements[0]).showGrips(showGrips)
}
```

**Comment by brettz9** [comment]
Hi @jfhenon .... Is there anything left outstanding on this?
