### ISSUE TITLE
svg-edit canvas locked after using subpath tool

### ISSUE THREAD

**Issue by michaeleconomy** [SVG-Edit/svgedit#409]
**Describe the bug**
program gets completely locked up and won't do anythnig

**To Reproduce**
1. us path tool
2. draw a shape
3. click on subpath
4. draw another shape
5. program locked

**Expected behavior**
It does not lock

**SVG-Edit environment (IMPORTANT)**
- File for SVG-Edit: https://svg-edit.github.io/svgedit/editor/svg-editor.html
- Version: ?

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser firefox
 - Version 75

**Log**
TypeError: editorContext_ is undefinedsvgedit-config-iife.js:7473:11
    toEditMode https://svg-edit.github.io/svgedit/svgedit-config-iife.js:7473
    mouseDown https://svg-edit.github.io/svgedit/svgedit-config-iife.js:7161
    mouseDown https://svg-edit.github.io/svgedit/svgedit-config-iife.js:15971
    jQuery 2

**Comment by jfhenon** [comment]
fixed with commit 6579c7e
