### ISSUE TITLE
Panning icon is inconsistent with rest of icons

### ISSUE THREAD

**Issue by michaeleconomy** [SVG-Edit/svgedit#412]
**Describe the bug**
Panning icon is this weird maroon color, and hard to tell that it's a panning icon (not enough spacing between arrows and box).

**Expected behavior**
I'd expect something along the lines of: https://icons8.com/icons/set/move

**SVG-Edit environment (IMPORTANT)**
- File for SVG-Edit: https://svg-edit.github.io/svgedit/editor/svg-editor.html

**Desktop (please complete the following information):**
win10 firefox 75

**Screenshots**
https://imgur.com/a/AiFX4sZ

**Comment by jfhenon** [comment]
Fixed
