### ISSUE TITLE
A small doc on how to go about integrating the app

### ISSUE THREAD

**Issue by subbusgithub** [SVG-Edit/svgedit#413]
Dear Authors,
First of all thank you for such a wonderful app. I am wanting to integrate it with one of my apps with some customization. I want to customize the tool bar options, add my own tools etc. However in the process I failed to get any documentation on the modules and apis and am spending time debugging it to understand the flow. I request you to just scribble a few lines if not a formal document so that people can understand the flow and use the apis to integrate the app within other applications. Also please point me to any document if it exists.

**Comment by brettz9** [comment]
Did you noticed the [`docs`](https://github.com/SVG-Edit/svgedit/tree/master/docs)folder?

**Comment by subbusgithub** [comment]
@brettz9 I did look into the "https://github.com/SVG-Edit/svgedit/blob/master/docs/tutorials/EditorAPI.md". But I could only find reference to "[Editor JSDocs]{@link module:Editor}". I am relatively new to this and have been asked to implement this feature. Kindly direct me to the right set of documents if this is not the location. Please bear with me if this sounds silly as I am just starting off.

**Comment by brettz9** [comment]
You can build the documents locally after a local `npm install` by running `npm run build-docs`. That should get the document links working properly.

**Comment by subbusgithub** [comment]
@brettz9 Thanks a lot for the help...I shall give that a try and get back.

**Comment by brettz9** [comment]
Ok, good Closing as that should resolve. For further general help questions, please ask at StackOverflow or such. Thanks!

**Comment by subbusgithub** [comment]
@brettz9 I tried using npm install and npm run build-docs. It does generate a lot of docs but the editor api page is still the same short and with inactive links (Editor JSDocs). Please see the screenshot. Let me know where I am going wrong. I also tried to traverse through the docs folders and kinda understood that svg-editor.js is probably the file that contains the entry point and apis. Kindly let me know if there is a more clearer document than going through the source code
![Svg-Editor-DocIssue](https://user-images.githubusercontent.com/17960307/81002058-47c32080-8e66-11ea-8bce-7eef5e0494a1.png)
.

**Comment by brettz9** [comment]
Thanks for the clear report. I've fixed those and some other missing/bad links in `master` so if you update and then build again, it should work.

While `svg-editor.js` is indeed the main entry for JavaScript, you really should see `svg-editor-es.html` as a starting point (which gets built into `svg-editor.html`), as there currently is no independent JavaScript module independent of that HTML (see #242). But yes, the primary JavaScript file it includes is indeed `svg-editor.js` (via `/svgedit-config-es.js`). Even if you use the non-ESM version in production, I recommend finding your way around the modules during debugging, both because it avoids a build step during debugging and it is clearer to follow the modules around.

**Comment by subbusgithub** [comment]
Thanks a lot for the direction Brett (hope I got the name right). I have managed to get some idea on how to initialize and add extensions, its a long way to go though. Now I am stuck with the question how do I integrate this with an Angular2 app. That is the task I have been given. How do I initialize and register for events from the svg-editor so that I can trigger the typescripts in my Angular app. I guess for extensions I have to make the corresponding angular component but how to bind the related events? have been looking into the events doc but kinda lost. Any direction would be greatly appreciated. Thanks.

**Comment by brettz9** [comment]
Nice to hear this may go toward a tutorial. I know nothing about Angular, but:

1. `svgEditor.ready` lets you register a callback for when the editor is first ready.
2. `svgEditor.canvas.bind` (if you are in the `svgedit-config-es.js` config file)  or  `this.canvas.bind` (if you are running within an extension's `init` method) lets you bind to other specific events (you can search `svg-editor.js` for `svgCanvas.bind` to see some examples.

**Comment by subbusgithub** [comment]
Hi Brett,
Got back to this project after a few days. Thanks for fixing the issues in the docs. All the links are working fine so far.

**Comment by subbusgithub** [comment]
Hi Brett, A small query, i want to bundle all the js and css files so that I can include it as an external dependency in my app. Is there a recommended way to do this? Right now I am having to include each one of them individually.

**Comment by brettz9** [comment]
You can see how the names are mapped by looking at rollup.config.js (`rollup-config.config.js` is for the config files like `svgedit-config-es.js`). Mostly the renaming is just to indicate the export type (e.g., "iife"), but `svg-editor.js` is indeed renamed to `index-<format>[.min>].js`

Yes, the `dist` files should be sufficient (though if not, feel free to report any issues).

**Comment by subbusgithub** [comment]
Hi Brett, I have tried and used the dist folder, but I am getting this error that I am not able to find a solution for. I have put it on SO in the following link, can you please take a look and respond wherever convenient.
https://stackoverflow.com/questions/62226916/angular-9-uncaught-referenceerror-regeneratorruntime-is-not-defined

Do let me know if you need more info. I have described it wrt Angular but the error isn't related to it . I guess its more of a babel/polyfill issue. Kindly suggest.

**Comment by subbusgithub** [comment]
Hi Brett I think I am doing something silly, bear as I am still new to all this. Will the dist folder be enough as i don't see any html and css files packaged within that folder. So will i have to include the entire svgedit folder for the app to work correctly inside my app, right now i have installed it as a node module using "npm install svgedit" and used only the dist folder to import the js. Guess I am doing it the wrong way. Kindly suggest.

**Comment by brettz9** [comment]
Yes, you need the HTML currently if you are not implementing your own editor. The HTML also shows which files--such as the regenerator runtime--that must be included for use of the full editor.

I am very busy and limited these days, so I'm afraid I cannot help much now. As mentioned on the README, this project is not able to be well-maintained.

**Comment by brettz9** [comment]
The regenerator runtime is a polyfill for the fact that Babel converts `async` functions into a form that older browsers can use. The polyfills may not all be in the `dist`. Just look at the editor and you should be able to figure it out.

**Comment by subbusgithub** [comment]
Hi Brett, sorry for bothering and thanks a lot for taking time out of your tight schedule to reply to the queries, really appreciate it. Once I get a good hands on svgedit, would be more than happy to contribute and join you guys. I truly believe its a project that will help a lot of people as svg graphics are going to be used more and more in the future. Once again thanks a lot for your help :)
