### ISSUE TITLE
SVG Image with negative position values cropped after importing

### ISSUE THREAD

**Issue by subbusgithub** [SVG-Edit/svgedit#414]
Hi I was trying to use the editor and observed the following behavior.

**Steps to reproduce**
1) Click the svg-edit drop down menu on top left
2) Select  "import image" option
3) In the "open file" dialog select an svg file with its position set to negatives (like -50,-50) .
4) It opens the svg file (i guess as an un-editable image) but the negative part of the file are not rendered at all.
5) If you try to move the image only the visible part is moved, (looks like it is cropped)

Whereas, this works fine if you open the file using the "open svg" menu option.

**Expected Behavior**
The image should be visible completely and must be able to be re-positioned.
Or if the "import image" option is not supposed to open svg files, probably the "open dialog" filters must be applied to only allow files other than svg files.

**Comment by cuixiping** [comment]
"Import SVG" has solved this issue.
