### ISSUE TITLE
Shortcuts with imagelib

### ISSUE THREAD

**Issue by EetuHakkinen** [SVG-Edit/svgedit#417]
**Describe the bug**
Keyboard shortcuts does not work after importing image from image library.

**To Reproduce**

1. Go to svgedit menu -> image library
2. Select image library
3. Select image
4. Now keyboard shortcuts is not working
5. When clicking outside drawing area (for example menu bar at the top or layers menu at the right), keyboard shortcuts starts to work again.

SVG-Edit environment (IMPORTANT)

File for SVG-Edit: https://unpkg.com/svgedit@5.1.0/editor/svg-editor.html
Desktop (please complete the following information):

OS: windows10
Browser: Chrome Version 83.0.4103.106 (Official Build) (64-bit)

**Comment by brettz9** [comment]
This seems to be Chrome-specific; I can't replicate on Firefox. The project is not being actively developed, though PRs with tests are welcome.
