### ISSUE TITLE
Measure edge indicators horizontal and vertical not match with the grid

### ISSUE THREAD

**Issue by Gmitry** [SVG-Edit/svgedit#420]
The grid seams correct placed when turned on but the measure indicators at the edges is not corrected calibrated. 

Ver. 5.1.0 2020-06-29

![SVG Edit 2020-06-28 Grid and measure labels not fit](https://user-images.githubusercontent.com/6629596/85971900-9a4d3300-b9f8-11ea-9fff-3a10b1917598.png)
See the screen-capture for more details of the bug:

**Comment by jfhenon** [comment]
Fixed with last build

**Comment by Gmitry** [comment]
> Fixed with last build

Thank you so much you and others doing Open Source are today's heroes will try to contribute even it is nothing compare to all the good work you and others are doing!
