### ISSUE TITLE
How to modify the svg-edit files?

### ISSUE THREAD

**Issue by kurundkar123** [SVG-Edit/svgedit#422]
I am new to this tool and I couldn't find a way to modify the files and like what I want to do is add one export option to convert the svg file into json file. If anyone can help me out with this. Thanking you in advance.

**Comment by brettz9** [comment]
You can take a look at https://github.com/SVG-Edit/svgedit/blob/master/docs/tutorials/ExtensionDocs.md#introduction and in the repository look at the files in `/editor/extensions`.

**Comment by jfhenon** [comment]
We have changed the way to customize with V7. Documentation needs to be updated as well but you should have a look at the extensions folder to have examples on how to write an extension.
