### ISSUE TITLE
Consider hosting the live repo as well as the latest release

### ISSUE THREAD

**Issue by progers** [SVG-Edit/svgedit#43]
https://rawgit.com is a free service by Ryan Grove for serving https requests directly from tip-of-tree. There's no SLA for this service and Ryan could always replace svg-edit with malware, but I think these concerns are pretty minimal for a project like svg-edit.

Here's a demo:
https://rawgit.com/SVG-Edit/svgedit/master/editor/svg-editor.html

Rawgit isn't behind a CDN (but there is a CDNified link with cache:forever set at https://cdn.rawgit.com/SVG-Edit/svgedit/master/editor/svg-editor.html) so we should keep that in mind.

I think it makes sense to add a tip-of-tree link in somewhat smaller text below the latest release. Wdyt?

**Comment by waldyrious** [comment]
I would expect [htmlpreview.github.io](https://htmlpreview.github.io/?https://raw.github.com/SVG-Edit/svgedit/master/editor/svg-editor.html) to work as well, but apparently there are some issues with the external resources. Just dropping the link here for reference.

**Comment by brettz9** [comment]
Rawgit sounds good... Maybe we'll need to commit the config file after all (so that it'll work out of the box without modification) and just let the user configure it.
