### ISSUE TITLE
Need help about `image` tags

### ISSUE THREAD

**Issue by qingxiao** [SVG-Edit/svgedit#431]
version: 6.0.0
There are` image` tags in the editor. In the canvas, operations such as click move will cause the image to be re requested
![image](https://user-images.githubusercontent.com/3422905/91322083-e4347880-e7f1-11ea-8a36-956c3d396e4a.png)

Recurrence steps
> start http-server
> visit `/editor/svg-editor-es.html`
> insert a image
> open chrome devtools
> click svgcanvas or orther

**Comment by jfhenon** [comment]
Hello @qingxiao, I was not able to reproduce your issue with https://svg-edit.github.io/svgedit/src/editor/svg-editor.html which is the last build from master. Can you try to reproduce with this url?

**Comment by qingxiao** [comment]
@jfhenon 我试了下，正常情况下确实是对的，
但是如果图片404，找不到的情况，就会出现这个
![图片](https://user-images.githubusercontent.com/3422905/91665639-ae60fe00-eb29-11ea-9ba9-78fbc7bacd6b.png)

**Comment by jfhenon** [comment]
> @jfhenon 我试了下，正常情况下确实是对的，
> 但是如果图片404，找不到的情况，就会出现这个
> ![图片](https://user-images.githubusercontent.com/3422905/91665639-ae60fe00-eb29-11ea-9ba9-78fbc7bacd6b.png)

Indeed, I can reproduce the bug now if the path does not exist. I will look into this shortly. thank you :-)

**Comment by qingxiao** [comment]
THX

**Comment by AgriyaDev5** [comment]
https://user-images.githubusercontent.com/44435283/125236625-f2a05b80-e301-11eb-88c5-e520a258ced7.mp4
