### ISSUE TITLE
Using Svg-Editor in an Iframe

### ISSUE THREAD

**Issue by kunzef** [SVG-Edit/svgedit#433]
I tried using the Svg-Editor in an iframe like this: 

> <iframe` title="SVG-edit" src="https://svg-edit.github.io/svgedit/src/editor/svg-editor.html?" marginwidth="0" marginheight="0" style="min-width: 800px;" width="100%" height="600" frameborder="0">Your browser does not support IFrames.</iframe> 

The problem is that i can not perform actions such as open anew page or create a square. Also the prompt asking where to store the user preferences and svg-images doesn't show.

In the console the following error is thrown

>DOMException: Blocked a frame with origin "https://svg-edit.github.io" from accessing a cross-origin frame.
>    at _callee$ (https://svg-edit.github.io/svgedit/dist/extensions/ext-storage.js:278:37)
    at tryCatch (https://svg-edit.github.io/svgedit/src/external/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (https://svg-edit.github.io/svgedit/src/external/regenerator-runtime/runtime.js:293:22)
    at Generator.next (https://svg-edit.github.io/svgedit/src/external/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (https://svg-edit.github.io/svgedit/dist/extensions/ext-storage.js:6:26)
    at _next (https://svg-edit.github.io/svgedit/dist/extensions/ext-storage.js:28:11)
    at https://svg-edit.github.io/svgedit/dist/extensions/ext-storage.js:35:9
    at new Promise (<anonymous>)
    at https://svg-edit.github.io/svgedit/dist/extensions/ext-storage.js:24:14
    at Object.langReady (https://svg-edit.github.io/svgedit/dist/extensions/ext-storage.js:436:14)

Im using Chrome version 85

**Comment by jfhenon** [comment]
Your console indicates you are blocked from accessing a cross-origin frame. Can you try running your frame with:
```
<iframe title="SVG-edit" src="https://svg-edit.github.io/svgedit/src/editor/xdomain-svg-editor.html?" marginwidth="0" marginheight="0" style="min-width: 800px;" width="100%" height="600" frameborder="0">Your browser does not support IFrames.</iframe>
```
or 
```
<iframe title="SVG-edit" src="https://svg-edit.github.io/svgedit/src/editor/xdomain-svg-editor-es.html?" marginwidth="0" marginheight="0" style="min-width: 800px;" width="100%" height="600" frameborder="0">Your browser does not support IFrames.</iframe>
```

**Comment by kunzef** [comment]
If I try to run with _xdomain-svg-editor.html?_ my console shows this error

> GET https://svg-edit.github.io/svgedit/src/editor/xdomain-svgedit-config-iife.js net::ERR_ABORTED 404

Trying to run it with _xdomain-svg-editor-es.html?_ gives this error

> Failed to load resource: the server responded with a status of 404 () 




The html of my site is

```
<!DOCTYPE html>
<html>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/3/w3.css">
<body>

<iframe title="SVG-edit" src="https://svg-edit.github.io/svgedit/src/editor/xdomain-svg-editor-es.html?" marginwidth="0" marginheight="0" style="min-width: 800px;" width="100%" height="600" frameborder="0">Your browser does not support IFrames.</iframe>

</body>
</html>`
```

**Comment by jfhenon** [comment]
can you retry now with xdomain-svg-editor-es.html? 
Thank you.

**Comment by kunzef** [comment]
Now the SVG-Editor is visible but now I have the same problem as with the svg-editor.html

I still get this error log

>DOMException: Blocked a frame with origin "https://svg-edit.github.io" from accessing a cross-origin frame.
    at Object.langReady (https://svg-edit.github.io/svgedit/src/editor/extensions/ext-storage.js:169:31)
    at Object.extAdded [as extension_added] (https://svg-edit.github.io/svgedit/src/editor/svg-editor.js:3107:19)
    at call (https://svg-edit.github.io/svgedit/src/svgcanvas/svgcanvas.js:623:22)
    at Object.SvgCanvas.addExtension (https://svg-edit.github.io/svgedit/src/svgcanvas/svgcanvas.js:1193:10)

**Comment by jfhenon** [comment]
This issue is already reported. I suggest you could close your issue and to follow up on #173

Are you able to install svgedit on your web server so you don't need the cross origin limitations of an iframe?

**Comment by kunzef** [comment]
Unfortunately I'm not but nevertheless thanks for your time and help.
