### ISSUE TITLE
Need Help in setScale - Resizing is not working as expected

### ISSUE THREAD

**Issue by jeyalaks** [SVG-Edit/svgedit#434]
**Describe the bug**
Resizing is not working as expected.

**To Reproduce**
1. My shape's size is **8(width) * 9(height)** and Zoom Level is **1**
2. Rotation Angle - **0**
3. After using canvas.setScale method, It returns height: **8.321428298950195**
width: **9.2882080078125**
4. Get the width and height value using **getBBox()** and **getStrokedBBox()** method, both returns same result.

Note: This is a group element.

**Coding**
  const oriEleBox = {
    height: 70
    width: 113.112
    x: 9.639
    y: 15
}

  const svgRoot = canvas.getRootElem()
  const tlist = canvas.getTransformList(curShapeElement)

  const newbox = {
    x: 27.213
    y: 31.108,
    width: 8,
    height: 9
  }

  const sx = newbox.width / oriEleBox.width || 1
  const sy = newbox.height / oriEleBox.height || 1
  const newX = shape.origin.x
  const newY = shape.origin.y

  const translateOrigin = svgRoot.createSVGTransform()
  const scale = svgRoot.createSVGTransform()
  const translateBack = svgRoot.createSVGTransform()

  translateOrigin.setTranslate(-newX, -newY)
  scale.setScale(sx, sy)
  translateBack.setTranslate(newX, newY)
  tlist.appendItem(translateBack)
  tlist.appendItem(scale)
  tlist.appendItem(translateOrigin)

                                  (or)
curShapeElement.setAttribute(
    'transform',
    `translate(${-newX},${-newY}) scale(${sx},${sy}) translate(${newX}, ${newY})`
  )

**Expected behavior**
The shape will be resized with the exact size(8 * 9)
(or)
Do we have any method for resizing the shape like as shape Movement(moveSelected() in svgEditor) and Rotation (rotateSelected() in svgEditor)?

**SVG-Edit environment (IMPORTANT)**
- File for SVG-Edit: -
- Version: -
- Protocol: http

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by jeyalaks** [comment]
Do we have any method for resizing the shape like as shape Movement(moveSelected() in svgEditor) and Rotation (rotateSelected() in svgEditor)?

**Comment by jfhenon** [comment]
Hello @jeyalaks, I'm sorry but I read several times your issue but I don't understand your issue.

**Comment by jeyalaks** [comment]
Hi @jfhenon, Thanks for your valuable reply... Actually, My question is, I am not able to resize the group element. Is it possible?

**Comment by jfhenon** [comment]
Yes, it's possible to resize a group... The user can do it by selecting the group and dragging one of the handle with the mouse. I guess the question was how to do it programmatically. In this case, the best approach would be to look into the svgedit code directly.
