### ISSUE TITLE
Unable to select initial tool via URL parameters

### ISSUE THREAD

**Issue by tbabej** [SVG-Edit/svgedit#438]
The `initTool` setting cannot be set using URL parameters. The problem is reproducible directly on the demo instance, i.e. opening the demo instance using the following link:

https://svg-edit.github.io/svgedit/dist/editor/index.html?initTool=path

one can observe that no tool has been pre-selected on the left toolbar.

**Expected behavior**
The `initTool` setting should be modifiable via GET query paramters. Other settings are respected, i.e. `initStroke[color]=00CC00` sets the fill color to green:

https://svg-edit.github.io/svgedit/dist/editor/index.html?initFill[color]=00CC00

**Comment by AgriyaDev5** [comment]
Params like: ?initStroke[color]=00CC00&initTool=text&initFill[color]=00CC00


![Screenshot at 2021-06-07 11:52:09](https://user-images.githubusercontent.com/44435283/120970009-75287f00-c788-11eb-9f39-4e8f28a6fdca.png)
