### ISSUE TITLE
Vertical resize does not work correctly

### ISSUE THREAD

**Issue by brianbv** [SVG-Edit/svgedit#447]
**Describe the bug**
When resizing objects in the vertical direction, the first resize of the object jumps to an incorrect position. Dragging up sets the top of the bounding box to y:0, dragging down sets the lower edge of the bounding box to y+object height.  After the initial incorrect position, the mouse position is tracked correctly without further jumps.  When the mouse is released and the resize is initiated again, the same results occur.

**To Reproduce**
1. Add a rectangle
2. Drag up or down

**Expected behavior**
The lower or upper edge of the bounding box moves to where the mouse cursor is. 

**SVG-Edit environment (IMPORTANT)**
- https://svg-edit.github.io/svgedit/dist/editor/index.html

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 87, 64 bit

**Comment by jfhenon** [comment]
Hello @brianbv Thank you for your detailed report. We will look into this this week.

**Comment by brianbv** [comment]
@jfhenon Thanks for fixing the bug, it works for me now!  I am interested in helping out on this project.  I could help with refactoring.  I also read some discussion regarding replacing jQuery Mobile with web components.  That sounded like a very good direction to take the project.  Let me know what I can do to help, and if there is  developer discussion list or team chat.

**Comment by jfhenon** [comment]
@brianbv You are more than welcome! At this point, we are working on another fork but I will add a branch very soon (likely this week-end) to this repo. I think we will call the branch "V7 preview" as it will include a lot of changes including some breaking changes on extensions.  My estimate is that we will have it ready for beta around Feb/March 2021.
If you are curious, you may have a quick look at https://github.com/OptimistikSAS/svgedit/tree/seFlyingButton

**Comment by jfhenon** [comment]
and you gave me an idea to start a discussion board on this project: 
https://github.com/SVG-Edit/svgedit/discussions
