### ISSUE TITLE
Demo: SVG source --> "Cancel" not working

### ISSUE THREAD

**Issue by guettli** [SVG-Edit/svgedit#450]
**PLEASE NOTE: This project is not currently being actively developed due to the core developers having moved on, and the only remaining maintainer merely applying occasional minor PRs or tweaks to keep the project alive. While you can file an issue, you should not expect any action, even if we label the issue.**

**Describe the bug**

I tried the demo, and if you click on the "SVG source" icon, I can see the SVG source. But the cancel button is not working. Only "Apply" closes the pop-up window.

I use Chrome on Linux.

**Comment by jfhenon** [comment]
We are reworking the dialogs in the next version. I'm not sure we will have the bandwidth to fix this in this release.
