### ISSUE TITLE
Bezier Curve tool

### ISSUE THREAD

**Issue by Kreijstal** [SVG-Edit/svgedit#467]
Create a bezier pen tool, like in this program
https://s.baku89.com/pentool/
or like papergrapher.
https://w00dn.github.io/papergrapher/

**Comment by jfhenon** [comment]
Hello Kreijstal, I think this is already a feature of SVGedit, mook on the left panel: 
![image](https://user-images.githubusercontent.com/20402845/104159833-55b34300-53f0-11eb-846a-48833ee2b9c5.png)
is this what you're looking for? 
Thanks
JF

**Comment by Kreijstal** [comment]
Ohh, ok
