### ISSUE TITLE
Modularize SVG-edit

### ISSUE THREAD

**Issue by codedread** [SVG-Edit/svgedit#47]
Started refactoring several years ago, but it never completed - most code still sits in svgcanvas.js.  Dependencies and order are still maintained via comments in each file :-/

My thoughts are to use ES6 modules and traceur for this.  I'll try to get a simple module ported over and using it (and update the release instructions).

**Comment by codedread** [comment]
I'm not actually working on this - so if anyone else wants to give it a shot, please feel free!

**Comment by brettz9** [comment]
Hi Jeff (@codedread ) Can I close this in favor of #235 (where I mention ES6 Modules in the title, and also Babel, etc.)?

**Comment by brettz9** [comment]
So ok to close then? Btw, I'm afraid we may be racing against time to migrate the docs from Google code (in case they disable site even further), or do you have all of them saved somewhere?

**Comment by codedread** [comment]
Yes @brettz9, closing this.  Also, feel free yourself to make those decisions :)

**Comment by codedread** [comment]
And no, I don't think I have the docs from Google Code...
