### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by anonimo82** [SVG-Edit/svgedit#470]
## Motivation

I'm asking this because, with JavaScript, SVG could fully replace Flash

## Current behavior

No current support (AFAIK) for animations

## Desired behavior

Animate transformations, eventually following a path, and script animations (like triggering animations on events)

## Alternatives considered

I guess a solution could be to edit the SVG Markup and adding JavaScript and interactivity.

## More info
Now, this shouldn't include a JavaScript editor of any kind, but just GUI for animations (like, in example, a timeline with key-frames) and a way to trigger animations on simple events (like, in example, for onClick event - to obtain this, a feasible solution could be to "tag" animations and call them in response of events)

## Thanks

Thanks in advance for reading and for any help you could provide
Bye, Ivano

**Comment by jfhenon** [comment]
OK, this is actually a significant enhancement that we will not be able to implement in the short term.

For you information, the key reason why Optimistik decided to start helping this community to maintain svgEdit is to offer to our industrial clients a free/open solution to edit SVG graphics representing a part of their manufacturing plant. We have a separate library (called OIMotion) to animate these SVGs based on realtime values. OIMotion us not open source at this time. You may request more details on our website (www.optimistik.io).

**Comment by anonimo82** [comment]
Can't find references to OIMotion at your link.

**Comment by jfhenon** [comment]
Yes, please leave your email on the site so we can discuss the subject.

**Comment by anonimo82** [comment]
Just did it

**Comment by anonimo82** [comment]
Sorry, I'd insist on this: can you add it to V7?
Maybe borrowing code from OIMotion?

**Comment by jfhenon** [comment]
If we add this, it will be on V8, next year.

**Comment by anonimo82** [comment]
Thanks, I greatly appreciate this.

**Comment by jfhenon** [comment]
I close this issue but the subject is discussed there: https://github.com/SVG-Edit/svgedit/discussions/596
