### ISSUE TITLE
Trace Bitmap Image

### ISSUE THREAD

**Issue by anonimo82** [SVG-Edit/svgedit#472]
## Motivation

Trace images to SVG inside SVGEdit

## Current behavior

Nothing applicable

## Desired behavior

Trace images and convert them to SVG elements

## Alternatives considered

Using other/external tools (it's quite a valid alternative, but it would be better to have this builtin)

## Comments and info

Could be obtained at: https://github.com/jankovicsandras/imagetracerjs

## Thanks

Thanks in advance for reading and for any help you could provide
Bye, Ivano

**Comment by jfhenon** [comment]
Hello Ivano, 
Thank you for your suggestion. We have a lot on our plate for a good V7. We could review a PR for this feature but we don't have enough bandwidth now to develop this.
