### ISSUE TITLE
Can't log into IAN library

### ISSUE THREAD

**Issue by idavillc** [SVG-Edit/svgedit#475]
When you click on the image library button and choose the IAN library. The login form does not log you into your IAN account. It just refreshes the page. I tried locally and the demos listed here at github.

I double checked the login credentials and they are correct.

**SVG-Edit environment (IMPORTANT)**

- File for SVG-Edit: ../dist/editor/index.html
- Version: 5.1.0
- Protocol: https
- Browser: Version 87.0.4280.141 (Official Build) (64-bit)

**Comment by AgriyaDev5** [comment]
> Can't log into IAN library

IAN as they changed the API, so we removed IAN option in SVGEdit.
