### ISSUE TITLE
demo, how run it?

### ISSUE THREAD

**Issue by 0xtrzy** [SVG-Edit/svgedit#482]
I'm download file canvas.httml and all js file
This example not working

Can You show how add rectangle, move corner (mouse) and nothing more

**Comment by jfhenon** [comment]
hello, 
assuming you have cloned the repository locally:
`npm i`
`npm run start`

then you should be able to see the demo on url: "http://localhost:8000/demos/canvas.html"

**Comment by RogerHaase** [comment]
With version 7.2.0 installed and starting the server in the clone root,
I had to set the url to:  `http://127.0.0.1:8000/packages/svgcanvas/demos/canvas.html`
