### ISSUE TITLE
Any document for easy customizing buttons and menus?

### ISSUE THREAD

**Issue by geohuz** [SVG-Edit/svgedit#486]
## Alternatives considered

Is there any way for toggling buttons or switching on/off drawing features in svgedit? For example, I would like to tailor it into a simple svg shapes (polygon, circle, rectangle) editor. Is there easy way to do it? Thanks

**Comment by jfhenon** [comment]
Hello, for what you want, I believe the easiest way is to change the svgedit.html file in svgedit version 5 or 6.
