### ISSUE TITLE
Regular Expression DoS vulnerability

### ISSUE THREAD

**Issue by linci8210** [SVG-Edit/svgedit#487]
We are working on the [ReDoS](https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS) problem and detected 4 vulnerable regex(es) from your repository.

1: ``:((?:[\w\u00c0-\uFFFF\-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?`` in svgedit/src/editor/jquery.min.js
2: ``((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^\[\]]*\]|['"][^'"]*['"]|[^\[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)`` in svgedit/src/editor/jquery.min.js
3: ``(%.)|(\*{1,3})((?:%.|.)+?)\2|(`+)((?:%.|.)+?)\4|\[((?:%.|.)+?)\]\(([^\s\)]+)\)`` in svgedit/dist/editor/extensions/ext-mathjax/ext-mathjax.js
4: ``%(\d+|\{\d+\}|\{[a-z]+:\%\d+(?:\|(?:%\{\d+\}|%.|[^\}])*)+\}|.)`` in svgedit/dist/editor/extensions/ext-mathjax/ext-mathjax.js

Please try the following:

	var pattern = ":((?:[\\w\\u00c0-\\uFFFF\\-]|\\\\.)+)(?:\\((['\"]?)((?:\\([^\\)]+\\)|[^\\(\\)]*)+)\\2\\))?";
	var input = ":\\\b(\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b";
	var re = new RegExp(pattern);
	var matched = input.match(re);

	var pattern = "((?:\\((?:\\([^()]+\\)|[^()]+)+\\)|\\[(?:\\[[^\\[\\]]*\\]|['\"][^'\"]*['\"]|[^\\[\\]'\"]+)+\\]|\\\\.|[^ >+~,(\\[\\\\]+)+|[>+~])(\\s*,\\s*)?((?:.|\\r|\\n)*)";
	var input = "[\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b";
	var re = new RegExp(pattern);
	var matched = input.match(re);

	var pattern = "(%.)|(\\*{1,3})((?:%.|.)+?)\\2|(`+)((?:%.|.)+?)\\4|\\[((?:%.|.)+?)\\]\\(([^\\s\\)]+)\\)";
	var input = "*%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b%\b\n";
	var re = new RegExp(pattern);
	var matched = input.match(re);

	var pattern = "%(\\d+|\\{\\d+\\}|\\{[a-z]+:\\%\\d+(?:\\|(?:%\\{\\d+\\}|%.|[^\\}])*)+\\}|.)";
	var input = "%{a:%0||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||\b";
	var re = new RegExp(pattern);
	var matched = input.match(re);

We didn’t create a pull request because we're not sure if these cases are possible to take place in your program, we also do not understand the functionality of these regexes as you do. Thank you for your understanding.

**Comment by jfhenon** [comment]
Hello, we are working on a version 7 that will not use anymore jquery.min.js so the first 3 regex should not be used anymore.
On the last one, we have to look into this.

**Comment by jfhenon** [comment]
due to major upgrade to V7 - older issues/PR are closed.
You can open the same issues or create a PR based on V7
