### ISSUE TITLE
http://myeditor.cool invitation

### ISSUE THREAD

**Issue by sskyy** [SVG-Edit/svgedit#488]
## Motivation

Hello, I'm the author of MyeditorCool. [http://myeditor.cool](http://myeditor.cool) is website reads user's file in github/onedrive/etc. through openapi, and allow user to edit it with any editor published to npm and has 'myeditorcool' field in package.json.

By supporting myeditorcool, svgedit can soon be used by users to edit their own remote svg file online without installing anything!
 
I want to invite svgedit to join myeditorcool, be our recommended editor. Only a few works need to be done, the docs are here: [https://github.com/MyEditorCool/editors/blob/master/DevelopAnEditor.md](https://github.com/MyEditorCool/editors/blob/master/DevelopAnEditor.md). Looking forward your reply.

**Comment by jfhenon** [comment]
Hello Zhen Yu Hou, 
This sound as a nice initiative. We don't have the bandwidth to work on the integration with your site.
Thanks
