### ISSUE TITLE
Several file dependencies are broken while running on dev mode

### ISSUE THREAD

**Issue by mazoqui** [SVG-Edit/svgedit#514]
**PLEASE NOTE: We are trying to make this project live again. While you can file an issue, we will do our best but you should not expect any action, even if we label the issue. However, we are welcoming new contributors **

**Describe the bug**
I can proper run and test svgedit running it locally if I download the the latest release zip file (svgedit-5.1.0) and serve its content on nginx.

But I can not manage to get it to run according to the described quick install

**To Reproduce**

Clone or copy the repository contents
git clone https://github.com/SVG-Edit/svgedit.git
npm i
npm run start

Navigate to http://localhost:8000/src/editor/index.html

**Expected behavior**
Proper rendering of MASTER git release (whish should be the one in production, right)?

I can see what it should be the editor page but not proper rendered - without canvas, toolbar, sidebar and layer panel andplenty of missing js files dependencies logged on the console 

It seems that there are path issues, but also js libs not installed, although the npm i was finished without blockage errors

Just following the quick install in different linux machines and you will get same error.

**SVG-Edit environment (IMPORTANT)**

**Desktop (please complete the following information):**
desktop - linux mint - chrome / firefox

**Comment by jfhenon** [comment]
Hello Marco , 
The master branch is actually a development branch
The branch v.5.1.0 is the latest release.

Now, I need to check the reason why it didn't work on your installation. What is your navigator please?

**Comment by mazoqui** [comment]
Hi jfhenon, thank you for so quick reply.
I'm running on linux the Chrome Version 90.0.4430.212 (Official Build) (64-bit) 

below the installation and running sequence:

![image](https://user-images.githubusercontent.com/3942421/119023594-8005a600-b978-11eb-8229-5c69066be983.png)
![image](https://user-images.githubusercontent.com/3942421/119023289-08377b80-b978-11eb-8403-19c1ba726090.png)
![image](https://user-images.githubusercontent.com/3942421/119023343-1c7b7880-b978-11eb-8e32-4a78b56267ab.png)
![image](https://user-images.githubusercontent.com/3942421/119023883-d8d53e80-b978-11eb-8819-dbb486629eda.png)

It is a bit better after I clean up npm cache, and no errors messages were logged. But I'm still facing  issues on Chrome related to page response.

**Comment by jfhenon** [comment]
do you have messages in the console that could help to understand?

**Comment by mazoqui** [comment]
Thank you once again.

No, no error messages.

Previously (before reinstalling it) error messages were related to the
*pathseg* and *canvg *importation file. Now it is not logging any error
message, but still getting the browser alert while waiting to load it.

I've also tried to run it from nginx instead of the node server, and it
does not seem to work out of the node environment, though.

**Comment by jfhenon** [comment]
I would like you to make 2 tests:
1/ from your browser, try https://svgedit.netlify.app/editor/index.html to see if it works. (I think it will but worth trying)
2/ on your git, type npm -v and node -v
For me: 
![image](https://user-images.githubusercontent.com/20402845/119054352-c3d3cc00-b9c7-11eb-879f-90cf4eed3a44.png)

**Comment by mazoqui** [comment]
HI 
npm version: **6.14.13** / node version: **14.17.0** 
![image](https://user-images.githubusercontent.com/3942421/119062010-1606f400-b9ac-11eb-8efe-657717301adb.png)

**Comment by jfhenon** [comment]
Ok. At least we know the browser is not the issue. One of the developer working with me is on Ubuntu like you. My system is running macOS. I will try to install a fresh new install to see if I have the same problem. 
One test also could be to run the built version (npm run build) and to test the url localhost:8000/dist/editor/index.html  
I will only be able to test this next week.

**Comment by jfhenon** [comment]
I did the test on Ubuntu with a fresh install of node. it worked
![image](https://user-images.githubusercontent.com/20402845/119168513-452b6d00-ba61-11eb-922d-9a05ba24ad3b.png)

**Comment by mazoqui** [comment]
Hi jfhenon,
thank you once again.
It sounds like an issue on webpack-dev-server. In a fresh linux mint installation, after installing latest npm+node version, clone, install and run the dev application, i got same issue again. 
It worked at first, but as soon as I reload the page, it crashes. 
On the network panel I could realise there were several svg resources on pending status. They did never finish. 
I've then reinstalled the webpack-dev-server, but no luck. It just work on first load and as soon as I reload the page, it crashes.
![image](https://user-images.githubusercontent.com/3942421/119208445-985cea00-ba78-11eb-9272-644b5b3e736d.png)
![image](https://user-images.githubusercontent.com/3942421/119208558-25a03e80-ba79-11eb-9b5a-28e61e9e1252.png)
![image](https://user-images.githubusercontent.com/3942421/119208731-dc042380-ba79-11eb-9a01-69902f8e6f1d.png)
Also tried to build and serve it on nginx: the page did not load properly and several missing dependencies were logged.

Since it might be an issue that only me is struggling to deal with, feel free to close it.

Really appreciate all wonderful jod and support from you.

thank you

**Comment by jfhenon** [comment]
The project is not using the webpack-dev-server.
