### ISSUE TITLE
Problem in Loading Svg file

### ISSUE THREAD

**Issue by AzamatIshmuratov** [SVG-Edit/svgedit#520]
I open svg file why black content appears? Thank you.

![image](https://user-images.githubusercontent.com/36133714/119268619-3e415d80-bc0d-11eb-8c33-556ee3ae189b.png)

Actually:

![image](https://user-images.githubusercontent.com/36133714/119268659-587b3b80-bc0d-11eb-9e81-5b92bcac45a3.png)

Fragment:
<g transform="translate(145.5,85.5)" id="page1">
      <g id="tempAIValueBox_ai_Psep" transform="translate(120,120)">
         <g id="g2475-59-3-9-3" style="filter:url(#filter3416-9-32-3-8-9)" transform="translate(-2.5,129.5)">
            <g id="ab">
               <path d="m 41.556,-105.74531 v -35.5 h -20 v 35.5 z" stroke="#868686" id="path2419-9-6-7-5" fill-rule="evenodd" fill="#ff0000" stroke-width="1" />
               <g id="g2425-27-5-6-7" transform="translate(23.140896,-136.34674)">
                  <text class="st2" xml:space="preserve" id="at-8">
                     <tspan y="15.8" x="2.5999999" id="tspan2421-3-2-9-0">HH</tspan>
                  </text>
               </g>
            </g>
            <g id="g5104-4">
               <path d="m 132.556,-120.74531 v -20 l -90.65,-0.5 v 20 z" stroke="#868686" id="path2429-95-8-9-1" fill-rule="evenodd" fill="#000000" stroke-width="0.918503" sodipodi:nodetypes="ccccc" />
               <g transform="translate(55.305744,-139.8)" id="valjytjdfhue-2">
                  <g id="g2435-3-1-6-3" transform="translate(3.02,2.5)">
                     <text class="st3" xml:space="preserve" id="value">
                        <tspan y="12.8" x="16.4" id="tspan2431-8-8-1-8">X.XX</tspan>
                     </text>
                  </g>
               </g>
            </g>
            <g id="g2449-94-0-0-4" transform="translate(35,0.5)">
               <path d="m 149.356,-121.24531 v -20 h -51.8 v 20 z" stroke="#868686" id="path2441-6-2-4-0" fill-rule="evenodd" fill="#ffffff" stroke-width="1.21655" />
               <g id="g2447-7-1-5-7" transform="matrix(1.2845786,0,0,1.4676692,101.51848,-142.62882)">
                  <text class="st4" xml:space="preserve" id="eu">
                     <tspan y="10.4" x="4.6999998" id="tspan2443-5-0-3-2">MUnits</tspan>
                  </text>
               </g>
            </g>
            <g transform="translate(119.556,-143.5)" id="link">
               <g id="g2455-8-9-3-1">
                  <path fill-opacity="0.3" d="M 8,4 C 8,6.2 6.2,8 4,8 1.8,8 0,6.2 0,4 0,1.8 1.8,0 4,0 6.2,0 8,1.8 8,4 Z" filter="url(#filter1)" fill="#000000" id="path2451-2-5-9-4" style="filter:url(#filter1-85-95-8-4-0)" />
                  <path d="M 8,4 C 8,6.2 6.2,8 4,8 1.8,8 0,6.2 0,4 0,1.8 1.8,0 4,0 6.2,0 8,1.8 8,4 Z" stroke="#000000" fill-rule="evenodd" fill="#ff0000" id="path2453-63-5-0-3" />
               </g>
               <g id="g2461-6-8-4-7" transform="translate(1.35,0.81)">
                  <path fill-opacity="0.3" d="M 0,5.3 C 0,5.3 0,0 0,0 H 1.1 V 5.3 H 1.4 V 1.7 H 2.5 V 5.3 H 2.9 V 3.2 H 4 V 5.3 H 4.4 V 4.1 h 1 v 1.2 z" filter="url(#filter1)" fill="#000000" id="path2457-44-2-4-1" style="filter:url(#filter1-85-95-8-4-0)" />
                  <path d="M 0,5.3 C 0,5.3 0,0 0,0 H 1.1 V 5.3 H 1.4 V 1.7 H 2.5 V 5.3 H 2.9 V 3.2 H 4 V 5.3 H 4.4 V 4.1 h 1 v 1.2 z" fill-rule="evenodd" fill="url(#lg1)" id="path2459-52-7-9-7" 
                   
                  />
               </g>
            </g>
            <g id="g2473-8-8-6-4">
               <path d="m 184.556,-104.5 v -16 l -142.7,-0.24531 v 15 z" stroke="#868686" id="path2465-4-7-9-3" fill-rule="evenodd" fill="#ffffff" stroke-width="1" sodipodi:nodetypes="ccccc" />
               <g id="g2471-5-1-6-9" transform="translate(58.355999,-116.8)">
                  <text class="st5" xml:space="preserve" id="dt">
                     <tspan y="7.3000002" x="29.200001" id="tspan2467-63-0-1-6">hh:mm:ss</tspan>
                  </text>
               </g>
            </g>
         </g>
      </g>
   </g>

**Comment by jfhenon** [comment]
Hello @AzamatIshmuratov , can you please review your issue. The SVG is not readable. maybe you could attach the file.
thanks
JF

**Comment by AzamatIshmuratov** [comment]
to -> .svg
[test.txt](https://github.com/SVG-Edit/svgedit/files/6528778/test.txt)

**Comment by AzamatIshmuratov** [comment]
I took a fragment of the group, there is actually a big diagram

**Comment by jfhenon** [comment]
It seems related to one of your filter: filter="url(#filter3416-9-32-3-8-9)"
When I removed it, the display was fine.

**Comment by AzamatIshmuratov** [comment]
Thanks, I look forward to)

**Comment by AzamatIshmuratov** [comment]
By the way, in version 6.1.0 your editor displays correctly

**Comment by AzamatIshmuratov** [comment]
I found what the problem is, but it is not correct as the svg file comes out blurry

![image](https://user-images.githubusercontent.com/36133714/119299919-4cc55e80-bc79-11eb-9533-5dedb83a216b.png)

I commented out:
// 'feFlood': ['flood-color', 'in'],
in massiv svgWhiteList_

But if I uncomment feFlood and comment out the code below in function sanitizeSvg(): 

if (!({}.hasOwnProperty.call(allowedAttrsNS, attrLocalName) &&
        attrNsURI === allowedAttrsNS[attrLocalName] && attrNsURI !== NS.XMLNS
      ) &&
        !(attrNsURI === NS.XMLNS && REVERSE_NS[attr.value])) {
        // TODO(codedread): Programmatically add the se: attributes to the NS-aware whitelist.
        // Bypassing the whitelist to allow se: prefixes.
        // Is there a more appropriate way to do this?
        if (attrName.startsWith('se:') || attrName.startsWith('data-')) {
          seAttrs.push([attrName, attr.value]);
        }
        node.removeAttributeNS(attrNsURI, attrLocalName);
      }

=> I get correct svg, but then errors when saving:
![image](https://user-images.githubusercontent.com/36133714/119300572-69ae6180-bc7a-11eb-93eb-bdb5cdf819c1.png)

![image](https://user-images.githubusercontent.com/36133714/119300465-3ec40d80-bc7a-11eb-8e0f-6659d4c2dc7c.png)

Thanks!

**Comment by jfhenon** [comment]
Can you test with the latest version in master and let me know if this works for you?

**Comment by AzamatIshmuratov** [comment]
I add element "in" (maybe it is a custom attribute) in massive feComposite [svgWhiteList_]:
'feComposite': ['operator', 'result', 'in2', **'in'**],

now, I get 
![image](https://user-images.githubusercontent.com/36133714/119325112-fcaac400-bc99-11eb-8bd2-c1d9ab74bde0.png)

This is normal, but the shadow is darker than in the original:
![image](https://user-images.githubusercontent.com/36133714/119325277-2bc13580-bc9a-11eb-89d7-66ea88bea788.png)

I continue my research)

**Comment by AzamatIshmuratov** [comment]
Sorry, I add 'flood-opacity' in feFlood. Now it works correctly. Thanks for your quick feedback. I have never met such responsive people. Sorry for my bad English
