### ISSUE TITLE
Menu ... SVG-Edit ... SVG-edit home page should point to Github repository

### ISSUE THREAD

**Issue by coevolving** [SVG-Edit/svgedit#53]
Launching https://github.com/SVG-Edit/svgedit "Try SVG-edit here" works fine.  When I select from the menu to "SVG-edit Home Page", I get redirected to https://code.google.com/p/svg-edit/ which has directions to go to https://github.com/SVG-Edit/svgedit.

Should that pointer to Google Code be removed?

**Comment by codedread** [comment]
Yes - feel free to send a patch to point it to the github page :)

**Comment by codedread** [comment]
er, pull request :)

**Comment by brettz9** [comment]
This is already in `master` so closing out. Thanks for the report!
