### ISSUE TITLE
Undo/Redo

### ISSUE THREAD

**Issue by AzamatIshmuratov** [SVG-Edit/svgedit#543]
Hello again! 

I download some svg:
[test.txt](https://github.com/SVG-Edit/svgedit/files/6536300/test.txt)

I get 
![image](https://user-images.githubusercontent.com/36133714/119436531-c6bb1d80-bd35-11eb-97ce-480e8afbb46d.png)

But if i move and do "Undo":
![image](https://user-images.githubusercontent.com/36133714/119436638-f8cc7f80-bd35-11eb-9bd9-40ff68a778ea.png)

tspan's remain in place. What could be the cause of this problem?

**Comment by AzamatIshmuratov** [comment]
Maybe you need to process it as in this fragment? 

if (selected.tagName === 'text') {
        const children = selected.childNodes;
        let c = children.length;
        while (c--) {
          const child = children.item(c);
          if (child.tagName === 'tspan') {
            const tspanChanges = {
              x: $(child).attr('x') || 0,
              y: $(child).attr('y') || 0
            };
            remapElement(child, tspanChanges, m);
          }
        }
      }

In this case, the problem lies precisely in _**tspan**_

**Comment by jfhenon** [comment]
I  could reproduce the issue with a smaller svg:
```
<svg width="1290" height="810" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg" version="1.1">
 <!-- Created with SVG-edit - https://github.com/SVG-Edit/svgedit-->
 <g class="layer">
  <title>Layer 1</title>
  <g id="svg_7">
   <rect fill="#FF0000" height="40" id="svg_3" stroke="#000000" stroke-width="5" width="87" x="307" y="249"/>
   <text fill="#000000" id="svg_1" x="292" y="265">
    <tspan id="svg_2" x="321.2" y="272.3">hh:mm:ss</tspan>
   </text>
   <rect fill="#FF0000" height="0" id="svg_4" stroke="#000000" stroke-width="5" width="0" x="356" y="264"/>
   <rect fill="#FF0000" height="0" id="svg_5" stroke="#000000" stroke-width="5" width="0" x="337" y="270"/>
  </g>
 </g>
</svg>
```

if you move the group and try to undo the move, the text does not undo correctly.
This issue also exists in 5.1.0 and that's not good news...

**Comment by AzamatIshmuratov** [comment]
I will try to find the problem. Can you give direction, which script or method to watch? As I understand it, the tspan is not registered in history exactly when we do **undo/redo**, but when we just move the element, it works correctly.
P.S. If I succeed, I will definitely share

**Comment by AzamatIshmuratov** [comment]
In general, I figured out the code. In method handleHistoryEvent() (UndoManager) in the condition:

if (cmdType == ChangeElementCommand.type())

I added this code: 
 
   if (cmd.elem.tagName === 'text'){
            let [dx, dy] = [cmd.newValues.x - cmd.oldValues.x, 
                            cmd.newValues.y - cmd.oldValues.y];
            
            let tspans = cmd.elem.children;

            for (let i = 0; i < tspans.length; i++){
              let x = +tspans[i].getAttribute('x');
              let y = +tspans[i].getAttribute('y');

              let unapply = eventType === 'after_unapply';
              x = unapply? x - dx: x + dx;  
              y = unapply? y - dy: y + dy; 
              
              tspans[i].setAttribute('x', x); 
              tspans[i].setAttribute('y', y); 
            }
          }

**In general, it is working out normally now**

**Comment by jfhenon** [comment]
Thank you very much for your research. I will look into this later today. You can also add a PR.

**Comment by jfhenon** [comment]
Can you check branch https://github.com/SVG-Edit/svgedit/tree/undo-with-tspan-%23543 ? 
Thanks

**Comment by AzamatIshmuratov** [comment]
You added the code in the correct place, but it does not work correctly in the editor: 
https://svgedit.netlify.app/editor/index.html

**Comment by AgriyaDev5** [comment]
https://user-images.githubusercontent.com/44435283/125238008-385e2380-e304-11eb-94a1-d05c5ebf0aa6.mp4
