### ISSUE TITLE
getBlur() - new

### ISSUE THREAD

**Issue by AzamatIshmuratov** [SVG-Edit/svgedit#546]
Sorry! I tried to ungroup an item from multiple items, it doesn't work correctly:

![image](https://user-images.githubusercontent.com/36133714/119485170-33eba480-bd70-11eb-8430-006e0abe3cb6.png)

The second one disappears
![image](https://user-images.githubusercontent.com/36133714/119485068-161e3f80-bd70-11eb-814d-a15d5eea7432.png)

svg:
[test.txt](https://github.com/SVG-Edit/svgedit/files/6538623/test.txt)

**Comment by AzamatIshmuratov** [comment]
I commented out this piece of code in pushGroupProperty(). 

// if (gattrs.filter) {
      //   var cblur = svgCanvas.getBlur(elem);
      //   var orig_cblur = cblur;
      //   if (!gblur) gblur = svgCanvas.getBlur(g);
      //   if (cblur) {
      //     // Is this formula correct?
      //     cblur = (gblur - 0) + (cblur - 0);
      //   } else if (cblur === 0) {
      //     cblur = gblur;
      //   }

      //   // If child has no current filter, get group's filter or clone it.
      //   if (!orig_cblur) {
      //     // Set group's filter to use first child's ID
      //     if (!gfilter) {
      //       gfilter = getRefElem(gattrs.filter);
      //     } else {
      //       // Clone the group's filter
      //       gfilter = copyElem(gfilter);
      //       findDefs().appendChild(gfilter);
      //     }
      //   } else {
      //     gfilter = getRefElem(elem.getAttribute('filter'));
      //   }

      //   // Change this in future for different filters
      //   var suffix = (gfilter.firstChild.tagName === 'feGaussianBlur') ? 'blur' : 'filter';
      //   gfilter.id = elem.id + '_' + suffix;
      //   changeSelectedAttribute('filter', 'url(#' + gfilter.id + ')', [elem]);

      //   // Update blur value 
      //   if (cblur) {
      //     changeSelectedAttribute('stdDeviation', cblur, [gfilter.firstChild]);
      //     canvas.setBlurOffsets(gfilter, cblur);
      //   }
      // }

Now it works correctly, but I don’t know if it’s correct.

**Comment by jfhenon** [comment]
I  could reproduce the issue with a smaller svg:
```
<svg width="1290" height="810" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg" version="1.1">
 <!-- Created with SVG-edit - https://github.com/SVG-Edit/svgedit-->
 <g class="layer">
  <title>Layer 1</title>
  <g id="svg_7">
   <rect fill="#FF0000" height="40" id="svg_3" stroke="#000000" stroke-width="5" width="87" x="307" y="249"/>
   <text fill="#000000" id="svg_1" x="292" y="265">
    <tspan id="svg_2" x="321.2" y="272.3">hh:mm:ss</tspan>
   </text>
   <rect fill="#FF0000" height="0" id="svg_4" stroke="#000000" stroke-width="5" width="0" x="356" y="264"/>
   <rect fill="#FF0000" height="0" id="svg_5" stroke="#000000" stroke-width="5" width="0" x="337" y="270"/>
  </g>
 </g>
</svg>
```

if you move the group and try to undo the move, the text does not undo correctly.

**Comment by AgriyaDev5** [comment]
URL: https://svgedit.netlify.app/editor/index.html

Try this file: [test_modify.txt](https://github.com/SVG-Edit/svgedit/files/6621716/test_modify.txt)

**Comment by AzamatIshmuratov** [comment]
This works for the given example. Was the svg file the problem?

**Comment by jfhenon** [comment]
I think changing the SVG is a temporary workaround but the issue is still not fixed.

**Comment by AgriyaDev5** [comment]
https://user-images.githubusercontent.com/44435283/125235521-385c2480-e300-11eb-824c-256cea89f0c4.mp4
