### ISSUE TITLE
Multiselect bug in firefox (with zoom)

### ISSUE THREAD

**Issue by StalderT** [SVG-Edit/svgedit#55]
Hello,

With current master branch, selecting multiples element in firefox with zoom don't work.

Step to reproduce : 

1) Draw 2 circles. Then select "Select Tool" and try to select the 2 circles.

Works fine : 
![f1](https://cloud.githubusercontent.com/assets/13799456/12372624/2009c8ce-bc5f-11e5-837d-2d300e93d3e2.gif)

2) Change zoom. Then select "Select Tool" and try to select the 2 circles.

it doesn't work :

![f2](https://cloud.githubusercontent.com/assets/13799456/12372628/33c9ad2a-bc5f-11e5-8c26-6e6d5f9ddfc3.gif)
![f3](https://cloud.githubusercontent.com/assets/13799456/12372629/35ea9588-bc5f-11e5-9b21-868f19b8fbf4.gif)

I don't know why but works with compiled version 2.8.1 and don't works with non-compiled version

Regards,

**Comment by StalderT** [comment]
After verification, I think that file svgedit.compiled.js in https://github.com/SVG-Edit/svgedit/releases/download/svg-edit-2.8.1/svg-edit-2.8.1.zip are not the good file. It is the same file that the file included in https://github.com/SVG-Edit/svgedit/releases/download/svg-edit-2.8/svg-edit-2.8.zip.

Bests regards

**Comment by sjernigan** [comment]
I can reproduce this in current Chrome (73).  Basically the selection doesn't seem to account for the zoom level.

**Comment by brettz9** [comment]
Actually, @sjernigan, I hesitate to reopen this as it was for Firefox specifically--could you reopen for Chrome, referencing this issue?
