### ISSUE TITLE
Gradient

### ISSUE THREAD

**Issue by AzamatIshmuratov** [SVG-Edit/svgedit#561]
I open svg, gradients are not working correctly:
In original:
![image](https://user-images.githubusercontent.com/36133714/120587684-42604d00-c44f-11eb-91a5-079c0445173b.png)

Actually:
![image](https://user-images.githubusercontent.com/36133714/120587477-e3023d00-c44e-11eb-8ccc-145a0d709dca.png)

Svg:
[Oil_tank_massomer.txt](https://github.com/SVG-Edit/svgedit/files/6588967/Oil_tank_massomer.txt)

**Comment by AzamatIshmuratov** [comment]
I looked at the original code (opened in a browser) and the code from the editor. Editor removes gradientTransform attribute from linearGradient

**Comment by AzamatIshmuratov** [comment]
Can you give a direction, where to look for an error, maybe I will succeed

**Comment by jfhenon** [comment]
Maybe the first thing you could do is to isolate the part of your svg causing the issue. It would be easier to reproduce and identify the issue.

**Comment by AzamatIshmuratov** [comment]
I need to observe that other parts have not changed during the editing process

**Comment by AgriyaDev5** [comment]
> Can you give a direction, where to look for an error, maybe I will succeed

`<linearGradient inkscape:collect="always" xlink:href="#SVGID_1_-7" id="linearGradient2868" gradientUnits="userSpaceOnUse" gradientTransform="matrix(0.15833324,0,0,1.1666665,137.00002,-295.0264)" x1="59.9995" y1="-0.0361" x2="59.9995" y2="11.9639" />`

File name: src/svgcanvas/svg-exec.js
method: convertGradientsMethod

gradientTransform convert to objectBoundingBox and gradientTransform attribute.  this problem occur.

**Comment by jfhenon** [comment]
fixed
