### ISSUE TITLE
Path mode regression

### ISSUE THREAD

**Issue by jfhenon** [SVG-Edit/svgedit#584]
with version 5.1.0, the select button changes when working on a path as below.

https://user-images.githubusercontent.com/20402845/121500493-a4d0c480-c9de-11eb-84ed-3f4adb7b5f68.mov

This does not work on v7.

**Comment by AgriyaDev5** [comment]
https://user-images.githubusercontent.com/44435283/125234783-026a7080-e2ff-11eb-99c3-52829b632a94.mp4
