### ISSUE TITLE
SVG paths were not converted correctly

### ISSUE THREAD

**Issue by bayegy** [SVG-Edit/svgedit#587]
https://github.com/SVG-Edit/svgedit/blob/1897e2e0ffc09fc4c4525b05f650ff5f004778b3/src/svgcanvas/path-actions.js#L114-L133

As the code shows, at case 10 (absolute elliptical arc (A)), it will continue to execute the code block at case 19, which appearently does not handle the attributes r1, r2, angle, largeArcFlag and sweepFlag. This issue will finally lead to the data missing of absolute elliptical arc (A)

**Comment by bluetwelve** [comment]
Drawing a circle or ellipse and selecting "convert to path" illustrates this.

**Comment by bluetwelve** [comment]
The following circle in svg-edit v5.1: 

<circle cx="30" cy="30" fill="#FF0000" id="svg_1" r="30" stroke="#000000" stroke-dasharray="null" stroke-linecap="null" stroke-linejoin="null" stroke-width="0"/>

converts to path :

<path d="m0,30c0,-16.574586 13.425414,-30 30,-30c16.574586,0 30,13.425414 30,30c0,16.574586 -13.425414,30 -30,30c-16.574586,0 -30,-13.425414 -30,-30z" fill="#FF0000" id="svg_1" stroke="#000000" stroke-dasharray="null" stroke-linecap="null" stroke-linejoin="null" stroke-width="0"/>

In v7 this is not working.

**Comment by bluetwelve** [comment]
I was able to fix this (for circles) by forcing cx, cy, rx and ry to be handled as numbers, where call like:

`const` cx = elem.getAttribute('cx');

are returning strings

**Comment by jfhenon** [comment]
fix with #630
