### ISSUE TITLE
Undo Redo Key Binding

### ISSUE THREAD

**Issue by GoTeamScotch** [SVG-Edit/svgedit#59]
Issue: The keypresses "Z" and "Y" trigger undo/redo respectively BUT Z is also tied to Zoom, so while pressing Z you get both actions (undo & zoom) triggered. So, when you go to hit the zoom key, your last action is undone! 

I fixed this issue by changing this:

```
{sel:'#tool_undo', fn: clickUndo, evt: 'click', key: ['Z', true]},
{sel:'#tool_redo', fn: clickRedo, evt: 'click', key: ['Y', true]},
```

To

```
{sel:'#tool_undo', fn: clickUndo, evt: 'click'},
{sel:'#tool_redo', fn: clickRedo, evt: 'click'},
```

Found in svg-editor.js around line 4020 (when not using compiled assets).

Undo / Redo can still be triggered by pressing [modKey] + Z or [modKey] + Y respectively so you're not losing anything with this change.

**Comment by codedread** [comment]
Can you send a pull request?

**Comment by GoTeamScotch** [comment]
Done.

**Comment by brettz9** [comment]
Looks like this can be safely closed with the PR having been merged... Feel free to comment if otherwise...
