### ISSUE TITLE
How to call a python script from svgedit?

### ISSUE THREAD

**Issue by michaelliesenberg** [SVG-Edit/svgedit#597]
Hi,

i whish to call a custom python script from svgedit. 
I tried serveral approaches and i couldnt do it. I post my question in stackoverflow maybe someone can answer there:
https://stackoverflow.com/questions/68452563/svg-edit-call-python-script

Adding a way to call a custom pyhton script would be a nice thing to have

Best regards,

Michael

**Comment by jfhenon** [comment]
Hello Michael,
We don't plan such feature in the near term. 
Thank you
JF
