### ISSUE TITLE
TopPanel x,y and dimension for element, doesn't work

### ISSUE THREAD

**Issue by faselunare** [SVG-Edit/svgedit#599]
**PLEASE NOTE: We are trying to make this project live again. While you can file an issue, we will do our best but you should not expect any action, even if we label the issue. However, we are welcoming new contributors **

**Describe the bug**
I draw a rectangle (or another shape)
I try to change the positioning from the toolbar at the top but if I manually enter the coordinates or the dimensions, it doesn't work and the numbers acquire inconsistent values. If I change the value in the boxes with the arrows, it seems to work.

**To Reproduce**
1. Go to https://svgedit.netlify.app/editor/index.html
2. Click on the Rectangle tool on the left toolbar
3. Draw a rectangle
4. Select the rectangle
5. Try to change position and dimension by entering the numbers manually in the top toolbar input field

**Expected behavior**
If i put X = 0 I expect to see the rectangle positioned all the way to the left once I have given enter or tab
the same for Y, Width and Height

**SVG-Edit environment (IMPORTANT)**
- File for SVG-Edit: /editor/index.html
- Version: 7
- Protocol: https://

**Desktop (please complete the following information):**
 - OS: Linux Opensuse
 - Browser: Firefox 
 - Version 89.0.2 (64-bit)

**Comment by AgriyaDev5** [comment]
https://user-images.githubusercontent.com/44435283/129593217-b65a3211-9a2e-440e-ac35-6949f4a5906f.mp4

PR: https://github.com/SVG-Edit/svgedit/pull/611
