### ISSUE TITLE
Save images directly to native file system

### ISSUE THREAD

**Issue by codedread** [SVG-Edit/svgedit#603]
## Motivation

With the [Native File System API](https://wicg.github.io/file-system-access/) (now implemented in Chromium-based browsers), it is possible to open and save files directly to the native file system. This would allow SVG-edit to have a much better edit-save cycle, like any desktop editor.

## Current behavior

Clicking SVG-edit > Save Image results in a file called "icon (x).svg" downloaded to my computer.
Clicking it again results in a file called "icon (x+1).svg" being downloaded to my computer.

## Desired behavior

Clicking SVG-edit > Save Image should result in the file that I opened natively to be saved to my file system.
Note that for files not originally opened from the native file system, you will have to ask the user where they would like to save the file.

Steps to implement:

1) Start using ```await window.showOpenFilePicker()``` if it's supported by the browser, instead of the standard <input type="file"> mechanism. Remember the file handle.

2) On saving, if a file handle exists, for this image, then upon Save, attempt to create a writable stream from it:

```
        const writableStream = await fileHandle.createWritable();
        writableStream.write(someArrayBuffer);
        writableStream.close();
```

On first save, this will ask the user for permissions for the browser to save the file. Subsequent saves in that session will work just like any other editor.

**Comment by jfhenon** [comment]
@codedread I did a quick test in the branch https://github.com/SVG-Edit/svgedit/tree/test-native-file-api
This is working very well. 
Things to watch:
- When you refresh the page, the filehandle is lost (needs to be saved) 
- We need a "save as..." option to be consistent
- Safari does not support this API for now (but we could use https://github.com/GoogleChromeLabs/browser-fs-access that proposes a fallback when the API is not supported). 

Thank you for the suggestion. I wish to include this in V7 definitely.

**Comment by jfhenon** [comment]
You can try the branch on https://6103c9c465f45d0008665207--svgedit.netlify.app/editor/index.html

**Comment by codedread** [comment]
I tested this out... Very cool!  Couple notes:

- Now that this works, maybe it is not a great idea to bring up the last-saved image. Blank canvas upon refresh now?
- Yes, I think Save As needs to be there, as well as Save working like Save As for a new image created from scratch. I think [showSaveFilePicker()](https://wicg.github.io/file-system-access/#api-showsavefilepicker) is your friend (I haven't used this myself in my own projects yet).
- In terms of other browsers not supporting this, I think the feature needs to be implemented with "progressive enhancement" in mind - browsers will be incentivized to implement this API if more web developers show an interest in it.
- This API also comes with a [showDirectoryPicker()](https://wicg.github.io/file-system-access/#api-showdirectorypicker) which gives the web app access to all files/sub-directories in that directory - not sure what to do with that for SVG-Edit, but something to keep in mind. :-)

**Comment by rleddy** [comment]
In uploading and downloading audio data on one of my pages, I have used the InexedDB for storage and refresh. (this is actually a vanilla component that is lazy loaded onto a page.) {Also, some pages still being pulled back out after taking stuff down form last summer if you happen to find my website. www.copious.world} 

So, once the audio is save and wave forms have been edited, data is in the IndexedDB. From there I can just use a data URL. I believe that is an old way. The new API sounds promising. 

But, the components can just grab state from the DB.

**Comment by rleddy** [comment]
Another thing I have done recently is to store files in IPFS. So, far I have used a web server to accept data. IPFS in the browser has been tricky. I am not sure they got it just right. They require WebRTC signalling. But, I think that has to do with having the browser be a full node. 

I believe there is progress that can be made in just preparing hashes and storage formats and using a peer swam based on websockets, which might also serve MQTT. The swarm can forward content, and the browser can manage some storage for the swarm.  But even with huge space now taken by browsers for local storage, having the browser dedicate P2P space is a little tough on resources.

**Comment by jfhenon** [comment]
We will look into the native file system approach in V7. I think we will make it our standard approach and keep the old way as a plugin to be used for old browsers. However, I want also to test out the GoogleChromeLabs/browser-fs-access library if this helps to include Safari in the supported browsers. 
More and more, we will use modern approach in svgedit that may limit old browser support but offer a much better user experience. Obviously, we will keep older version of svgedit available for old browsers.
