### ISSUE TITLE
svg templates not loading properly 

### ISSUE THREAD

**Issue by rahulss14** [SVG-Edit/svgedit#609]
Tried loading svg templates built using photoshop or canva but it does not load correctly

**Comment by jfhenon** [comment]
Hello, 
Can you please provide an example and provide the version of SVGEdit?

**Comment by rahulss14** [comment]
Tried loading this svg :
<img width="941" alt="Screenshot 2021-08-17 at 3 11 50 AM" src="https://user-images.githubusercontent.com/45919225/129633100-952e6166-1396-48be-814c-db7280cd0cab.png">



Result : 
<img width="1427" alt="Screenshot 2021-08-17 at 3 11 03 AM" src="https://user-images.githubusercontent.com/45919225/129633126-a17d7f7a-3d32-4c6a-9e6a-d8d74d99a8a9.png">

I have used the latest version of SVGEdit .

**Comment by jfhenon** [comment]
the attached file has a PNG format. can you submit the SVG file?
thanks

**Comment by rahulss14** [comment]
I can not attach the SVG file here , that's why I shared the png file . Shall I mail you the SVG file ?

**Comment by jfhenon** [comment]
You could rename your file as .txt or zip it.
JF

**Comment by rahulss14** [comment]
[17 dapper- hindi.svg.zip](https://github.com/SVG-Edit/svgedit/files/7001121/17.dapper-.hindi.svg.zip)


Thanks !

**Comment by jfhenon** [comment]
it was an issue with the whitelist "symbol". now your svg displays like below: 
![image](https://user-images.githubusercontent.com/20402845/129801934-7f3732a7-f7fc-4075-9900-965b501732e5.png)
This will soon be available on master.

**Comment by jfhenon** [comment]
fixed by #615

**Comment by rahulss14** [comment]
Thank you so much !

Now I am able to import the svg , but cannot edit it .
