### ISSUE TITLE
Save crashes w/ext-server_opensave.js

### ISSUE THREAD

**Issue by bsculley** [SVG-Edit/svgedit#61]
I'm running SVG-Edit locally.  Previously the Save function did nothing, so I added ext-server_opensave.js to the extensions list.  Now the app crashes on a bad memory access when Save is pressed.  I'm running IE10 on Windows 7.

**Comment by GoTeamScotch** [comment]
Isn't the script you're trying to load just supposed to be used as a base for writing your own extension?

**Comment by brettz9** [comment]
That extension depends on fileopen.php and filesave.php (and a server configured for PHP)...

Do you have them so configured? If so, have you tried logging within the PHP files to isolate the problem?

**Comment by brettz9** [comment]
Closing due to lack of response. Feel free to reopen/comment further if you can provide an example/some steps to reproduce against the latest pre-release: https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/editor/svg-editor.html
