### ISSUE TITLE
Cannot edit SVG

### ISSUE THREAD

**Issue by rahulss14** [SVG-Edit/svgedit#618]
I am now able to import a SVG but cannot edit it . Can you help me resolve this .

**Comment by jfhenon** [comment]
can you be a little more precise on what was the issue?

**Comment by rahulss14** [comment]
I have some svgs created using photoshop / canva . When I open the svg in SVGEdit , I am not able to edit the svg .

Attached SVG:
[21 elegant- hindi.svg.zip](https://github.com/SVG-Edit/svgedit/files/7079626/21.elegant-.hindi.svg.zip)

**Comment by AgriyaDev5** [comment]
@rahulss14 

click  ![SVG-edit](https://user-images.githubusercontent.com/44435283/135089942-102cdd0e-0de5-4e9b-8ae3-3a4efc0884b3.png) `Edit source` to load your svg file content, you are able to edit the SVG.
