### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by jeremiebeve59** [SVG-Edit/svgedit#625]
Hello,

Is there a version of SVG-edit and a browser associated (a couple version-browser), supported for a mobile utilisation (responsive design) ? (Android based plateform)
I have tried edge,chrome,opera,firefox and it doesn't work.

An old version could bé ok for my utilisation.

Thank you,

Regards

Jérémie

**Comment by jfhenon** [comment]
which version did you try?

**Comment by jeremiebeve59** [comment]
Hello !

I have tried multiple versions, like ; 7.0 (last), 5.1.0, 6.1.0 and my version : 5.0.0

And it is impossible to create just a rectangle ...

Thanks for your response in advance ;)

Regards

**Comment by jfhenon** [comment]
Indeed, it does not work :-( . 
We didn't really focus on the responsive side until now but clearly we should improve this.

**Comment by jeremiebeve59** [comment]
Ok, thanks for your answer :)

Just tell me if this is improved ;)

Regards

**Comment by jfhenon** [comment]
@t00 I made an update to the PR #634 to test mobile browsers. You can run it thanks to netlify with https://deploy-preview-634--svgedit.netlify.app/editor/index.html
Let me know if this is enough for your use.

**Comment by jeremiebeve59** [comment]
That's nice. Thanks JFH !

But I think this IS not enough for me to build svg Map. I draw 2D map of
houses (floor by floor)

We should be able to easily draw walls, faster. It is inappropriate i think
for now

But everything except that IS ok...
If you have a solution ?! It could be nice

Thanks

**Comment by jfhenon** [comment]
That was also my impression as well. It's possible to make it "work" with touch devices but the reality is that much more work would be needed to really take advantage of these devices (pinch&zoom, force touch, etc...).
I propose to merge this PR so at least we have a first level of support but I keep this issue open.
To be able to work on "easily draw walls", I would appreciate if you can detail what would be needed in svgEdit.

**Comment by t00** [comment]
@jfhenon that is a resounding yes, I tried a few shapes and it just works!
