### ISSUE TITLE
"convert to path" does not work for circle or ellipse

### ISSUE THREAD

**Issue by bluetwelve** [SVG-Edit/svgedit#629]
Create a circle or ellipse in your svg. Select it and click on "Convert to path". You should see the same shape but drawn as a path. Instead, we get a giant shape that is obviously wrong.

I was able to fix this (for circles) by forcing cx, cy, rx and ry to be handled as numbers in svgcanvas\utilities.js getPathDFromElement() function, where calls like:

const cx = elem.getAttribute('cx');

are returning strings.

**Comment by bluetwelve** [comment]
I thought at first this was connected to the arc issue described here: https://github.com/SVG-Edit/svgedit/issues/587 because Inkscape uses arcs when it converts a circle but svg-edit uses bezier curves

**Comment by jfhenon** [comment]
You pointed us in the right direction. I hope this is now fixed with #630. Thanks.

**Comment by bluetwelve** [comment]
Thanks! I knew there were other functions/files that needed this and tests and it looks like you nailed them all... very impressive speed
