### ISSUE TITLE
Changes in SVG spec break SVG-Edit in Chrome 48.

### ISSUE THREAD

**Issue by tangentstorm** [SVG-Edit/svgedit#63]
The SVGPathSeg interface was removed from the SVG specification, and as a result, Chrome no longer supports it, starting with version 48:

https://www.chromestatus.com/feature/5708851034718208

This change renders SVG-Edit completely unusable.

We have been using this nice workaround by @progers at our company:

 https://github.com/progers/pathseg

Just add pathseg.js to your list of includes.

(The better fix is probably to update to the new Paths API he points out in the README there.)

**Comment by codedread** [comment]
Are you saying that even after https://github.com/SVG-Edit/svgedit/pull/20 that the trunk SVG-edit doesn't work?

**Comment by tangentstorm** [comment]
My apologies. We're using an old version where I work, and I had to patch it.

I skimmed the bug list but didn't notice there was already a fix.

(Also, someone mentioned it on the IRC channel earlier today, but I missed them and nobody else responded. I just sort of assumed you guys didn't know. Sorry!)

**Comment by codedread** [comment]
No problem!  :)
