### ISSUE TITLE
control points and handles only display correctly the first time

### ISSUE THREAD

**Issue by bluetwelve** [SVG-Edit/svgedit#637]
Create a circle. Convert it to a path. Click to select the path, then click again. The control points and handles display correctly. Click outside the shape to deselect it, then click to select the path, then click again. The control points and handles should display again but don't. I have to reload the page to get them to display correctly (once)

This is a v7 issue - works fine in earlier versions

**Comment by bluetwelve** [comment]
In path-actions.js, I notice that the second time I try to display the control points with two clicks, select is invoked with the correct target but currentPath  is null. Will try to look at this again tomorrow
  
  /**
    * @param {Element} target
    * @returns {void}
    */
    select (target) {
      editorContext_ = pathActionsContext_.getEditorContext();
      if (currentPath === target) {
        pathActionsMethod.toEditMode(target);
        editorContext_.setCurrentMode('pathedit');
      // going into pathedit mode
      } else {
        currentPath = target;
      }
    },

**Comment by jfhenon** [comment]
Thank you. Ideally you create a PR but if you put us on the right track, we will fix it.

**Comment by bluetwelve** [comment]
Understood. I would like to contribute and if I feel like I am closing in on a PR I will just go for it from now on. In this case I don't understand the flow very well. From the logging I've put in, it looks like behavior is very different the second time I try to expose the control points.

**Comment by bluetwelve** [comment]
Pull request submitted - let me know if there's anything I can do better. I was having a tough time getting git to accept my pull request - seems to not like the personal accesss token it gave me.

**Comment by jfhenon** [comment]
It works well. It seems simple now that you found the issue but it was a tricky one.... 
Thanks!!!
