### ISSUE TITLE
Fullscreen Mode

### ISSUE THREAD

**Issue by GoTeamScotch** [SVG-Edit/svgedit#64]
SVG Edit could use a fullscreen button. I have this working in my development copy of the app, complete with icons as needed. I copied the existing code formatting where possible and put the icon right after the Undo button in the top toolbar.

My question is this: is it ok to include [screenfull](https://github.com/sindresorhus/screenfull.js) in SVG Edit? It's covered under an MIT license.

If this is ok, I can submit a pull request later.

**Comment by codedread** [comment]
I'll be honest, I've forgotten the legalities of SVG-edit... Several of the third-party libraries we use are MIT licensed though, so I think this is ok.

**Comment by GoTeamScotch** [comment]
Ok I will need to fork the repo and put in my edits from a clean copy of the base branch. The copy I have is too modified to upload changes directly.

While I have you, I wanted to discuss the possibility of developing a WordPress plugin based on SVG Edit.
I use SVG Edit in a WordPress plugin I've made and it's customized for my site. My plugin does the following:
- allows WordPress users to upload SVG projects from the editor to WordPress, complete with categories and meta data (date, title, description, etc) which can be referenced later and is visible from WordPress' media library. The addition of a server side image library makes collaborating on images possible and the need of storing SVG files on your computer a thing of the past.
- basic support for WordPress roles and permissions. I.e. some users can import images, some cannot.
- a new theme which is inspired by Photoshop's styles using icons from Font Awesome. The theme basically inverts the lighter styles in the vanilla app to a darker theme and has a monochrome feel.  See GIF here for sample: http://i.imgur.com/RtOfmqD.gif
- custom fonts are available through a modified version of [svg-font-loader](https://github.com/clintberry/svg-font-loader). I plan on adding support for Google fonts so you can just search for fonts and load them right away but there's some obstacles to overcome there.
- downloading jpg/pngs no longer uses a new web browser window showing a base64 decoded image. Putting this long string of text in the address bar and having the browser parse and render the image caused some of my clients' browsers to crash when exporting images so instead it serves them a file to download.
- makes use of current jQuery library. I've been trying here and there on updating other libraries but it's not a big priority right now. I've also been slowly starting to use jQuery UI instead of custom coded elements (like dialog boxes).

My point in saying all this is that I work on SVG Edit regularly because I have clients who use the app regularly. Being an open source developer, I think other folks could benefit from my work as well. I would like to eventually create a fork and publish a publicly available plugin on WordPress.org but my workload doesn't really allow for that right now. Much of what I've done is tailored for a specific set of needs and to make it globally useful would take some effort.

I just wanted to get a conversation going because I feel that SVG Edit is a really powerful graphics editor app that could be very useful to people in the WordPress world. What are your general thoughts on this?

**Comment by belonesox** [comment]
@GoTeamScotch, have you any success with it?

**Comment by locness3** [comment]
@GoTeamScotch ?
