### ISSUE TITLE
Web page won’t responsive on Android touch screen

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [SVG-Edit/svgedit#641]
**PLEASE NOTE: We are trying to make this project live again. While you can file an issue, we will do our best but you should not expect any action, even if we label the issue. However, we are welcoming new contributors **

**Describe the bug**
While I open the V7-preview page from your GitHub repo with Chrome for Android v93, any of buttons can’t responsive on touch screen.

**To Reproduce**
1. Go to your repo
2. Click on Try SVG-edit V7-preview here
3. Press OK button on the dialog for the first time 

**Expected behavior**
Any button should be responsive for touch screen devices, this would give benefits for users who is using Android tablets.

**SVG-Edit environment (IMPORTANT)**
- File for SVG-Edit: [svg-editor.html]
- Version: [e.g. 3.0.0]
- Protocol: [e.g., http, https, file]

**Desktop (please complete the following information):**
 - N/A

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy S6]
 - OS: [Android 7.0]
 - Browser [Chrome]
 - Version [93.0.4577.62]

**Screenshots**

**Log**
If applicable, copy any error logs in your browser console. This can be very
helpful in identifying the problem.

**Additional context**

**Comment by jfhenon** [comment]
We focus now on desktop now but I keep track of this issue.

**Comment by jfhenon** [comment]
duplicate with #625
