### ISSUE TITLE
Layers Panel issues - multiple problems

### ISSUE THREAD

**Issue by bluetwelve** [SVG-Edit/svgedit#644]
I am using Chrome. when Layers Panel is expanded an empty 15 px strip is left on the far right, this causes a horizontal scroll bar to appear and interferes with bottom panel.

**Comment by bluetwelve** [comment]
Pretty sure I have cause and effect backwards. The horizontal scroll bar appears when we open the panel and causes the blank strip.

**Comment by bluetwelve** [comment]
This bug has to do with the overview_window - when the panel is expanded the overview window seems to trigger the scroll bar to appear. If I remove the 15 px left margin on overview_window_content, the horizontal scroll bar is gone but I can still get a vertical scroll bar by hovering over the "Layer 1" text or by opening the layer_moreopts menu.

I can get rid of the scroll bars by disabling them on the svg_editor class (overflow: hidden;) and this works flawlessly but is a change in behavior from earlier versions - I don't think it is an acceptable solution.

Hoping someone else can take a look at this - I think the layers panel needs to be redesigned

**Comment by jfhenon** [comment]
Hello, I'm sorry but I can't really reproduce using your description. Could you add a few screenshots? 
Thanks

**Comment by bluetwelve** [comment]
[scroll.zip](https://github.com/SVG-Edit/svgedit/files/7196206/scroll.zip)

It's very easy to reproduce on chrome, I have reproduced it on several different machines now with the v7 preview. Simply opening the panel causes the horizontal scroll bar to appear. Hovering over the layer label in the list (which causes the label text to turn italicized and blue) causes the vertical scroll bar to appear. Opening that dropdown menu button also does not work correctly.

**Comment by bluetwelve** [comment]
I have tested a potential workaround: if I have a 15px column for the "Panel" label and the panel itself is a 0px column to the right that expands, I can then let overview_window_content (editor\extensions\ext-overview_window\ext-overview_window.js) left margin be zero, which fixes the problems. I think ext-overview_window.js is the root of the issues.

**Comment by jfhenon** [comment]
fixed
