### ISSUE TITLE
Unable to leave popup

### ISSUE THREAD

**Issue by WoolyTheWool** [SVG-Edit/svgedit#645]
In the Web version, I'm unable to press the OK button on the starting popup

**Comment by WoolyTheWool** [comment]
Even worse, I'm not able to do anything

**Comment by jfhenon** [comment]
Could you please precise your environment? If you are using a tablet or an iphone, this is not yet wroking with V7. You may try an earlier version (also accessible from the home page of SVGEdit).
Thanks

**Comment by t00** [comment]
I tried all V7, 6.10 and 5.10 - both android chrome and firefox - latest versions. Welcoming privacy local storage dialog cannot be dismissed - pressing ok/cancel will not work, neither ticking checkbox or tapping dropdown. Likely issue is with z-order or some event sinking overlay - anyone knows anything to try to get pass this dialog?

**Comment by t00** [comment]
![Screenshot_20211010-182922_Firefox](https://user-images.githubusercontent.com/1933165/136706782-5ac9091b-95e5-4b49-85f1-a32b2d1005e3.jpg)
Here is a sample firefox screenshot.

**Comment by t00** [comment]
... and a release 6.10 with chrome, also nothing is clickable.
![Screenshot_20211010-183210_Chrome](https://user-images.githubusercontent.com/1933165/136706880-dddc7874-bb3b-4e7d-ada5-ba81abc5c556.jpg)

**Comment by jfhenon** [comment]
duplicate with #625

**Comment by t00** [comment]
@jfhenon it does not look like a duplicate. Question is on which mobile browsers it works?

**Comment by jfhenon** [comment]
> @jfhenon it does not look like a duplicate. Question is on which mobile browsers it works?

You are right, it is not duplicated but related. Unfortunately no mobile browsers works for now. Web component was used for most dialogs. Unfortunately the function used to convert touch events into desktop events need to be run for every dialogs.
I think we have identified a relatively quick fix but I also wanted to finish another piece of work. Let me reconsider this priority.
