### ISSUE TITLE
Usage of left control panel not obvious

### ISSUE THREAD

**Issue by chessstats** [SVG-Edit/svgedit#65]
It is not obvious that you have to drag the mouse to open context menus on the left vertical control panel. For the first time when you click on Shapes for example, a menu opens up. Next time you have to drag for the same menu to open. There should be a popup that explains this behaviour because it is not a usual GUI behaviour.

**Comment by ibrierley** [comment]
Must admit, this did get me at first too, and still find it a bit unintuitive.

**Comment by GoTeamScotch** [comment]
+1. I feel like the app would benefit from having more and more descriptive tooltips throughout the UI. jQuery Tooltip would be a good solution, although I know the bundled copy of jQuery is a little outdated.

On that note, I recently started using the newest version of jQuery with SVG Edit with no problems so far.

**Comment by jfhenon** [comment]
In V7, when you hover on the "panel' text, you see a link icon. You just need to click to open the panel.
