### ISSUE TITLE
Left tool panel is truncated on Firefox in v7 preview

### ISSUE THREAD

**Issue by benjaminbch** [SVG-Edit/svgedit#654]
**Describe the bug**
Left tool panel is truncated on Firefox in v7 preview

**To Reproduce**
Open svgedit

**SVG-Edit environment**
- Version: v7 preview

**Desktop**
 - OS: MacOS 11 and Windows 10
 - Browser : Firefox
 - Versions : ESR 91, 93.0

**Screenshots**
<img width="454" alt="Capture d’écran 2021-09-29 à 14 14 04" src="https://user-images.githubusercontent.com/63210012/135266448-c9a461ae-5dd8-40a8-8ea4-32130539a62e.png">

**Comment by jfhenon** [comment]
Fixed with last commit (css improved for Firefox)
