### ISSUE TITLE
"add sub-path" tool freezes the UI

### ISSUE THREAD

**Issue by peter-hartmann** [SVG-Edit/svgedit#655]
**Describe the bug**
When using the path tool and right after using the "add sub-path" tool, then the editor seems to freeze.  On completion of the sub-path the editor no longer accepts any input.

**To Reproduce**
1. open the tool - blank page
2. click on "path tool" and draw a path, click the last point twice to complete the path.
3. clock the "add sub-path" tool and draw another path, click the last point twice to complete the path.
4. Observe that the editor no longer accepts any mouse input.

**Expected behavior**
User should be able to draw another sub-path or choose any other tool after completing the first sub-path

**SVG-Edit environment (IMPORTANT)**
Reproduced  here:
- https://unpkg.com/svgedit@5.1.0/editor/svg-editor.html
- using the editor under node-modues

**Desktop (please complete the following information):**
 - Browser chrome

**Smartphone (please complete the following information):**
 - Device: mac
 - OS: big sur 11.6
 - Browser: both chrome and safari
 - Version: svgedit 5.1.0

**Log**
chrome log:
```
svgedit-config-iife.js:6882 Uncaught TypeError: Cannot read properties of undefined (reading 'getCurrentMode')
    at Object.mouseDown (svgedit-config-iife.js:6882)
    at HTMLDivElement.mouseDown (svgedit-config-iife.js:15719)
    at HTMLDivElement.dispatch (jquery.min.js:3)
    at HTMLDivElement.i (jquery.min.js:3)
mouseDown @ svgedit-config-iife.js:6882
mouseDown @ svgedit-config-iife.js:15719
dispatch @ jquery.min.js:3
i @ jquery.min.js:3```

**Comment by peter-hartmann** [comment]
Appears to work fine in version svgedit 7.0.0-beta.6.

**Comment by vfd65536** [comment]
it still happens for me in all of the demo builds, and those are the only ones I can use because my school blocks all *.io domains

**Comment by jfhenon** [comment]
the demo builds are not on .io domains. If you also block .app domaines, it's going to be an issue indeed. You may want to clone the project on a local server. (clone -> npm install -> npm run build)
