### ISSUE TITLE
Path Editing broken

### ISSUE THREAD

**Issue by codedread** [SVG-Edit/svgedit#66]
1) Make a polygon using the path tool
2) Double-click the path so the individual points are selected on the path
3) Try to move a node in the path.

Observed:  The path node tries to move but jitters back to its starting point.  If you double-click the point to turn the segment into a curve, then the path node is movable.  This is a horrible workaround.

**Comment by progers** [comment]
I'm back from vacation again. Were you able to find out what was going wrong?

**Comment by codedread** [comment]
Nope :(

**Comment by magnebra** [comment]
I ended up with this fix/work-around [https://github.com/magnebra/svgedit/commit/933a942303d06a3cfca143ca1566b06fecb345c0] for the time being.

It seems the issue may have originated in this commit [https://github.com/SVG-Edit/svgedit/commit/fbbd740c794e27a384eea0abd7987a1515b0a6b4]

**Comment by progers** [comment]
Thanks magnebra, it looks like you did find the commit that broke this.
Would you be up for reviewing https://github.com/SVG-Edit/svgedit/pull/69 ?
