### ISSUE TITLE
Text does not scale with selection box/cursor in Chrome 96+

### ISSUE THREAD

**Issue by smagnetize** [SVG-Edit/svgedit#660]
**Describe the bug**
Scaling text starting in Chrome 96 breaks (currently Beta). The bounding text contents does not match the selection box and the selection box does not track the cursor.

**To Reproduce**
1. Go to https://svgedit.netlify.app/editor/index.html        (or any version of SVG-Edit)
2. Create text
3. Scale text

**Expected behavior**
It should work like Chrome 95 or Firefox where the text fits selection box.

**SVG-Edit environment**
```svg
<svg width="640" height="480" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
 <!-- Created with SVG-edit - https://github.com/SVG-Edit/svgedit-->
 <g class="layer">
  <title>Layer 1</title>
  <text fill="#000000" font-family="Serif" font-size="24" id="svg_2" stroke="#000000" stroke-width="0" text-anchor="middle" x="109" xml:space="preserve" y="108">test</text>
 </g>
</svg>
```
- Version: 5, 6, 7  (maybe even 3+)

**Desktop:**
 - OS: Windows
 - Browser Chrome
 - Version 96+

**Screenshots**
![svgedit-chrome-96-scale-issue](https://user-images.githubusercontent.com/25177818/139878690-2a27dd45-22a3-4640-81ec-d6c0691f70bd.gif)

**Comment by smagnetize** [comment]
Here's a cypress test that works in Chrome 95 but not 96
https://github.com/smagnetize/svgedit/commit/61ce05599615d1287ec1a6413e264f75326ac24b

**Comment by jfhenon** [comment]
Thank you for the very good description of the issue. Would you attribute this change to a bug in Chrome 96 or on the way we manage the scale of text element?

**Comment by smagnetize** [comment]
I'm sure it's Chrome, I reduced the problem and submitted this:
https://bugs.chromium.org/p/chromium/issues/detail?id=1266389

**Comment by jfhenon** [comment]
I close this as it is related to a Chrome issue. I also had to skip the test as it passed locally but on on the CI.

**Comment by smagnetize** [comment]
It's fixed now in Canary
