### ISSUE TITLE
promp dialog only shows once

### ISSUE THREAD

**Issue by michaelliesenberg** [SVG-Edit/svgedit#669]
Hi,

i am using chrome as browser and notice that once i import svg image the sePrompDialog says "image loading, please wait..." and that is ok but if i do it again the sePrompDialog dialog doenst appear anymore.

Is this a known issue? How can i force it to open again?

**Comment by jfhenon** [comment]
Indeed, we will fix this. Thanks.

**Comment by michaelliesenberg** [comment]
Hi jfhenon,

i can still reproduce the issue if i import the svg image  on the online demo svgedit
Is it working for you?

**Comment by jfhenon** [comment]
Yes it is working for me. see screen recording

https://user-images.githubusercontent.com/20402845/145111674-902b21e7-0a16-4d67-aaec-79a0e7ebae26.mov
