### ISSUE TITLE
Rewrite the zoom selector

### ISSUE THREAD

**Issue by benjaminbch** [SVG-Edit/svgedit#671]
**NOTE:**
This issue is now funded on Bountysource (https://app.bountysource.com/issues/109641308-minor-display-issue-with-zoom-selector)
However, the fix needs to be a **FULL REWRITE** of the zoom selector web component without using the elix library. 
The component source is: src/editor/components/seZoom.js
Native JS, CSS preferred but another library is possible if it is popular and actively maintained.

Obviously, the fix needs to work consistently on Safari, Firefox and Chrome.

**To Reproduce**
1. Open zoom selector

**Expected behavior**
All options must be visible with correct hover

**SVG-Edit environment (IMPORTANT)**
- Version: 7.0.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Firefox
 - Version : 91 ESR

**Screenshots**
![unnamed](https://user-images.githubusercontent.com/63210012/144289018-8d260aaa-0922-415a-973c-f10d1f1aa98c.png)

**Comment by luciozambon** [comment]
The same bug with SVG-Edit environment 
    Version: 7.0.0

Desktop:
    OS: Windows 10
    Browser : Google Chrome
    Version : 97

This bug isn't present on MacOS, both Chrome and Safari

**Comment by pratik2315** [comment]
Hey! Anyone working on this issue? Im interested

**Comment by jfhenon** [comment]
> Hey! Anyone working on this issue? Im interested

I don't think so. You can start on this issue. 
JF

**Comment by radasam** [comment]
Hi, 

What's the intended styling for the popup part of the selector? 

I assume at least the hover styling is broken in the screenshot and latest build

Thanks

**Comment by jfhenon** [comment]
We have no strict guidelines but clearly the current style is indeed broken.

**Comment by jfhenon** [comment]
@radasam you can claim your payment on bountysource.
JF

**Comment by radasam** [comment]
@jfhenon thanks, I've signed up and submitted a solution
