### ISSUE TITLE
The console reported an error setConfig

### ISSUE THREAD

**Issue by So-For** [SVG-Edit/svgedit#680]
When I set setConfig,there has an error

I was set `dimensions` as Array , but `select.js` got an Object.
![image](https://user-images.githubusercontent.com/66558137/145778642-7d72c44d-6b07-4f78-8d47-5722ce96b9f5.png)

```js
svgEditor.setConfig({
    dimensions: [ 640, 480 ],
  });
```

**Comment by jfhenon** [comment]
two questions:  
1. { 0: 640, 1:480 } should be equivalent to  [640, 480] no? 
2. could you make a step by step guide to reproduce the issue?
