### ISSUE TITLE
npm i  ,  404 Not Found - GET https://oss.npmmirror.com/elix/-/elix-15.0.1.tgz

### ISSUE THREAD

**Issue by fangx4** [SVG-Edit/svgedit#685]
**To Reproduce**
1. npm i

**Log**
2069 verbose stack HttpErrorGeneral: 404 Not Found - GET https://oss.npmmirror.com/elix/-/elix-15.0.1.tgz
2069 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:95:15
2069 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2070 verbose statusCode 404
2071 verbose pkgid elix@https://registry.npm.taobao.org/elix/-/elix-15.0.1.tgz
2072 verbose cwd /System/Volumes/Data/data/www/svgedit
2073 verbose Darwin 20.6.0
2074 verbose argv "/opt/local/bin/node" "/opt/local/bin/npm" "i"
2075 verbose node v14.18.2
2076 verbose npm  v7.22.0
2077 error code E404
2078 error 404 Not Found - GET https://oss.npmmirror.com/elix/-/elix-15.0.1.tgz
2079 error 404
2080 error 404 'elix@https://registry.npm.taobao.org/elix/-/elix-15.0.1.tgz' is not in the npm registry.
2081 error 404 You should bug the author to publish it (or use the name yourself!)
2082 error 404 Note that you can also install from a
2083 error 404 tarball, folder, http url, or git url.
2084 verbose exit 1

**Comment by jfhenon** [comment]
Hello, it must be an issue with your npm configuration. It works well with me. 
I suggest you directly check with the author of the package: https://github.com/elix/elix
