### ISSUE TITLE
Remove console errors when in an extension mode

### ISSUE THREAD

**Issue by Chinimala** [SVG-Edit/svgedit#692]
Hello,

When you are in a mode provided by an extension (for example, shapelib), you are spammed with console.error "unknown mode" when moving the mouse.
This can be tested on https://svgedit.netlify.app/editor/index.html when using the shapelib.

**Comment by jfhenon** [comment]
good catch...this will be fixed quickly on master but, unless requested by anyone, I will wait a little before publishing to npm.

**Comment by Chinimala** [comment]
Thank you for your concern ! I overwrited the console.error function for the moment.
