### ISSUE TITLE
how to get the select conditon without mousedown

### ISSUE THREAD

**Issue by crazyboy12** [SVG-Edit/svgedit#72]
i want make the element in canvas had been selected which i  only use the element id ,could i do this?

**Comment by brettz9** [comment]
There are two possible methods. For either, you pass in array of DOM elements and an optional boolean as second argument to indicate whether to also show the grips.

`svgEditor.canvas.addToSelection([domElement1ToSelect, domElement2ToSelect], true);`

`svgEditor.canvas.selectOnly([domElement1ToSelect, domElement2ToSelect], true);`

The first, `addToSelection`, will not clear away any existing selections first, whereas the second, `selectOnly` does.

`selectOnly` first calls `svgEditor.canvas.clearSelection(true);` (where `true` indicates the `selected` handler will not be fired) and then passes its arguments to `addToSelection`.

(My answers assume the latest pre-release (at https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/editor/svg-editor.html ) but I would guess the API may also have applied to older releases.)

Closing as that should answer it, but feel free to comment further.
