### ISSUE TITLE
Is there any way to set persistent styles on individual elements?

### ISSUE THREAD

**Issue by JonasGruenwald** [SVG-Edit/svgedit#723]
Hi, 

I'm trying to integrate svgcanvas into a project, I'm not using any of the svgedit UI, just working with the canvas / DOM directly.

I need to set styles on the individual elements on the canvas for things that are not covered by the basic SVG options that can be set through svgcanvas functions, like mix-blend-mode, font-variation-settings for variable typefaces etc.

When I set styles on an element on the canvas, either directly through the DOM, or via svgcanvas.changeSelectedAttribute, the next time the element is moved by the user, the styles get removed from it, I'm assuming that's because svgcancas sets things like pointer-events on individual objects.

I'm just wondering if there is any way around this that would allow me to set styles on those individual elements without them being removed, I've tried to look through the docs and source but I couldn't find any functions related to setting styles -- any help would be appreciated.

**Comment by jfhenon** [comment]
hello, SVG-Edit currently support to set a class on a single element.
<img width="234" alt="image" src="https://user-images.githubusercontent.com/20402845/152882732-5e4b302b-82c9-42b5-92aa-419feee39867.png">
would this work for your use case?

**Comment by JonasGruenwald** [comment]
Hi! Thank you very much for getting back to me - I have considered that option, but unfortunately it won't work for what I need to implement.

I need to set different numeric style values for individual elements for my use case of variable typefaces, so for instance I'll have a slider that produces a numeric value, then I want to apply that value as a font variation setting style on an individual element like this
```
font-variation-settings: 'wdth' 25;
```
Where 25 would be a variable numeric value from the slider, so I can't just write a static class for that unfortunately.
I could perhaps dynamically generate a style-sheet with rules for each element that sets those styles within those rulesets, however that seems pretty tricky, and I think dynamically modifying CSS stylesheet rules still has bad browser support.

Maybe a workaround could be re-applying the styles every time after svgedit removes them, it seems like adding them after a change event occurs doesn't work though sadly..

**Comment by JonasGruenwald** [comment]
Just to update, since there seems to be not other way, I did go for generating a CSS stylesheet from my values every time they change - but just as regular text, and then injecting that text into a style tag in the svg, probably not the best option, but it should work, my implementation is a bit like this:

```
export const generateCanvasStyle = (list: CanvasElement[]) => {
  let output = ""
  list.forEach((item) => {
    output += `
#${item.id}{
  mix-blend-mode: ${item.blendMode};
}
    `
  })
  return output
}
```

Given a list of items that I keep track of, with their values stored on them, maybe it helps someone with a similar problem, I'm closing this issue.
