### ISSUE TITLE
I can't run this project

### ISSUE THREAD

**Issue by echolove38** [SVG-Edit/svgedit#724]
I cloned the project
run npm install
run npm run start
I open the http://localhost:8000/src/editor/index.html
I see this error in browser console:
`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.`

**Comment by jfhenon** [comment]
I just started from a new installation and it worked for me. 
You have to give more details on your environment if you want a chance to solve the issue. (for example, are you using extensions?, what is your OS, your node version etc...)

**Comment by echolove38** [comment]
> I just started from a new installation and it worked for me. You have to give more details on your environment if you want a chance to solve the issue. (for example, are you using extensions?, what is your OS, your node version etc...)

OS: windows 10
node: 14.7.0
browser: chrome

**Comment by jfhenon** [comment]
did you modify anything after the clone of svgedit?

**Comment by echolove38** [comment]
> did you modify anything after the clone of svgedit?

nothing

**Comment by jfhenon** [comment]
Can give us screenshot of your console and also the network tab of the Chrome inspector?

**Comment by echolove38** [comment]
> Can give us screenshot of your console and also the network tab of the Chrome inspector?
![error](https://user-images.githubusercontent.com/12425497/154654252-c6d27d24-4b3a-4a35-8b25-963db60b0a2f.png)
![error1](https://user-images.githubusercontent.com/12425497/154654278-7ad08ad6-2b6b-4f76-ab2f-74e45fa5f783.png)

**Comment by jfhenon** [comment]
strange indeed... 
can you also please run `npm ls` to check what versions are used?

**Comment by jfhenon** [comment]
npm ls should give you the version of all packages.

**Comment by echolove38** [comment]
> npm ls should give you the version of all packages.

I redownload the project code, and now run ok, thanks
