### ISSUE TITLE
Bring forward / Send backward moves selected element all the way forward or all the way backward

### ISSUE THREAD

**Issue by kevindude6** [SVG-Edit/svgedit#726]
**Describe the bug**
Logical error in **"moveUpDownSelected()" in selected-elem.js** causing moveUpDownSelected() to have the same effect as moveToBottomSelectedElem() / moveToTopSelectedElem(). This can be verified in the svg-edit v7 demo.

**To Reproduce**
1. Layer three shapes on top of each other
2. Select the top shape
3. Right click
4. Select send backward

**Expected behavior**
Top-most element will move backward one step, leaving it in the middle of the other two elements

**Actual behavior**
Top-most element will move all the way to the bottom.

**SVG-Edit environment (IMPORTANT)**
- All environments

**Possible fix**

Change:
```
Array.prototype.forEach.call(list, el => {
    if (!foundCur) {
      if (el === selected) {
        foundCur = true
      }
      return true
    }
    closest = el
    return false
})
```

To:

```
Array.prototype.forEach.call(list, function (el) {
    if (!foundCur) {
      if (el === selected) {
        foundCur = true
      }
      return true
    } else if(closest === undefined){
      closest = el
    }
    return false
})
```

There are definitely better solutions, but I can submit this change as a pull request if desired.

**Comment by jfhenon** [comment]
yes, it would be great if you can propose a PR.
