### ISSUE TITLE
Hosting SVG edit without a webserver

### ISSUE THREAD

**Issue by Saurbaum** [SVG-Edit/svgedit#74]
The majority of SVG Edit works when I try to run it locally.  Some few requests though fail due to cross origin requests when trying to make use of jQuery.

XMLHttpRequest cannot load file:///C:/Dev/svg-edit-2.8.1/images/svg_edit_icons.svg. Cross origin requests are only supportedf or protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.send @ jquery.js:4

Is there a way to run this without the overhead of a webserver?

**Comment by codedread** [comment]
I think the only functionality that you don't get is having the icons, which are loaded via XMLHttpRequest.  Is it really so annoying to set up though?  This is what I use:

python -m SimpleHTTPServer 8888

**Comment by Saurbaum** [comment]
You also lose half the drawing capabilities and a fair few message boxes appear empty as well.

While it is trivial to start one in a production environment in the security paranoid customer world where every port opened has to be verified and explained it's much harder to convince people that it's really necessary.

**Comment by Saurbaum** [comment]
Turns out I can trick my hosted browser into allowing the file access to get around the cross origin request.

**Comment by progers** [comment]
For others who stumble on this thread, this means launching chrome with --allow-file-access-from-files.

In general though, don't do this unless you have an issue opening ports and are not behind a firewall. It is very easy to forget to restart your browser without the flag, and --allow-file-access-from-files should not be used for your daily browsing on the open web.

The preferred way is with a local server and localhost.
Start the server:
python -m SimpleHTTPServer 8000

And then drive your favorite browser over to:
http://localhost:8000/
