### ISSUE TITLE
is there a way to enter read only mode ?

### ISSUE THREAD

**Issue by echolove38** [SVG-Edit/svgedit#746]
is there a way to enter read only mode ?
users can only read , no ability to select, move, etc...

**Comment by jfhenon** [comment]
You could just use any internet browser to display your SVG (directly or with an iframe). You don't need svgedit to display SVG in readonly mode.

If you really need svgEdit in readonly, you need to write an extension to capture every event and do nothing.

**Comment by echolove38** [comment]
> You could just use any internet browser to display your SVG (directly or with an iframe). You don't need svgedit to display SVG in readonly mode.
> 
> If you really need svgEdit in readonly, you need to write an extension to capture every event and do nothing.

ok , thanks
