### ISSUE TITLE
Chrome reports use of deprecated features.

### ISSUE THREAD

**Issue by Saurbaum** [SVG-Edit/svgedit#75]
Should I be concerned about compatibility going forwards of SVG Edit?

browser.js:59 SVGPathSeg is deprecated and will be removed in Chrome 48. See https://www.chromestatus.com/feature/5708851034718208.ww.chromestatus.com/feature/5708851034718208.

jquery.js:3 SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead.

**Comment by iuyiuy** [comment]
The jquery part should be fixed with bug #52.

**Comment by sebhaase** [comment]
As long as the SVG PathSeg API is used (that is, what was deprecated recentlz by chrome)  one needs to include one additional js file , ref. https://github.com/progers/pathseg 

`<script src="pathseg.js"></script>`

**Comment by brettz9** [comment]
As mentioned, the jQuery issue is being tracked by #52 and pathseg.js provides the `SVGPathSeg` replacement, so closing this issue. Feel free to open another issue for any additional deprecation notices you may come across.
