### ISSUE TITLE
Moving an element with snapping on causes selector box misalignment

### ISSUE THREAD

**Issue by kevindude6** [SVG-Edit/svgedit#752]
**Describe the bug**
When moving an element that is not aligned to the snapping grid, the element will be snapped to the grid after click and drag (or resizing the element). However, the bounding selector box of the element will not be updated, causing a misalignment.

**To Reproduce**
1. Create an element with snapping off
2. Turn snapping on (setting the snapping step-size to a higher value may be helpful for visual clarity)
3. Click and drag the element anywhere, then release left mouse button.
4. Observe selector box

**Expected behavior**
Selector box will resize to fit newly-snapped element

**SVG-Edit environment (IMPORTANT)**
- Live demo environment (2022/4/4)
- Master branch as of (2022/4/4)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome, Safari

**Screenshots**
[1](https://imgur.com/a/dbwat4W)

**Additional context**
Appears to be resolved by adding:
`svgCanvas.selectorManager.requestSelector(selectedElements[i]).resize()`
into the for loop located in event.js:mouseUpEvent line 626.

I will create a pull request for this fix if desired.

**Comment by kevindude6** [comment]
Pull request --> #753

**Comment by jfhenon** [comment]
Closed with #753
