### ISSUE TITLE
you probably meant to install standard and not standardjs

### ISSUE THREAD

**Issue by jimmywarting** [SVG-Edit/svgedit#761]
https://github.com/SVG-Edit/svgedit/blob/02feff8db559b1207a2746e3cc49791e4c9ceec7/src/editor/react-extensions/react-test/package.json#L14

**Comment by jfhenon** [comment]
Correct. I'll fix this. 
Thanks

**Comment by jfhenon** [comment]
fixed with https://github.com/SVG-Edit/svgedit/pull/764
