### ISSUE TITLE
No favicon icon

### ISSUE THREAD

**Issue by Georg-Git** [SVG-Edit/svgedit#766]
**bug**
I miss the favicon icon.
[https://svgedit.netlify.app/editor/index.html](https://svgedit.netlify.app/editor/index.html)

The link is broken:
`  <link rel="shortcut icon" href="data:image/x-icon;," type="image/x-icon" />`

should be:
`<link rel="shortcut icon" type="image/x-icon" href="images/logo.png">`

 and the file  /images/logo.png is missing.
 
 See icon of old version:
 [https://unpkg.com/svgedit@5.1.0/editor/images/logo.png](https://unpkg.com/svgedit@5.1.0/editor/images/logo.png)

**Comment by Georg-Git** [comment]
My proposal: a slightly modified version of logo.svg.

The result: 

![image](https://user-images.githubusercontent.com/1309628/169689906-df11fb80-60f9-49da-a929-15880310b7e2.png)

![image](https://user-images.githubusercontent.com/1309628/169690223-31a0d2ad-cc25-43fe-ad25-ebf7dcc074d5.png)

![image](https://user-images.githubusercontent.com/1309628/169690239-69072213-41dc-4fd2-8f07-abb4a30460e3.png)


logo.svg:
`<svg width="51" height="51" xmlns="http://www.w3.org/2000/svg">
<g class="layer">
<g fill="#f9ba00" stroke-width="0">
<circle cx="4.9" cy="36.7" r="2.5"/><circle cx="8.2" cy="28.6" r="2.5"/><circle cx="16.2" cy="25.3" r="2.5"/><circle cx="27.6" cy="36.6" r="2.5"/><circle cx="24.3" cy="44.7" r="2.5"/><circle cx="16.2" cy="48" r="2.5"/><circle cx="8.2" cy="44.7" r="2.5"/>
<path d="m7 43.4 9.2-9.2 2.4 2.5L9.4 46z"/>
<path d="M14.5 25.3H18V48h-3.5z"/>
<path d="m7 29.9 2.5-2.5 16 16-2.4 2.5z"/>
<path d="M4.9 35h22.4v3.5H4.9z"/>
</g>
<path fill="#666" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M37.7 1 18.3 25 16 38.3l12.2-4.9L47.7 9.1"/>
<path d="M17 32.8a3.9 3.9 0 0 1 3 .6 3.5 3.5 0 0 1 1.5 2.7L16 38.2l1-5.4z" fill="#fff"/>
<path d="M19 24.5a15.7 16 0 0 0 3.8 5 18.7 19 0 0 0 5.8 3m5.6-28.1a17 17 0 0 0 4.1 5.2 20.3 20 0 0 0 6.3 3.1" fill="none" stroke="#fff" stroke-miterlimit="10"/>
<path d="M48 8.8a18.5 18.5 0 0 1-5.7-3A33.5 33.5 0 0 1 37.6 1S42 2.2 44 3.7a24.5 24.5 0 0 1 4 5.1z" fill="none" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"/>
</g></svg>`

**Comment by jfhenon** [comment]
I made a change so the favicon also works in dark mode. 
I hope this is OK for you as well. leet me know.
<img width="145" alt="image" src="https://user-images.githubusercontent.com/20402845/170859852-9fb53231-6f40-4818-b11c-faef8591ae0c.png">
<img width="126" alt="image" src="https://user-images.githubusercontent.com/20402845/170859911-b483a8b6-f970-4de4-a0d2-af6aabf50ce8.png">
