### ISSUE TITLE
Loaded image misplaced with both "svgEditor.loadFromURL" and "?url=" query parameter

### ISSUE THREAD

**Issue by tobei** [SVG-Edit/svgedit#770]
**Describe the bug**
When loading an external SVG form an URL, either with loadFromURL or url query parameter, the loaded SVG will appear next to the canvas but not on the canvas. Sometimes the canvas will be resized to the size of the image, and sometimes it will not. In both cases reloading the page will resize and align the loaded image perfectly on the canvas.

**To Reproduce**
1. Open svg-edit latest build
2. Open the console and execute svgEditor.loadFromURL(...) to load an externally hosted SVG.
3. Alternatively, open svg-edit with ?url=... pointing to an externally hosted SVG.
4. Instead of being the same result as a normal "open", there is now the external image next to the canvas instead of being on the canvas. In some instances the canvas doesn't even resize to the image dimension.

**Expected behavior**
loading remote SVG this way should behave just like a local file "open" should, and not as an image import/placement:
the canvas should be set to SVG content and resized accordingly.

**SVG-Edit environment (IMPORTANT)**
svg-edit latest build (v7)

**Desktop (please complete the following information):**
windows 10
chrome 101

**Comment by jfhenon** [comment]
Can you test with the PR preview?
https://deploy-preview-771--svgedit.netlify.app/editor/index.html?url=...
Thanks

**Comment by tobei** [comment]
Hi there, did a few tests and it worked like a charm so far ! Super thank you !!
