### ISSUE TITLE
svg with text contains '<>&' chars can't be opened again

### ISSUE THREAD

**Issue by lisupeng** [SVG-Edit/svgedit#776]
Reproduce steps:
1.New a svg. Add text contains '<' or '>'
2.Save the svg.
3.Load the svg and fails.

**Comment by jfhenon** [comment]
I followed your steps using the latest version (https://svgedit.netlify.app/editor/index.html)
and could open with no issue the following SVG: 
````
<svg width="640.0000000000001" height="480" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
 <!-- Created with SVG-edit - https://github.com/SVG-Edit/svgedit-->
 <g class="layer">
  <title>Layer 1</title>
  <text fill="#000000" font-family="Serif" font-size="24" id="svg_2" stroke="#000000" stroke-width="0" text-anchor="middle" x="97.5" xml:space="preserve" y="89.5">Text&gt;&lt;&amp;</text>
 </g>
</svg>
`````
<img width="715" alt="image" src="https://user-images.githubusercontent.com/20402845/174428721-8fd2bfbf-3e72-439e-9f0f-3292066a2251.png">

Please confirm the version, provide the svg that could not open.
thanks

**Comment by jfhenon** [comment]
if the problem can be reproduced, please reopen with detailed informations.
thanks
