### ISSUE TITLE
When moving selection with arrows always cr, cx or r input is focused

### ISSUE THREAD

**Issue by m0bYczE** [SVG-Edit/svgedit#778]
Hello, I have problem when I move selection with arrows than input like cr, cx or r is selected (focused) and than I can't move with selection until I click topbar and disable focus on input than after one key click is it back focused on input. How can I fix it? Browser is Safari.

Thank you.

**Comment by m0bYczE** [comment]
I tried it in Chrome and this working, so it would be problem only on Safari.

**Comment by jfhenon** [comment]
You are right, I tried on Safari, Firefox and Chrome.
1/ click on a circle shape
2/ click on any input field of the toolbar (such as rx) 
3/ click anywhere on the canvas so the toolbar disappear
4/ click on the circle shape again so the toolbar reappear 

On Firefox and Chrome, no input field has the focus however on Safari, the rx input field has kept the previous focus (so the arrows will not move the shape on the canvas but increase or decrease the rx value).

So you behavior is explainable by the way the browser has been designed. I don't think this should be fixed (or maybe in Safari to make it consistent with other browsers).
