### ISSUE TITLE
Reorient path locks editor

### ISSUE THREAD

**Issue by Saurbaum** [SVG-Edit/svgedit#78]
Draw a squiggle with the pencil tool.
Rotate it.
Hit reorient path.

SVG Edit is now locked up.

Using the demo version still hosted from the Google Code site it works.

**Comment by brettz9** [comment]
Please try on https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/editor/svg-editor.html , our latest prerelease. I am not able to replicate any problems there (In https://svg-edit.github.io/svgedit/releases/svg-edit-2.8.1/svg-editor.html there are some problems with this sequence, but ones not relating to locking up.)

Closing as it appears to be fixed, but feel free to reopen if you are still experiencing problems. Also let us know the browser you are using.
