### ISSUE TITLE
Rewrite the seList and seListItem components

### ISSUE THREAD

**Issue by jfhenon** [SVG-Edit/svgedit#784]
NOTE:
This issue is funded on Bountysource (https://app.bountysource.com/issues/109641309-rewrite-the-selist-and-selistitem-components)
However, this is a FULL REWRITE of the list/listitem selector web component without using the elix library.
The component source is: src/editor/components/seList.js (and seListItem.js)
Native JS, CSS preferred but another library is possible if it is popular and actively maintained.

Obviously, the fix needs to work consistently on Safari, Firefox and Chrome.

**Comment by marcosfreitas** [comment]
there is anyone working on this? I'm interested.

**Comment by acanosa** [comment]
Hello, is this still available or is marcos still working on it?

**Comment by marcosfreitas** [comment]
> Hello, is this still available or is marcos still working on it?

Hey, I'm not working on it.
