### ISSUE TITLE
zooming on iMac with apple magic mouse is way too sensitive.

### ISSUE THREAD

**Issue by MoralCode** [SVG-Edit/svgedit#80]
whenever I try and zoom using the scroll gesture on the apple magic mouse, SVG-edit exaggerates the amount that I want to scroll and i have to keep re-finding my image.

can you add a scroll-sensitivity adjustment?

**Comment by brettz9** [comment]
With a recent fix to zooming, you might want to try again at https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/editor/svg-editor.html . I don't think we've changed anything about the amount of zooming, but it should be easier to control the positioning...

**Comment by bjtucker** [comment]
I'm not sure what has changed, but I can confirm that I found svgedit hard to use because of a similar behavior on mac using the trackpad around the same time this issue was created. I can't seem to replicate the issue I was having now. 

Happy to find that this seems fixed to me.

**Comment by brettz9** [comment]
Great--well, if I don't hear back from the original poster or others who experienced the issue or who can test it, I think I'll change the issue to being merely a feature request for controlling scroll sensitivity rather than an environment-specific bug.

**Comment by DeveloperACE** [comment]
Hey, sorry for the delay. I since switched to using a trackpad so sorry about that.
I tried the link you provided on both my apple trackpad and magic mouse and the mouse scroll gesture seems to now only scroll/pan the page. However the trackpad pinch-to-zoom gestures also dont work.

Sorry for the delay.

**Comment by jfhenon** [comment]
5 years old issue. please create a new issue if needed. thank you for understanding.
