### ISSUE TITLE
The coordinates' position  of the object "text " don't seems correct,  

### ISSUE THREAD

**Issue by MK0626** [SVG-Edit/svgedit#852]
There was a great deal of confusion about the true meaning of the coordinates' position, It seems impossible to draw this image through the Java background by the following source file:

<svg width="296" height="152" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
 <g>
  <title>Layer 1</title>
  <templateName>test</templateName>
  <templateNo/>
  <scenarioId>1591353237001076736</scenarioId>
  <templateTypeId/>
  <color>402</color>
  <templateId>1593425162561056768</templateId>
  <text currText="currText" y2="1.04603" x2="5.00324" y1="32.0419" x1="42.74746" height="31" width="33.46875" bg-color-opacity="1" stroke-color-opacity="1" xml:space="preserve" text-anchor="start" font-family="微软雅黑" font-size="24" id="svg_4" y="26.61239" x="5.17226" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" dproportion-down="0" dproportion-up="0" decimal-allowed="0" strokes-width="0" stroke-width="0" bg-color="null" stroke-color="#ffffff" stroke="#000000" fill="#000000">
   <tspan y2="1.04603" x2="5.00324" y1="32.0419" x1="42.74746" y="26.61239" x="5.17226">test</tspan>
  </text>
 </g>
</svg>
![img1](https://user-images.githubusercontent.com/118510166/202835908-51189b70-b01a-4c6b-9b70-a0c514010c76.png)

**Comment by jfhenon** [comment]
Can you please clarify the question?

**Comment by jfhenon** [comment]
Below is the definition of the x,y of the text element in an svg. I'm closing the issue as it's not detailed enough

```
[x](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/x)
The x coordinate of the starting point of the text baseline. Value type: [<length>](https://developer.mozilla.org/en-US/docs/Web/SVG/Content_type#length)|[<percentage>](https://developer.mozilla.org/en-US/docs/Web/SVG/Content_type#percentage) ; Default value: 0; Animatable: yes

[y](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/y)
The y coordinate of the starting point of the text baseline. Value type: [<length>](https://developer.mozilla.org/en-US/docs/Web/SVG/Content_type#length)|[<percentage>](https://developer.mozilla.org/en-US/docs/Web/SVG/Content_type#percentage) ; Default value: 0; Animatable: yes
```
