### ISSUE TITLE
Inclusion in a HTML Editor (Webcomponent)

### ISSUE THREAD

**Issue by jogibear9988** [SVG-Edit/svgedit#858]
Hello,

I'm workin on a HTML Editor Webcomponent (see: https://node-projects.github.io/web-component-designer-demo/index.html).
I need also SVG Editing capability in my Editor (wich is very limited at the moment). Would be nice if I could include the functionality of the framework.

At the moment if not yet a Idea how, nor have I looked into your codebase. But maybe there are parts we could share? Maybe this would also be a win for you?
Any interest in a work together? Or to exchange ideas?

**Comment by cuixiping** [comment]
You can read this part from README:  [I want to integrate SVGEdit into my own Web application](https://github.com/SVG-Edit/svgedit#i-want-to-integrate-svgedit-into-my-own-web-application)

**Comment by jfhenon** [comment]
or [I want to build my own svg editor]( https://github.com/SVG-Edit/svgedit#i-want-to-build-my-own-svg-editor) to use the svgcanvas capabilities
