### ISSUE TITLE
Problems integrating svgcanvas in angular project -  error TS7016: Could not find a declaration file for module '@svgedit/svgcanvas'

### ISSUE THREAD

**Issue by sbodese** [SVG-Edit/svgedit#861]
Hi, im got also problems to integrate this svgeditor in angular 14.x or 15.x. like the documentation says:

"npm i -s '@svgedit/svgcanvas'

you can then import it in your application:

import svgCanvas from '@svgedit/svgcanvas'"

doesnt work,

i got a TS7016 Error

Error: src/app/shared/components/image-preview/image-preview.component.ts:2:23 - error TS7016: Could not find a declaration file for module '@svgedit/svgcanvas'. 'C:/gits/product/frontend/product/node_modules/@svgedit/svgcanvas/dist/svgcanvas.js' implicitly has an 'any' type. Try npm i --save-dev @types/svgedit__svgcanvasif it exists or add a new declaration (.d.ts) file containingdeclare module '@svgedit/svgcanvas';`

2 import SvgCanvas from '@svgedit/svgcanvas';
`

Thanks and Greetings Steffen

**Comment by sbodese** [comment]
generally solved by add these line to the tsconfig.json:

  "compilerOptions": {

    // svg edit type import versuch
        "noImplicitAny": false,

at least the whole editor is not runnable under angular.

**Comment by KunioHaha** [comment]
> generally solved by add these line to the tsconfig.json:
> 
> "compilerOptions": {
> 
> ```
> // svg edit or svgcanvas type import need
>     "noImplicitAny": false,
> ```
> 
> at least the whole editor is not runnable under angular.

I don't think its a good idea
