### ISSUE TITLE
Cannot able to drag and drop images from iphone/ipad drive images when directly connected to laptop/pc 

### ISSUE THREAD

**Issue by NK121190** [SVG-Edit/svgedit#872]

**Comment by NK121190** [comment]
I am trying to drag and drop from iphone drive. I am connecting phone in the USB port .So that in My computer like c drive, d drive Apple phone drive will appear. From there i am trying to drag and drop images to svg editor ,it is not working . File size is coming as 0, and while dragging instead of copy it is showing as move.Please help to resolve
 
I am using 5.0.0 version

**Comment by jfhenon** [comment]
> I am trying to drag and drop from iphone drive. I am connecting phone in the USB port .So that in My computer like c drive, d drive Apple phone drive will appear. From there i am trying to drag and drop images to svg editor ,it is not working . File size is coming as 0, and while dragging instead of copy it is showing as move.Please help to resolve
> 
>  
> 
> I am using 5.0.0 version

Could you please test on the latest version. It will be difficult to find someone to fix version 5. 
Thanks

**Comment by NK121190** [comment]
I  have implemented 5.0.0 version in my project .I have worked around 4 months to stablize it in my project. So Kindly  tell me the root cause or fix for the above

**Comment by jfhenon** [comment]
I would try https://bountysource.com/ to find someone interested to fix your issue.
