### ISSUE TITLE
Expected length NaN errors 

### ISSUE THREAD

**Issue by bartbutenaers** [SVG-Edit/svgedit#875]
**Describe the bug**
When I apply a (correct) svg string to svg-edit, I 'think' he gives errors about the default svg string.

**To Reproduce**

Since my appliction is a plugin for Node-RED, unfortunately I can only show a part of the code here.
Hopefully my description might give you some idea what I might be doing wrong...

My open-source application works like this:
1. The svg string is stored inside my own application.  
2. When a user clicks the *"open svg-edit"* button in my application, the svg string is applied to svg-edit.
3. Then the user can manipulate the svg string via svg-edit.
4. At the end, svg-edit is closed and the manipulated svg string is stored in my application
5. The user can repeat this process over and over again.

I will try to summarize the code a bit, to explain how I have implemented this:
1. The container div element of my plugin will end up somewhere inside the Node-RED html:
   `<div id="svg-edit-container" style="display:none"></div>`
   I have set display to none because the container should be invisible by default.
2. As soon as I user opens the dialog popup of my plugin, I create the svg-edit instance to make sure svg-edit is ready to go:
   ```
   <link href="svg_edit/lib/svgedit.css" rel="stylesheet" media="all"></link>
   <script type="module">
      import SvgDrawingEditor from '/svg_edit/lib/Editor.js';
      let svgEditContainer = document.getElementById('svg-edit-container');
      let svgDrawingEditor = new SvgDrawingEditor(node.svgEditContainer);
      svgDrawingEditor.init();
      // Get the svg string from my application and pass it to svg-edit
      svgDrawingEditor.loadFromString("<svg width="640" height="480" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg"><circle cx="50" cy="50" r="40" fill="green"/></svg>");
      svgDrawingEditor.setConfig({
         allowInitialUserOverride: true,
         fitToContent: true,
         extensions: [],
         noDefaultExtensions: false,
         userExtensions: [],
         // Load the images via my plugin endpoint that acts as a proxy
         imgPath: "svg_edit/lib/images/",
         // Don't load the default initial or last modified svg string from cache.  
         // Otherwise the svg string - that is applied via loadFromString - will be replaced by svg-edit immediately afterwards.
         noStorageOnLoad: true 
      })

      svgDrawingEditor.onchange = function() {
         // Get the modified string from svg-edit and store it in my application.
         // I never arrive here.   Still need to figure out why ...
         var svgString = svgDrawingEditor.getSvgString();
      };
   </script>
   ```
3. As soon as the user clicks the *"open svg-edit"* button in my application, I show the container div element again in full screen mode:
   ```
   $("#node-open-svg-edit").on("click", async function (e) {
      // Get the svg string from my application and pass it to svg-edit
      svgDrawingEditor.loadFromString("<svg width="640" height="480" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg"><circle cx="50" cy="50" r="40" fill="green"/></svg>");
      svgDrawingEditor.loadFromString(svgString);
      // Show the container div element again  
      svgEditContainer.style.display = "";

      $(document).on('webkitfullscreenchange mozfullscreenchange fullscreenchange', function(event) {
         if (!document.fullscreenElement) {
            // When leaving full screen mode, hide the container div element again
            svgEditContainer.style.display = "none";
         }
      });

      var requestFullScreenMethod = svgEditContainer.requestFullScreen || svgEditContainer.webkitRequestFullscreen || svgEditContainer.webkitRequestFullScreen || svgEditContainer.mozRequestFullScreen || svgEditContainer.msRequestFullscreen;

      if( requestFullScreenMethod ) {
         requestFullScreenMethod.apply( svgEditContainer );
      }
   });
   ```
   And that seems to work fine: svg-edit is opened in full screen mode and nicely draws my svg string.

4. However when I open my Chrome developer tools console log, I see these errors:
   ```
   Error: <svg> attribute width: Expected length, "NaN".
   Error: <svg> attribute height: Expected length, "NaN".
   Error: <svg> attribute x: Expected length, "NaN".
   Error: <svg> attribute y: Expected length, "NaN".
   Error: <g> attribute transform: Expected number, "translate(NaN,NaN)".
   ```

By looking at the `<g>` element I have somehow a feeling that svg-edit is complaining about the default svg-string that svg-edit uses itself (because that also contains such a group).  Or is it related to the group that svg-edit adds to my own svg string, because I see that my svg string has been manipulated automatically:

![image](https://user-images.githubusercontent.com/14224149/213907047-27596c3d-7f56-443d-80e0-562ceb738838.png)

I had set the `noStorageOnLoad: true ` to get rid of that default svg string.  Because otherwise svg-edit always showed the default svg instead of mine...

I am not sure at the moment if I am displaying/hiding svg-edit correctly.  It feels somehow that I am doing it completely incorrect, by circumventing the cache or something else....  So I would appreciate if anybody could give me some tips to do it better.

Thank you!!!
Bart

**SVG-Edit environment (IMPORTANT)**
My Node-RED web application connects to my server via http, where my endpoint (acting as a proxy) will load the files from https://svgedit.netlify.app/editor/ and send it back to my browser.
So at the moment I use the files I get from that cloud server, not from an npm package (yet).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 108.0.5359.125 (Official Build) (64-bit)

**Comment by jfhenon** [comment]
Hi Bart,
Thank you for the detail question. Can you explain this line of your code:
`svgDrawingEditor.loadFromString(svgString);`

**Comment by bartbutenaers** [comment]
@jfhenon,
You are correct.  Normally I use the svgString variable, which contains the string stored in Node-RED.  For this issue I had replaced it by the hardcoded svg string (i.e. the statement just above it), to simplify my code a bit.  But I forgot to remove the original statement using the variable.  So you can ignore that line.  My bad...

**Comment by bartbutenaers** [comment]
@jfhenon,
Did a little of debugging.

1. I pass a string (containing both a width and height) to svg-edit:

   ![image](https://user-images.githubusercontent.com/14224149/214164343-05a64010-8d11-4081-9bd9-36060e058c77.png)

2. But when stepping down into that function, I can see that all variables are NaN.

   ![image](https://user-images.githubusercontent.com/14224149/214164715-4e085af7-9efe-4e20-b39c-46feb8326095.png)

3. And then the exception occurs at line 387

So the problem is not related to the width and height in my svg string, but to the ***'missing' width and height of my container div element***.  My container div element has style `display:none` (as mentioned above in my original post), because I don't want it to consume any space inside the Node-RED application.  When I remove that style, the error seems to be gone, but then svg-edit appears _**inside**_ my Node-RED config screen window:

![image](https://user-images.githubusercontent.com/14224149/214165575-0633e049-8013-4bbd-8c81-87d42289733d.png)

But that is not what I want to achieve, because I want the container div element (and the svg-edit content) to be invisible, except when the user wants to show it in fullscreen mode.

So I have rearranged my code a bit.  When I make my container div element visible again (via `display:""`) ***before*** I set the SVG string, then the error seems to not occur anymore because the div element got a size now:

![image](https://user-images.githubusercontent.com/14224149/214166328-6c070b67-1838-4913-872d-bebf3a9c21d7.png)

So the clue is to make sure the div element is visible when you start calculating.

Of course it is possible to workaround this, and a warning could be added to the documentation.  But it would be nice if svg-edit would be able to deal with this, because it is rather confusing.  Not sure if this helps, but I see that the canvas has a width and size (I assume it is extracted from my svg string):

![image](https://user-images.githubusercontent.com/14224149/214171335-60dd0798-09e3-43b4-92d4-1fa70206c439.png)

Perhaps svg-edit might solve this by ***temporarily*** changing the display style to make it visible:
```
let originalDisplayStyle = containerElement.style.display;
containerElement.style.display = "block";
let width = containerElement.offsetWidth;
let height = containerElement.offsetHeight;
containerElement.style.display = originalDisplayStyle;
```
You could do that perhaps only if the width or height are NaN, to have no impact on other users...

Would be nice to hear your thoughts about this!

**Comment by jfhenon** [comment]
thank you again for the time digging into this issue. 
The sample in the readme already states that the div must have a width and height.
Probably this would need to be more visible.
```
<body>
  <!-- svgedit container can be positionned anywhere in the DOM
       but it must have a width and a height -->
  <div id="container" style="width:100%;height:100vh"></div>
</body>
```
The issue with a fix is indeed that  `getComputedStyle(workarea, null).width`will return  'auto' when display is hidden but also if the width is set to 'auto'.

**Comment by bartbutenaers** [comment]
That is the least I can do, considering you are maintining this entire project for us ...

Ah it is already in the documention.  Seems I have completely overlooked that.
You can close this ticket if no "easy" fix is possible, based on your experience with this project.

Thanks for your time!!!!
