### ISSUE TITLE
Export function not work

### ISSUE THREAD

**Issue by sonnguyent2** [SVG-Edit/svgedit#891]
Hi, anyone have same issue? export to PDF work fine but other type like PNG not work.
![image](https://user-images.githubusercontent.com/7929533/225165387-a4aa2690-3997-4aff-b3b5-32c8735f72b1.png)

I have searched for this in open issues but not found, look like this is new one. Can you guide me how to fix this, thanks.

**Comment by jbardi** [comment]
I'm having the same problem. I've tested on both Chrome and Firefox with the same result. Just shows "Loading image, please wait..." but nothing else.

**Comment by shenggen1987** [comment]
<img width="1219" alt="image" src="https://github.com/SVG-Edit/svgedit/assets/12542876/76364257-855f-49b0-acb3-96016cdc7c49">
const downloadFileName = (blobUrl, fileName) => {
  const link = document.createElement('a') // 创建a标签
  link.href = blobUrl // 获取blob 下载url
  link.download = fileName
  link.click()
  URL.revokeObjectURL(link.href)
  document.body.removeChild(link)
}
