### ISSUE TITLE
Access to the selected area of a text

### ISSUE THREAD

**Issue by FabianMauz** [SVG-Edit/svgedit#893]
Hello and thank you for providing the svgEditor.

I have a question:

Is it possible to query a selected section within a text element?

![image](https://user-images.githubusercontent.com/23172219/225307053-19d81ce1-4e14-4468-8edb-e8105c1a0ade.png)

Something like:

svgEdior.getSelectedTextPart ( )

which would return "test"

Another question from my side: 

Is there any possibility to have a subscript or superscript button for texts or parts of texts.

Many thanks in advance

Fabian

**Comment by cuixiping** [comment]
> Is there any possibility to have a subscript or superscript button for texts or parts of texts.

The answer is no. A text element is treated as an indivisible whole. You cannot set different style for a part of them.

**Comment by FabianMauz** [comment]
Thanks for your reply. 
Is there a possibility to get the selected part of a text?

**Comment by cuixiping** [comment]
No directly. But you can take a look at this file:  [svgedit/packages/svgcanvas/core/text-actions.js](https://github.com/SVG-Edit/svgedit/blob/master/packages/svgcanvas/core/text-actions.js)
