### ISSUE TITLE
Default value of 10 for Snap to grid doesn't align

### ISSUE THREAD

**Issue by bilogic** [SVG-Edit/svgedit#894]
![image](https://user-images.githubusercontent.com/946010/226594115-ff355ea9-3b1c-40b7-8eff-ab8f0628b8a9.png)

`Snapping on/off` is ticked
`Snapping Step-Size` is 10 (default value)

My round rectangle snaps, but just doesn't align with the background grid.

**Comment by jfhenon** [comment]
Each "small" square of the grid represents 10 pixels and it seems to work well. If I select 100 for step-size, below is the result and I don't see the issue:

https://user-images.githubusercontent.com/20402845/228970288-0d3695e3-33f7-4489-b7ae-f9b2142127a9.mov

**Comment by bilogic** [comment]
I just tested it on https://svgedit.netlify.app/editor/index.html, issue no longer exists, probably have to due to the recent commits. Thanks!
