### ISSUE TITLE
Path points with negative absolute coordinates get lost

### ISSUE THREAD

**Issue by Zireael07** [SVG-Edit/svgedit#895]
**PLEASE NOTE: We are trying to make this project live again. While you can file an issue, we will do our best but you should not expect any action, even if we label the issue. However, we are welcoming new contributors **

**Describe the bug**

**To Reproduce**
1. Import an svg file that sticks out of the Inkscape canvas on the left
2. Try to move the path
3. See a gap where points should be

**Expected behavior**
Points shouldn't be lost

**SVG-Edit environment (IMPORTANT)**
- File for SVG-Edit: [e.g., `svg-editor.html`, `svg-editor-es.html`, `embedapi.html`]
- Version: master on netlify
- Protocol: [e.g., http, https, file]

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser Vivaldi
 - Version 5.7.2921.63 (Stable channel) stable (64-bit) 

**Screenshots**

**Log**
If applicable, copy any error logs in your browser console. This can be very
helpful in identifying the problem.

**Additional context**

**Comment by cuixiping** [comment]
Are you talk about the number precision?

**Comment by Zireael07** [comment]
Number precision has nothing to do with it. Just the fact that they have a minus sign

**Comment by cuixiping** [comment]
Can you give your cases data details? including original data, result data and expected data.

**Comment by Zireael07** [comment]
I don't think I have the file anymore, but literally: original data is an SVG file that has negative absolute coordinates. Resulting data is that the editor shows only part and even moving doesn't show the points on the left (that have negative coordinates). Expected data is to see the entire SVG after moving it around to fit in the window

**Comment by cuixiping** [comment]
I cannot reproduce it. Can you reproduce again?

**Comment by Zireael07** [comment]
It was reproducible with the same file every time

**Comment by cuixiping** [comment]
> It was reproducible with the same file every time

You can paste your file here if you can reproduce.
