### ISSUE TITLE
can not install  when download code

### ISSUE THREAD

**Issue by w8w8w8** [SVG-Edit/svgedit#900]
**PLEASE NOTE: We are trying to make this project live again. While you can file an issue, we will do our best but you should not expect any action, even if we label the issue. However, we are welcoming new contributors **

**Describe the bug**
Can not run npm install , get some error

**To Reproduce**
1. download code from  (https://github.com/SVG-Edit/svgedit)
2. Click on 'npm install'
3. See error

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [win10]

**Screenshots**
![image](https://github.com/SVG-Edit/svgedit/assets/4744039/7f795d06-116b-43f0-ae56-f5b94eea12c2)

**Log**
npm ERR! code ENOENT
npm ERR! syscall spawn bash
npm ERR! path D:\code\svgedit-master\node_modules\core-js
npm ERR! errno -4058
npm ERR! enoent spawn bash ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Local\npm-cache\_logs\2023-05-28T04_44_31_081Z-debug-0.log

**Additional context**
D:\code\svgedit-master>node -v
v17.9.1

D:\code\svgedit-master>npm -v
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
8.11.0

D:\code\svgedit-master>

**Comment by jfhenon** [comment]
it seems the requirements for the node engine version are not met. I don't understand the reason why because you seem to be at node 17 and the requirement is >= 16. 
Did you modify the package.json? (please send a copy if you can)

**Comment by w8w8w8** [comment]
> it seems the requirements for the node engine version are not met. I don't understand the reason why because you seem to be at node 17 and the requirement is >= 16. Did you modify the package.json? (please send a copy if you can)

fist , thank you for your reply.

I download the code , and run npm i  .     didn‘t modify any thing , did not modify the package.json

**Comment by jfhenon** [comment]
can't reproduce.
