### ISSUE TITLE
how to flip Horizontal and Vertical

### ISSUE THREAD

**Issue by echolove38** [SVG-Edit/svgedit#904]
how to flip Horizontal and Vertical

**Comment by cuixiping** [comment]
Select the target element, then drag the left side control dot to right, or drag the up side control dot to bottom.

**Comment by echolove38** [comment]
> Select the target element, then drag the left side control dot to right, or drag the up side control dot to bottom.

有个工具栏按钮 点击这个按钮可以实现让选中的元素水平或垂直翻转

**Comment by cuixiping** [comment]
> > Select the target element, then drag the left side control dot to right, or drag the up side control dot to bottom.
> 
> 有个工具栏按钮 点击这个按钮可以实现让选中的元素水平或垂直翻转

I never seen that.
