### ISSUE TITLE
Is setCustomHandlers removed from 7.2.0 ?

### ISSUE THREAD

**Issue by lxsang** [SVG-Edit/svgedit#915]
Hello,

First of all, thank-you for this great project.

I followed the tutorial in [Events.md](https://github.com/SVG-Edit/svgedit/blob/master/docs/tutorials/Events.md) to implement a custom open/save behavior for the editor with  `setCustomHandlers `:

```js
svgEditor.setCustomHandlers({
  save (_win, _data) {
    // Save svg
  }
})
```

but i got the following error:

```
index.html:45 Uncaught (in promise) TypeError: svgEditor.setCustomHandlers is not a function
    at index.html:45:13
    at Editor.js:1088:18
    at Array.map (<anonymous>)
    at Editor.runCallbacks (Editor.js:1087:24)
    at Editor.init (EditorStartup.js:604:16)
(anonymous) @ index.html:45
(anonymous) @ Editor.js:1088
runCallbacks @ Editor.js:1087
init @ EditorStartup.js:604
await in init (async)
(anonymous) @ index.html:36
``` 

I am unable to locate the definition of `setCustomHandlers` anywhere in the source code. Is that function removed from the latest version of SVGEdit? Is there any alternative way to override the default open/save behavior of the editor ?

**SVG-Edit environment**
- Version: 7.2.0

**Comment by jfhenon** [comment]
Yes, setCustomHandlers is not used anymore. The documentation is not up to date.

The proper way to replace the file/open/etc... is to create an extension replacing ext-opensave.js (which you can use a sample to write your custom open/save behavior.)

To load this extension, you need to initialize svgedit and set the config using your new extension (and you likely need to stop loading the default extensions . This should look to something like the code below:

```
svgEditor.setConfig({
          allowInitialUserOverride: true,
          extensions: [
             'ext-eyedropper',
             'ext-grid',
             'ext-markers',
             'ext-panning',
             'ext-shapes',
             'ext-polystar',
             'ext-storage'
          ],
          noDefaultExtensions: true, // stop loading defaut extensions
          userExtensions: [ '/path/to/my-custom-opensave.js' }]
        })
```
Let us know if this work.

**Comment by lxsang** [comment]
Sorry for the late response!

I created a custom extension and set the following config:

```js
svgEditor.init()

svgEditor.setConfig({
          allowInitialUserOverride: true,
          noDefaultExtensions: true, // stop loading defaut extensions
          extensions: [
            'ext-eyedropper',
             'ext-grid',
             'ext-markers',
             'ext-panning',
             'ext-shapes',
             'ext-polystar',
             'ext-storage'
          ],
          userExtensions: [ 'extensions/ext-antos_vfs/ext-antos_vfs.js']
        });
```

I got the following error:

```
Error: Cannot add extension "eyedropper", an extension by that name already exists.
    at SvgCanvas.addExtension (svgcanvas.js:861:28)
    at Editor.addExtension (Editor.js:1209:27)
    at EditorStartup.js:633:25
    at async Promise.all (/workbench/index 0)
    at async Editor.extAndLocaleFunc (EditorStartup.js:616:5)
```

And the `opensave` extension still being loaded, it looks like `noDefaultExtensions` has no effect whatsoever.

**Comment by jfhenon** [comment]
I assume you have not the issue anymore. Please reopen if necessary
