### ISSUE TITLE
Documentation: Update wiki and docs/ files per most recent changes

### ISSUE THREAD

**Issue by praneybehl** [SVG-Edit/svgedit#92]
Its a great project, and also does look quite big. Just wondering if there is any documentation or is it the old fashioned way - go through the whole source and figure.

Some docs will be really helpful and greatly appreciated.
Thanks

**Comment by iuyiuy** [comment]
The readme links to the docs folder:
https://github.com/SVG-Edit/svgedit/tree/master/docs

But I've created a quick start guide in the wiki:
https://github.com/SVG-Edit/svgedit/wiki/Quick-start-guide

I think this is a better place for it. Feel free to correct me, if I'm wrong.

**Comment by praneybehl** [comment]
I am sorry I should have bene more clearer, I mean the API Reference.

**Comment by iuyiuy** [comment]
That was a start. I've now added an events article:
https://github.com/SVG-Edit/svgedit/wiki/Events

I've only documented the one event I've had a use for so far, but I might as well document it as I go. Also for my own future reference. Feel free to supplement.

**Comment by iuyiuy** [comment]
Actually, I found this:
https://svg-edit.googlecode.com/svn/trunk/docs/files/svgcanvas-js.html

It's on the deprecated Google Code repository and it's probably not up-to-date, but it might help.

**Comment by progers** [comment]
Would someone be willing to convert that to markdown and put it in https://github.com/SVG-Edit/svgedit/tree/master/docs ?

**Comment by praneybehl** [comment]
Cheers will see what I can do. Thanks

**Comment by brettz9** [comment]
There is now JSDoc-generated output for our pre-release, available at https://svg-edit.github.io/svgedit/releases/svg-edit-3.0.0-alpha.4/docs/jsdoc/index.html . However, I'm keeping the issue open as the wiki pages need review now, and even those in `docs/` probably need some updating.
