### ISSUE TITLE
Printing to Universal Laser System laser print driver

### ISSUE THREAD

**Issue by dlarue** [SVG-Edit/svgedit#921]
The ULS laser cutter/engraver is only supported on Windows( :( ) but even then it, like Epilog, uses a printer driver which configures the laser configuration based on the SVG drawing line width and line color AND if it's a vector or a bitmap.
From Adobe Illustrator we can send a drawing to the printer driver and it's setup correctly but with SVG Edit the print function appears to always look like a bitmap drawing.

Is there a way to make change this or is it just a fact of how the browser handles the page being printed?

I tried this using the latest online version(v7) on this site: https://svgedit.netlify.app/editor/index.html in a Chrome browser.

The computer connected to the laser is a Windows computer and likely Windows 7 since it's an old computer and the desktop does not have the tiles of v10.
Browser is Chrome but I don't know the version and I currently don't have access to the machine until next week.

**Comment by dlarue** [comment]
I just realized I may have not had the background disabled in Editor Preferences.  I will retest this next week and update this issue report.

**Comment by jfhenon** [comment]
OK, please reopen if needed.
