### ISSUE TITLE
X, Y coordinates not working for a group element

### ISSUE THREAD

**Issue by alibaba0507** [SVG-Edit/svgedit#930]
Create a element you can change x or y coordinates with decimal precision , for example 10.5 , but when you group one or more elements ,you can not change X,Y coordinates to 10.5 for the group , the work around is to enter for example 105 and after that add the dot between 0 and 5. Please can you fix this.

**Comment by jfhenon** [comment]
Yes, this is a bug. It's going to be fixed soon.
