### ISSUE TITLE
Indices not displaying correctly

### ISSUE THREAD

**Issue by hatienl0i2612** [SVG-Edit/svgedit#943]
**Describe the bug**

**To Reproduce**
1. Open this svg file 
https://drive.google.com/file/d/18AeyCxGC10UjQ8KRbectiTBrEjItp_IS/view
2. Check display

**Expected behavior**

**Screenshots**
 when open in browser  
![image](https://github.com/SVG-Edit/svgedit/assets/36532499/23c9db75-4acc-4695-9242-06808f295ebe)

After open in svgedit
![image](https://github.com/SVG-Edit/svgedit/assets/36532499/6fc0d75f-201b-4cc2-a083-56ce42d516d0)

**Comment by jfhenon** [comment]
The drive with the svg file is not accessible. Best would be to attach the file to a comment. 
Even better would be to make a much simpler svg with the issue.
