### ISSUE TITLE
npm run build --workspace @svgedit/svgcanvas failed

### ISSUE THREAD

**Issue by ravikandpal31** [SVG-Edit/svgedit#969]
**PLEASE NOTE: We are trying to make this project live again. While you can file an issue, we will do our best but you should not expect any action, even if we label the issue. However, we are welcoming new contributors **

**Describe the bug**
not able to build getting below error while running below step
run npm run build --workspace @svgedit/svgcanvas to build the svgcanvas dependency locally

OS: window
node: v14.15.4

> svgedit@7.3.3 prebuild C:\OPM_CODE\svgedit
> npm run build --workspace=packages/svgcanvas --workspace=packages/react-test

> svgedit@7.3.3 prebuild C:\OPM_CODE\svgedit
> npm run build --workspace=packages/svgcanvas --workspace=packages/react-test

> svgedit@7.3.3 prebuild C:\OPM_CODE\svgedit
> npm run build --workspace=packages/svgcanvas --workspace=packages/react-test

> svgedit@7.3.3 prebuild C:\OPM_CODE\svgedit
> npm run build --workspace=packages/svgcanvas --workspace=packages/react-test

'npm' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svgedit@7.3.3 prebuild: `npm run build --workspace=packages/svgcanvas --workspace=packages/react-test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the svgedit@7.3.3 prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\223021341\AppData\Roaming\npm-cache\_logs\2024-05-13T12_56_17_120Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svgedit@7.3.3 prebuild: `npm run build --workspace=packages/svgcanvas --workspace=packages/react-test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the svgedit@7.3.3 prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\223021341\AppData\Roaming\npm-cache\_logs\2024-05-13T12_56_17_212Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svgedit@7.3.3 prebuild: `npm run build --workspace=packages/svgcanvas --workspace=packages/react-test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the svgedit@7.3.3 prebuild script.

**Comment by jfhenon** [comment]
I can't reproduce this issue. 
according to this error message: 'npm' is not recognized as an internal or external command, 
Your nodejs environment is not properly installed.

**Comment by ravikandpal31** [comment]
Which node version supported by this app?
