### ISSUE TITLE
ImportSVG and save, re_open the svg , the use size not right

### ISSUE THREAD

**Issue by w8w8w8** [SVG-Edit/svgedit#971]
hi, thanks for the good project.
I am use the svgedit from 2017, 
today I found ,when I drop an  svg file to the workarea , then  change the size , and save.
then I reopen the svg , some size not right.

![image](https://github.com/SVG-Edit/svgedit/assets/4744039/28bd67e9-9631-412e-81dd-250367ba9436)

![image](https://github.com/SVG-Edit/svgedit/assets/4744039/cfdb6c78-36c4-48c0-bd6f-158387a2705b)

![image](https://github.com/SVG-Edit/svgedit/assets/4744039/7848afa5-16a9-4efe-afa2-2196234a3e78)

when I open the save svg file in edge, it is right! 
![image](https://github.com/SVG-Edit/svgedit/assets/4744039/83780a6c-e9a0-4891-9e96-41d709fa17a1)
 
there is the drop file:
![Centrifugal pump](https://github.com/SVG-Edit/svgedit/assets/4744039/97bdc411-5579-43c8-a0d9-5b34f20f8109)

there is the my sved svg file :
![243](https://github.com/SVG-Edit/svgedit/assets/4744039/fbd949fa-031e-403b-af18-3297f22f1c07)

![243](https://github.com/SVG-Edit/svgedit/assets/4744039/3143ad18-5af9-454f-b0fb-32d24d8b05c1)

in addition, how can find the svgedit version?  It is very old version what  I use the svgedit.

**Comment by w8w8w8** [comment]
I upload an svg file, if you load from the file , then will find that show result in svgedit != show in edge
![242--old](https://github.com/SVG-Edit/svgedit/assets/4744039/fd22e784-c00e-4048-a518-55f2e02416ca)

**Comment by w8w8w8** [comment]
if use svgedit 7.0, it is not wrong!
bug if try do test use 6.0, that wrong will be happened.  I do not konw how fix this question

**Comment by jfhenon** [comment]
If I understand well, your issue does not happen with the latest svgedit. In this case, you need to move to the latest vesion. It's unlikely that you will have someone to fix your issue on a previous version.

**Comment by jfhenon** [comment]
reopen if the issue is reproducible with V7

**Comment by w8w8w8** [comment]
@jfhenon  I use svgedit in my angular project, and I edit some svgedit code , and svgeditV7 can not run in angular project!
I want to fix this question

**Comment by w8w8w8** [comment]
> if use svgedit 7.0, it is not wrong! bug if try do test use 6.0, that wrong will be happened. I do not konw how fix this question
hello,  I think , the use element position incorrect, 

![image](https://github.com/SVG-Edit/svgedit/assets/4744039/54138519-0afd-4fbe-bb20-aafd42f8c8e4)

when inport svg , then set position x=0 and y=0 , it Outside the canvas
