### ISSUE TITLE
when I use loadFromString , but the Canvas is empty

### ISSUE THREAD

**Issue by w8w8w8** [SVG-Edit/svgedit#973]
![image](https://github.com/SVG-Edit/svgedit/assets/4744039/83ec1675-1782-4c7a-9b1e-56e9ad3e7147)

![image](https://github.com/SVG-Edit/svgedit/assets/4744039/4ad1c3b5-985a-4c1e-9b36-e3af7cc190cb)

![image](https://github.com/SVG-Edit/svgedit/assets/4744039/4b2194a8-e75b-49e0-93c5-f2f67f65be15)

set debugger:

![image](https://github.com/SVG-Edit/svgedit/assets/4744039/577ee67c-8667-4936-a019-e4ce59c6057a)

![image](https://github.com/SVG-Edit/svgedit/assets/4744039/a351a77d-4e6b-48b4-8837-eac6521136e4)

I have get svg string from my server, but can not loadFromString .  At the beginning, it was successful, but then suddenly it turned into a blank screen. Is that the method I used wrong?

**Comment by jfhenon** [comment]
which version of svgedit are you using?

**Comment by w8w8w8** [comment]
> which version of svgedit are you using?

7.2

**Comment by jfhenon** [comment]
I suggest to check the console for any error message.
You can also add the alert flag to the loadfromString which will display a console message in case of exception.

The code from Editor.js:

````
/**
   * @function module:SVGthis.loadFromString
   * @param {string} str The SVG string to load
   * @param {PlainObject} [opts={}]
   * @param {boolean} [opts.noAlert=false] Option to avoid alert to user and instead get rejected promise
   * @returns {Promise<void>}
   */
  loadFromString (str, { noAlert } = {}) {
    return this.ready(async () => {
      try {
        await this.loadSvgString(str, { noAlert })
      } catch (err) {
        if (noAlert) {
          throw err
        }
      }
    })
  }`

**Comment by jfhenon** [comment]
no reply so closing this issue. Please reopen if required.
