### ISSUE TITLE
fix not show/hide layers ICON

### ISSUE THREAD

**Issue by w8w8w8** [SVG-Edit/svgedit#980]
Because I made a lot of modifications and couldn't push, I wrote it here

src\editor\panels\LayersPanel.html
`<table id="layerlist">
                <tr class="layer">
                    <td class="layervis"></td>
                    <td class="layervis">
                        <img src="./images/eye.svg" width="14" height="14" />
                    </td>
                    <td class="layername">Layer 1</td>
                </tr>
            </table>`

src\editor\panels\LayersPanel.js

layerVis.className = (!drawing.getLayerVisibility(name)) ? 'layerinvis layervis' : 'layervis'

`      const _eye = document.createElement('img');
      _eye.src="./images/eye.svg";
      _eye.style.width = '14px';
      _eye.style.width = '14px';
      layerVis.appendChild(_eye);`

result:
![image](https://github.com/SVG-Edit/svgedit/assets/4744039/81682274-bc50-412f-8055-85f3545fbf76)

**Comment by jfhenon** [comment]
I'm sorry but I don't really understand your issue.

**Comment by w8w8w8** [comment]
![image](https://github.com/SVG-Edit/svgedit/assets/4744039/56602163-1769-4cf3-96c5-52db87b40033)

lost the eye icon (V7.2)!

I think , write the code fix it:
![image](https://github.com/SVG-Edit/svgedit/assets/4744039/9c71b827-c210-48e5-b49d-c93203fb00d1)
