### ISSUE TITLE
recalcRotatedPath is not a function

### ISSUE THREAD

**Issue by ckisme** [SVG-Edit/svgedit#991]
In path editing mode, if you drag a node to resize it, you will be prompted with "recalcRotatedPath is not a function"
![image](https://github.com/user-attachments/assets/ce1dfc5f-504c-4165-9a2c-de816a517891)

**Comment by jfhenon** [comment]
Sorry, I can't reproduce it. Can you describe the steps on a simple path?

**Comment by jfhenon** [comment]
Please reopen with a detail description of the steps if issue is still present.
