### ISSUE TITLE
Layer panel does not work as expected for layer created for orphan elements

### ISSUE THREAD

**Issue by VenissaCarolQuadros** [SVG-Edit/svgedit#997]
**PLEASE NOTE: We are trying to make this project live again. While you can file an issue, we will do our best but you should not expect any action, even if we label the issue. However, we are welcoming new contributors **

**Describe the bug**
When a new file is imported, if elements are not part of a layer they are automatically assigned to a layer. However, the 'eye' icon in the layer panel is not visible indicating that the layer is invisible but it is not. Also, toggling this does not modify the visibility.

**To Reproduce**
1. Go to https://svgedit.netlify.app/editor/index.html
2. Import the following SVG file : 
```
<svg width="254.00000000000003" height="105.83333" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg" version="1.1" xml:space="preserve">
<rect fill="#FF0000" height="11" id="svg_1" stroke="#000000" stroke-width="5" width="37" x="108.5" y="63.82"/>
</svg>
```
3. Try toggling visibility in the LayerPanel

**Expected behavior**
Completely functional LayerPanel for new layer created for orphan elements

**SVG-Edit environment (IMPORTANT)**
- File for SVG-Edit: [e.g., `svg-editor.html`, `svg-editor-es.html`, `embedapi.html`] ??
- Version: v7
- Protocol: https

**Desktop :**
 - OS: Windows
 - Browser Chrome
 - Version 29.0.6668.72

**Screenshots**
![image](https://github.com/user-attachments/assets/141c3223-0de0-489a-9a91-a80b81f51a0d)
![image](https://github.com/user-attachments/assets/caff3a67-4b75-4fa1-8c1f-1021af0ccd89)

**Potential resolution**
I believe the issue is caused by ['name'](https://github.com/SVG-Edit/svgedit/blob/master/packages/svgcanvas/core/draw.js#L524) not being defined. This results in it not being added to layer_map. Initializing name as 'getNewLayerName(layernames)' should resolve this.

Please let me know if I've been amiss in tracing the root cause.

**Comment by jfhenon** [comment]
you are right. fixing this.
